use crate::writeback::BridgeWritebackLoopDisposition;

use super::*;

#[test]
fn duplicate_certification_retains_typed_authority_matrix() {
    let host_request = crate::policy::BridgeExecutionPolicyBaseline::operational()
        .serial_request(worth_execution::CancellationToken::new(), None);
    let resource_request = worth_execution::ExecutionRequest::serial(&host_request);

    let WritebackHarnessExecution::DuplicateCertification {
        repeated_bundle_digest,
        replay_bundle_digest,
        duplicate_authority_matrix,
        counter_snapshot,
        ..
    } = certified_execution(
        WritebackHarnessTarget::DuplicateCertification,
        resource_request,
    )
    else {
        panic!("duplicate certification should produce duplicate typed matrix");
    };

    assert_eq!(repeated_bundle_digest, replay_bundle_digest);
    assert_eq!(
        duplicate_authority_matrix.writeback_digest(),
        replay_bundle_digest
    );
    assert_eq!(
        duplicate_authority_matrix.causality_digest(),
        duplicate_authority_matrix.causality().digest()
    );
    assert_eq!(
        duplicate_authority_matrix.truth_trigger_digest(),
        duplicate_authority_matrix
            .causality()
            .truth_trigger_digest()
    );
    assert_eq!(
        duplicate_authority_matrix.route_digest(),
        duplicate_authority_matrix.causality().route_digest()
    );
    assert_eq!(
        duplicate_authority_matrix.replay_bundle_report().digest(),
        replay_bundle_digest
    );
    assert_eq!(
        duplicate_authority_matrix.effect_intent_patch_canonical_basis(),
        duplicate_authority_matrix
            .replay_bundle_report()
            .effect_intent_patch_canonical_basis()
    );
    assert_eq!(
        duplicate_authority_matrix.effect().effect_intent(),
        duplicate_authority_matrix
            .authority_boundary_matrix()
            .first_authority_request()
            .effect_intent()
    );
    assert_eq!(
        duplicate_authority_matrix.effect().effect_intent(),
        duplicate_authority_matrix
            .authority_boundary_matrix()
            .repeated_authority_request()
            .effect_intent()
    );
    let authority_boundary = duplicate_authority_matrix.authority_boundary_matrix();
    assert_eq!(
        authority_boundary.contract_digest(),
        authority_boundary.contract().digest()
    );
    assert_eq!(
        authority_boundary.strategy_basis_digest(),
        authority_boundary.strategy_basis().digest()
    );
    assert_eq!(
        authority_boundary.first_strategy_coherence_digest(),
        authority_boundary.first_strategy_coherence().digest()
    );
    assert_eq!(
        authority_boundary.repeated_strategy_coherence_digest(),
        authority_boundary.repeated_strategy_coherence().digest()
    );
    assert_eq!(
        authority_boundary.first_candidate_digest(),
        authority_boundary.first_candidate().digest()
    );
    assert_eq!(
        authority_boundary.repeated_candidate_digest(),
        authority_boundary.repeated_candidate().digest()
    );
    assert_eq!(
        authority_boundary.contract_digest(),
        authority_boundary.first_candidate().contract_digest()
    );
    assert_eq!(
        authority_boundary.first_strategy_coherence_digest(),
        authority_boundary
            .first_candidate()
            .strategy_coherence_digest()
    );
    assert_eq!(
        authority_boundary.repeated_strategy_coherence_digest(),
        authority_boundary
            .repeated_candidate()
            .strategy_coherence_digest()
    );
    assert_eq!(
        duplicate_authority_matrix
            .authority_boundary_matrix()
            .first_authority_request()
            .effect_intent(),
        duplicate_authority_matrix
            .authority_boundary_matrix()
            .first_authority_receipt()
            .effect_intent()
    );
    assert_eq!(
        duplicate_authority_matrix
            .authority_boundary_matrix()
            .repeated_authority_request()
            .effect_intent(),
        duplicate_authority_matrix
            .authority_boundary_matrix()
            .repeated_authority_receipt()
            .effect_intent()
    );
    assert_eq!(
        duplicate_authority_matrix
            .replay_bundle_report()
            .replay_bundle()
            .effect_intent_digest(),
        duplicate_authority_matrix.effect_intent_digest()
    );
    assert_eq!(
        duplicate_authority_matrix
            .loop_prevention_report()
            .first_disposition(),
        BridgeWritebackLoopDisposition::AllowAuthoritativeAttempt
    );
    assert_eq!(
        duplicate_authority_matrix
            .loop_prevention_report()
            .first_digest(),
        duplicate_authority_matrix
            .loop_prevention_report()
            .first_loop_prevention()
            .digest()
    );
    assert_eq!(
        duplicate_authority_matrix
            .loop_prevention_report()
            .repeated_digest(),
        duplicate_authority_matrix
            .loop_prevention_report()
            .repeated_loop_prevention()
            .digest()
    );
    assert_eq!(
        duplicate_authority_matrix
            .loop_prevention_report()
            .current_feedback_provenance_digest(),
        duplicate_authority_matrix
            .loop_prevention_report()
            .first_loop_prevention()
            .current_feedback_provenance()
            .digest()
    );
    assert_eq!(
        duplicate_authority_matrix
            .first_attempt()
            .idempotence_digest(),
        duplicate_authority_matrix
            .first_attempt()
            .idempotence()
            .digest()
    );
    assert_eq!(
        duplicate_authority_matrix.first_attempt().outcome_digest(),
        duplicate_authority_matrix
            .first_attempt()
            .outcome()
            .digest()
    );
    assert_eq!(
        duplicate_authority_matrix
            .first_attempt()
            .replay_bundle_digest(),
        duplicate_authority_matrix
            .first_attempt()
            .replay_bundle()
            .digest()
    );
    assert_eq!(
        duplicate_authority_matrix.first_attempt().outcome_class(),
        duplicate_authority_matrix
            .first_attempt()
            .receipt()
            .outcome_class()
    );
    assert_eq!(
        duplicate_authority_matrix
            .repeated_attempt()
            .idempotence_digest(),
        duplicate_authority_matrix
            .repeated_attempt()
            .idempotence()
            .digest()
    );
    assert_eq!(
        duplicate_authority_matrix
            .boundedness_proof()
            .authoritative_commit_count(),
        1
    );
    assert_eq!(counter_snapshot.writeback_commit_count, 1);
    assert_eq!(counter_snapshot.writeback_noop_count, 1);
}
