[package]
name = "bank-courtroom"
edition.workspace = true
version.workspace = true
license.workspace = true
publish = false

[features]
cold-docker-courtroom = [
    "bank-http-adapter/cold-certification",
    "bank-user-node/cold-certification",
]

[dependencies]
bank-domain.workspace = true
bank-external-rail.workspace = true
bank-http-adapter.workspace = true
bank-server.workspace = true
bank-user-node.workspace = true
rand.workspace = true
reqwest.workspace = true
serde.workspace = true
serde_json.workspace = true
thirtyfour.workspace = true
tokio.workspace = true
url.workspace = true
worth-query-host.workspace = true

[[test]]
name = "async_identity_courtroom"
path = "tests/async_identity_courtroom.rs"
required-features = ["cold-docker-courtroom"]

[[test]]
name = "transport_process_courtroom"
path = "tests/transport_process_courtroom.rs"
required-features = ["cold-docker-courtroom"]

[[bin]]
name = "cold-bank-http-server"
path = "src/bin/cold-bank-http-server.rs"
required-features = ["cold-docker-courtroom"]

[[bin]]
name = "cold-bank-user-node"
path = "src/bin/cold-bank-user-node.rs"
required-features = ["cold-docker-courtroom"]

[[bin]]
name = "cold-bank-rail"
path = "src/bin/cold-bank-rail.rs"
required-features = ["cold-docker-courtroom"]

[lints]
workspace = true
