#[derive(Clone, Copy, Debug, Eq, PartialEq)]
pub enum UiMountedProjectionDenial {
    Identity(super::super::UiMountedIdentityDenial),
    UnknownGraphNode,
    MissingSurfaceBinding,
    MissingMosaicFocusScope(crate::graph::UiGraphNodeIdentity),
    AmbiguousMosaicFocusScope(crate::graph::UiGraphNodeIdentity),
    ForeignPlan,
    ForeignGraphWorld,
    ForeignMountIncarnation,
    ForeignAllocation,
    PreviewInstanceMismatch,
    CoordinateBasisMismatch,
    NonFiniteGeometry,
    NegativeExtent,
    TableCapacityExceeded,
    AmbiguousStaticPaintToken,
    MissingStaticPaintToken,
    ForeignStaticPaintToken,
    MissingStaticPaintColor,
    InvalidStaticPaintColor,
    MissingStaticPaintAllocation(crate::graph::UiGraphNodeIdentity),
    UnsupportedStaticPaintAllocation(crate::graph::UiGraphNodeIdentity),
    StaticPaintParticipationWithheld(crate::graph::UiGraphNodeIdentity),
    StaticPaintNodeReceiptMismatch,
    StaticPaintCapacityExceeded,
    StaticPaintCompletion(worth_ui_host_contract::UiMountedFilledRectCompletionDenial),
    PortalOverlayOwnerMissing,
    PortalOverlayCapacityExceeded,
    PortalOverlayCompletion(worth_ui_host_contract::UiMountedPortalOverlayCompletionDenial),
    AmbiguousPortalChildOwner,
    MissingSemanticTextColor,
    MissingSemanticTextFormatting {
        graph_node: crate::graph::UiGraphNodeIdentity,
        plan_index_available: bool,
        predecessor_available: bool,
        semantic_input_available: bool,
        theme_value_changed: bool,
    },
    MissingSemanticTextToken,
    ForeignSemanticTextToken,
    AmbiguousSemanticTextToken,
    InvalidSemanticTextColor,
    SemanticTextShapeMismatch,
    MissingSemanticCollectionPredecessor,
    InvalidSemanticCollectionPatch,
    SemanticTextLayerOrderExceeded,
    MissingSemanticTextAllocation(crate::graph::UiGraphNodeIdentity),
    UnsupportedSemanticTextAllocation(crate::graph::UiGraphNodeIdentity),
    SemanticTextNodeReceiptMismatch,
    SemanticTextCapacityExceeded,
    SemanticTextCompletion(worth_ui_host_contract::UiMountedSemanticTextCompletionDenial),
    SemanticTextQualification(worth_ui_text::UiTextQualificationDenial),
    SemanticTextReconstruction(worth_ui_text::UiTextReconstructionDenial),
    MissingSemanticTextReconstructionSource,
    AmbiguousDrawableOrder {
        instance: worth_ui_host_contract::UiMountedInstanceIdentity,
        layer: u32,
    },
    DrawableSourceCoverageMismatch,
    MissingHitTestOrder(crate::graph::UiGraphNodeIdentity),
    DuplicateHitTestOrder {
        surface: worth_ui_host_contract::UiSemanticSurfaceIdentity,
        order: worth_ui_host_contract::UiMountedHitTestOrder,
    },
    MissingHitTestAllocation(crate::graph::UiGraphNodeIdentity),
    UnsupportedHitTestAllocation(crate::graph::UiGraphNodeIdentity),
    HitTestParticipationWithheld(crate::graph::UiGraphNodeIdentity),
    HitTestNodeReceiptMismatch,
    HitTestCapacityExceeded,
    HitTestCompletion(worth_ui_host_contract::UiMountedHitTestCompletionDenial),
    VisualOverlayTargetMissing,
    VisualOverlaySurfaceMismatch,
    DuplicateLaneContribution,
    CostCounterOverflow,
    AppearanceSelectionBatchMismatch,
    AppearanceSelectionFrameMismatch,
    ProjectionOwnerUnavailable,
}

impl From<super::super::UiMountedIdentityDenial> for UiMountedProjectionDenial {
    fn from(denial: super::super::UiMountedIdentityDenial) -> Self {
        Self::Identity(denial)
    }
}
