//! Registration descriptor authority — types admitted during capability registration.

pub use crate::capability::{
    CommandCategory, CommandDescriptor, CommandId, CommandProjectionCommandReference,
    CommandProjectionDescriptor, CommandProjectionGrouping, CommandProjectionIconLabelPolicy,
    CommandProjectionId, CommandProjectionKey, CommandProjectionMeaningOverride,
    CommandProjectionMosaicScope, CommandProjectionOrdering, CommandProjectionOverflowBehavior,
    CommandProjectionReadinessDisplayPolicy, CommandProjectionShortcutVisibility,
    CommandProjectionSurface, ComponentAccessibilitySupport,
    ComponentAllocationMeasurementContract, ComponentAppearanceAspectContractDenial,
    ComponentCanvasSpatialContract, ComponentChildPolicy, ComponentDescriptor,
    ComponentExecutionLane, ComponentFocusContainerPolicy, ComponentFocusNavigationAxis,
    ComponentFocusSupport, ComponentHitTestClipContract, ComponentHitTestContract,
    ComponentHitTestInset, ComponentHitTestOrder, ComponentId, ComponentPortalChildContract,
    ComponentPropSchema, ComponentRealtimeOverlayContract, ComponentRealtimeOverlayContractDenial,
    ComponentRealtimeOverlayContractDenialReason, ComponentRealtimeOverlayPriority,
    ComponentSemanticTextContract, ComponentSemanticTextContractDenial,
    ComponentSemanticTextSpanContract, ComponentStateOwnership, ComponentStaticPaintContract,
    ComponentStaticPaintOrder, ComponentViewportAxisPlacement, ComponentViewportInset,
    ComponentViewportRegion, FrozenAppearanceThemeCapabilities,
    FrozenAppearanceThemeCapabilitiesDenial, IconAccessibilityPosture, IconColorSupport,
    IconDescriptor, IconFamily, IconId, IconKey, IconSizeSupport, IconSourceDescriptor,
    IconSourceKind, IconThemePosture, MeasurementConstraint, MeasurementValue, MosaicChildRule,
    MosaicClippingPosture, MosaicFocusScopeKind, MosaicHitTestPosture, MosaicMeasurementAuthority,
    MosaicOverflowBehavior, MosaicParentGrowthBehavior, MosaicPlacementAction,
    MosaicPlacementConflictBehavior, MosaicPlacementEligibility, MosaicPlacementPersistence,
    MosaicPlacementPolicyDescriptor, MosaicPlacementPolicyId, MosaicPlacementReloadReconciliation,
    MosaicPlacementSource, MosaicPlacementSupport, MosaicPlacementTarget,
    MosaicRegionKindDescriptor, MosaicRegionKindId, MosaicRegionPersistence, MosaicRegionRole,
    MosaicResizePermission, MosaicScrollOwnership, MosaicSizingBehavior,
    MosaicSizingContractDescriptor, MosaicSizingContractId, MosaicSizingKind,
    MosaicSizingPersistence, MosaicStableIdentityBehavior, MosaicStateOwnerIdentity,
    MosaicStateOwnerScopeId, MosaicStatePersistencePolicy, MosaicStateReconciliationKey,
    MosaicStateReplacementRule, MosaicStateSlotDescriptor, MosaicStateSlotId, MosaicStateSlotKind,
    MosaicStateTruthPosture, MosaicViewportConstraint, NamedMeasurementDefinition,
    NamedMeasurementToken, NativeCapabilityDescriptor, NativeCapabilityFamily, NativeCapabilityId,
    NativeCapabilityKey, NativePlatformPosture, NativeShellAuthorityClaim,
    PlatformInternalCapability, PluginCapabilityPermission, PluginContributionFamily,
    PluginSlotContributionReference, PluginSlotDescriptor, PluginSlotDiagnostics,
    PluginSlotGlobalMutationHook, PluginSlotId, PluginSlotKey, PluginSlotOrdering,
    PluginSlotSupportPosture, QueryDenialPresentation, RawColorOutsideTokenDefinition,
    RawIconAssetReference, RawLayoutMeasurementForDiagnostics, RawLayoutMeasurementKind,
    RuntimeOutcomeAffordance, RuntimeOutcomeDenialPosture, RuntimeOutcomeFamily,
    RuntimeOutcomePresentation, RuntimeOutcomeProjectionDescriptor, RuntimeOutcomeProjectionId,
    RuntimeOutcomeProjectionKey, RuntimeOutcomeRecoveryPosture, RuntimeOutcomeSourceReference,
    RuntimeOutcomeTone, SettingDefaultPosture, SettingDefaultValue, SettingDescriptor,
    SettingEditorHint, SettingId, SettingKey, SettingMigrationPosture, SettingOwnershipMetadata,
    SettingScope, SettingValidationPosture, SettingValueSchema, SurfaceDescriptor, SurfaceId,
    SurfaceKind, SurfacePlacementClass, SurfaceStateClass, TaskPresentationCancellationPosture,
    TaskPresentationDescriptor, TaskPresentationFailurePosture, TaskPresentationFamily,
    TaskPresentationId, TaskPresentationKey, TaskPresentationLifecyclePosture,
    TaskPresentationProjectionEligibility, TaskPresentationRuntimeAuthorityPosture,
    ThemeColorValue, ThemeColorValueError, ThemeTokenAlias, ThemeTokenDescriptor, ThemeTokenFamily,
    ThemeTokenId, ThemeTokenKey, ThemeTokenSource, ThemeTokenValue, UiCommandContextConsumption,
    UiCommandKeyCode, UiCommandLogicalKey, UiCommandModifierSet, UiCommandPhysicalKey,
    UiCommandRegistrationGeneration, UiCommandRegistrationOwner,
    UiCommandRegistrationOwnerIdentity, UiCommandRepeatPolicy, UiCommandRouteDeclaration,
    UiCommandRouteDestination, UiCommandRoutePriority, UiCommandRouteScope,
    UiCommandRouteScopeIdentity, UiCommandShortcutKey, UiCommandShortcutPlatform,
    UiCommandShortcutSequence, UiCommandShortcutStroke, UiCommandTextInputPolicy,
    UiThemeDefinition, UiThemeDefinitionDenial, UiThemeDefinitionIdentity, UiThemeSlotCatalog,
    UiThemeSlotCatalogDenial, UiThemeSlotDeclaration, UiThemeSlotDisclosure,
    UiThemeSlotSuccessorCompatibility, ViewBindingDescriptor, ViewBindingFamily, ViewBindingId,
    VisibleStateBindingDeclaration, WorthUiQueryViewRegistration, WorthUiViewBindingIdentity,
};
