//! Source-level name resolution from a facade module to defining items.
//!
//! Stable-toolchain only: the resolver reads module graphs with `syn` and
//! follows `pub use` chains (renames, `self`, globs, extern crates), crate-root
//! `#[macro_export]` macros, and items generated by local `macro_rules!`
//! invocations. It never decides visibility legality; rustc already has.
//!
//! - [`crate_index`] owns which crates are parsed and how extern names map to them
//! - [`use_bindings`] owns flattening `use` trees
//! - [`item_shape`] owns reading names, visibility, and cfg from `syn` items
//! - [`name_lookup`] owns one module's name table (explicit, glob, prelude)
//! - [`macro_generation`] owns attributing a name to a macro invocation

mod crate_index;
pub(crate) mod item_shape;
mod macro_generation;
mod name_lookup;
mod use_bindings;

pub(crate) use crate_index::{CrateId, CrateIndex};

use crate_index::ExternCrate;
use std::cell::RefCell;
use std::collections::{BTreeMap, BTreeSet};
use syn::Item;

/// What one resolved name denotes.
#[derive(Clone, Debug, Eq, Ord, PartialEq, PartialOrd)]
pub(crate) enum Definition {
    Module {
        krate: CrateId,
        path: Vec<String>,
    },
    /// A named item at `module` (`index` into that module node's items).
    Item {
        krate: CrateId,
        module: Vec<String>,
        index: usize,
    },
    Variant {
        krate: CrateId,
        module: Vec<String>,
        index: usize,
        variant: String,
    },
    /// An item a `macro_rules!` invocation at `module`/`invocation` generates.
    Generated {
        krate: CrateId,
        module: Vec<String>,
        invocation: usize,
        template: MacroTemplate,
    },
    /// Defined by a registry, git, or standard-library crate.
    OutsideWorkspace(String),
}

/// Where the `macro_rules!` definition behind a generated item lives.
#[derive(Clone, Debug, Eq, Ord, PartialEq, PartialOrd)]
pub(crate) struct MacroTemplate {
    pub(crate) krate: CrateId,
    pub(crate) module: Vec<String>,
    pub(crate) index: usize,
}

/// Which items a lookup may see, by declared visibility.
#[derive(Clone, Copy, Debug, Eq, Ord, PartialEq, PartialOrd)]
enum Reach {
    /// A path inside the defining crate: rustc already checked privacy.
    AnyVisibility,
    /// A same-crate glob: private items of the target stay out.
    CrateVisible,
    /// Another crate: only bare `pub` items.
    PublicOnly,
}

#[derive(Clone, Debug, Eq, Ord, PartialEq, PartialOrd)]
struct LookupKey {
    krate: CrateId,
    module: Vec<String>,
    name: String,
    reach: Reach,
    path_start: bool,
}

pub(crate) struct Resolver<'a> {
    crates: &'a CrateIndex,
    memo: RefCell<BTreeMap<LookupKey, Vec<Definition>>>,
    active: RefCell<BTreeSet<LookupKey>>,
}

impl<'a> Resolver<'a> {
    pub(crate) fn new(crates: &'a CrateIndex) -> Self {
        Self {
            crates,
            memo: RefCell::new(BTreeMap::new()),
            active: RefCell::new(BTreeSet::new()),
        }
    }

    pub(crate) fn crates(&self) -> &'a CrateIndex {
        self.crates
    }

    /// Every definition `segments` names when written inside `krate::module`.
    pub(crate) fn resolve_path(
        &self,
        krate: CrateId,
        module: &[String],
        segments: &[String],
    ) -> Result<Vec<Definition>, String> {
        let Some((first, rest)) = segments.split_first() else {
            return Ok(vec![module_definition(krate, module)]);
        };
        let (mut current, rest) = match first.as_str() {
            "::" => match rest.split_first() {
                Some((name, rest)) => (self.extern_root(krate, name)?, rest),
                None => return Ok(Vec::new()),
            },
            "crate" => (vec![module_definition(krate, &[])], rest),
            "self" => (vec![module_definition(krate, module)], rest),
            "super" => (vec![module_definition(krate, parent(module))], rest),
            _ => (
                self.lookup(krate, module, first, Reach::AnyVisibility, true)?,
                rest,
            ),
        };
        for segment in rest {
            current = self.descend(krate, current, segment)?;
        }
        Ok(current)
    }

    fn descend(
        &self,
        origin: CrateId,
        current: Vec<Definition>,
        segment: &str,
    ) -> Result<Vec<Definition>, String> {
        let mut next = Vec::new();
        for definition in current {
            match definition {
                Definition::Module { krate, path } if segment == "super" => {
                    next.push(module_definition(krate, parent(&path)));
                }
                Definition::Module { krate, path } => {
                    let reach = if krate == origin {
                        Reach::AnyVisibility
                    } else {
                        Reach::PublicOnly
                    };
                    next.extend(self.lookup(krate, &path, segment, reach, false)?);
                }
                Definition::Item {
                    krate,
                    module,
                    index,
                } => next.extend(self.enum_variant(krate, &module, index, segment)),
                Definition::OutsideWorkspace(path) => {
                    next.push(Definition::OutsideWorkspace(format!("{path}::{segment}")));
                }
                Definition::Variant { .. } | Definition::Generated { .. } => {}
            }
        }
        Ok(next)
    }

    fn extern_root(&self, krate: CrateId, name: &str) -> Result<Vec<Definition>, String> {
        Ok(match self.crates.extern_crate(krate, name)? {
            ExternCrate::Workspace(id) => vec![module_definition(id, &[])],
            ExternCrate::OutsideWorkspace => vec![Definition::OutsideWorkspace(name.to_owned())],
            ExternCrate::Unknown => Vec::new(),
        })
    }

    fn enum_variant(
        &self,
        krate: CrateId,
        module: &[String],
        index: usize,
        variant: &str,
    ) -> Option<Definition> {
        let indexed = self.crates.crate_at(krate);
        let Some(Item::Enum(item)) = indexed
            .graph
            .modules
            .get(module)
            .and_then(|node| node.items.get(index))
        else {
            return None;
        };
        item.variants
            .iter()
            .any(|candidate| candidate.ident == variant)
            .then(|| Definition::Variant {
                krate,
                module: module.to_vec(),
                index,
                variant: variant.to_owned(),
            })
    }
}

fn module_definition(krate: CrateId, path: &[String]) -> Definition {
    Definition::Module {
        krate,
        path: path.to_vec(),
    }
}

fn parent(module: &[String]) -> &[String] {
    module.split_last().map_or(module, |(_, parent)| parent)
}
