#[derive(Clone, Copy, Debug, Eq, PartialEq)]
pub enum PlatformPulseProductComponent {
    Root,
    MastheadBorder,
    Brand,
    RuntimeBadge,
    EvidenceBorder,
    EvidenceRail,
    EvidenceTitle,
    EvidenceBody,
    SourceSignalTitle,
    SourceSignalActive,
    EvidenceServiceLabel,
    EvidenceServiceBody,
    ServiceStage,
    ServiceStageBorder,
    QueryAccent,
    LowerShelfDivider,
    ServiceEyebrow,
    ServiceTitle,
    ServiceBody,
    QueryCard,
    QueryCardBorder,
    QueryLabel,
    NativeCard,
    NativeCardBorder,
    NativeLabel,
    NativeBody,
    QueryDenialLabel,
    QueryDenialBody,
    ActionTarget,
    ActionLabel,
    PortalTarget,
    PortalLabel,
    PortalSurface,
    PortalAccent,
    PortalTitle,
    PortalBody,
    PortalCancelTarget,
    PortalCancelLabel,
    PortalPrimaryTarget,
    PortalPrimaryLabel,
    ReviewTarget,
    ReviewLabel,
    ReviewSurface,
    ReviewTitle,
    ReviewBody,
    ReviewCancelTarget,
    ReviewCancelLabel,
    ReviewPrimaryTarget,
    ReviewPrimaryLabel,
    ConfirmationTarget,
    ConfirmationLabel,
    ProjectedStatus,
    StatusBand,
    StatusText,
}

impl PlatformPulseProductComponent {
    pub const ALL: [Self; 54] = [
        Self::Root,
        Self::MastheadBorder,
        Self::Brand,
        Self::RuntimeBadge,
        Self::EvidenceBorder,
        Self::EvidenceRail,
        Self::EvidenceTitle,
        Self::EvidenceBody,
        Self::SourceSignalTitle,
        Self::SourceSignalActive,
        Self::EvidenceServiceLabel,
        Self::EvidenceServiceBody,
        Self::ServiceStage,
        Self::ServiceStageBorder,
        Self::QueryAccent,
        Self::LowerShelfDivider,
        Self::ServiceEyebrow,
        Self::ServiceTitle,
        Self::ServiceBody,
        Self::QueryCard,
        Self::QueryCardBorder,
        Self::QueryLabel,
        Self::NativeCard,
        Self::NativeCardBorder,
        Self::NativeLabel,
        Self::NativeBody,
        Self::QueryDenialLabel,
        Self::QueryDenialBody,
        Self::ActionTarget,
        Self::ActionLabel,
        Self::PortalTarget,
        Self::PortalLabel,
        Self::PortalSurface,
        Self::PortalAccent,
        Self::PortalTitle,
        Self::PortalBody,
        Self::PortalCancelTarget,
        Self::PortalCancelLabel,
        Self::PortalPrimaryTarget,
        Self::PortalPrimaryLabel,
        Self::ReviewTarget,
        Self::ReviewLabel,
        Self::ReviewSurface,
        Self::ReviewTitle,
        Self::ReviewBody,
        Self::ReviewCancelTarget,
        Self::ReviewCancelLabel,
        Self::ReviewPrimaryTarget,
        Self::ReviewPrimaryLabel,
        Self::ConfirmationTarget,
        Self::ConfirmationLabel,
        Self::ProjectedStatus,
        Self::StatusBand,
        Self::StatusText,
    ];

    pub const fn id(self) -> &'static str {
        match self {
            Self::Root => "platform.pulse.component.seed",
            Self::MastheadBorder => "platform.pulse.component.masthead_border",
            Self::Brand => "platform.pulse.component.brand",
            Self::RuntimeBadge => "platform.pulse.component.runtime_badge",
            Self::EvidenceBorder => "platform.pulse.component.evidence_border",
            Self::EvidenceRail => "platform.pulse.component.evidence_rail",
            Self::EvidenceTitle => "platform.pulse.component.evidence_title",
            Self::EvidenceBody => "platform.pulse.component.evidence_body",
            Self::SourceSignalTitle => "platform.pulse.component.source_signal_title",
            Self::SourceSignalActive => "platform.pulse.component.source_signal_active",
            Self::EvidenceServiceLabel => "platform.pulse.component.evidence_service_label",
            Self::EvidenceServiceBody => "platform.pulse.component.evidence_service_body",
            Self::ServiceStage => "platform.pulse.component.service_stage",
            Self::ServiceStageBorder => "platform.pulse.component.service_stage_border",
            Self::QueryAccent => "platform.pulse.component.query_accent",
            Self::LowerShelfDivider => "platform.pulse.component.lower_shelf_divider",
            Self::ServiceEyebrow => "platform.pulse.component.service_eyebrow",
            Self::ServiceTitle => "platform.pulse.component.service_title",
            Self::ServiceBody => "platform.pulse.component.service_body",
            Self::QueryCard => "platform.pulse.component.query_card",
            Self::QueryCardBorder => "platform.pulse.component.query_card_border",
            Self::QueryLabel => "platform.pulse.component.query_label",
            Self::NativeCard => "platform.pulse.component.native_card",
            Self::NativeCardBorder => "platform.pulse.component.native_card_border",
            Self::NativeLabel => "platform.pulse.component.native_label",
            Self::NativeBody => "platform.pulse.component.native_body",
            Self::QueryDenialLabel => "platform.pulse.component.query_denial_label",
            Self::QueryDenialBody => "platform.pulse.component.query_denial_body",
            Self::ActionTarget => "platform.pulse.component.identity_target",
            Self::ActionLabel => "platform.pulse.component.action_label",
            Self::PortalTarget => "platform.pulse.component.portal_target",
            Self::PortalLabel => "platform.pulse.component.portal_label",
            Self::PortalSurface => "platform.pulse.component.portal_surface",
            Self::PortalAccent => "platform.pulse.component.portal_accent",
            Self::PortalTitle => "platform.pulse.component.portal_title",
            Self::PortalBody => "platform.pulse.component.portal_body",
            Self::PortalCancelTarget => "platform.pulse.component.portal_cancel_target",
            Self::PortalCancelLabel => "platform.pulse.component.portal_cancel_label",
            Self::PortalPrimaryTarget => "platform.pulse.component.portal_primary_target",
            Self::PortalPrimaryLabel => "platform.pulse.component.portal_primary_label",
            Self::ReviewTarget => "platform.pulse.component.review_target",
            Self::ReviewLabel => "platform.pulse.component.review_label",
            Self::ReviewSurface => "platform.pulse.component.review_surface",
            Self::ReviewTitle => "platform.pulse.component.review_title",
            Self::ReviewBody => "platform.pulse.component.review_body",
            Self::ReviewCancelTarget => "platform.pulse.component.review_cancel_target",
            Self::ReviewCancelLabel => "platform.pulse.component.review_cancel_label",
            Self::ReviewPrimaryTarget => "platform.pulse.component.review_primary_target",
            Self::ReviewPrimaryLabel => "platform.pulse.component.review_primary_label",
            Self::ConfirmationTarget => "platform.pulse.component.confirmation_target",
            Self::ConfirmationLabel => "platform.pulse.component.confirmation_label",
            Self::ProjectedStatus => "platform.pulse.component.projected_status",
            Self::StatusBand => "platform.pulse.component.status_band",
            Self::StatusText => "platform.pulse.component.status_text",
        }
    }

    pub fn authored_semantic_identity(self) -> String {
        format!("component:{}", self.id())
    }
}
