use super::QualifiedProfileRecord;

/// The closed record of `profiles/worth-ui-linux-x11-vulkan-v1.toml`.
pub(super) const RECORD: QualifiedProfileRecord = QualifiedProfileRecord {
    manifest_sha256: "0f60a2eb99d9e5bbeda54e84f430d97975eb832ee20d7536000194f5fd60eea5",
    strings: STRING_FIELDS,
    integers: INTEGER_FIELDS,
    booleans: BOOL_FIELDS,
};

const STRING_FIELDS: &[(&str, &str)] = &[
    ("identity", "worth-ui-linux-x11-vulkan-v1"),
    ("profile_stage", "current"),
    ("live_emission", "enabled"),
    ("platform", "linux-x86_64"),
    ("desktop", "x11-server"),
    ("event_backend", "winit-0.30.13"),
    ("event_backend_features", "rwh_06;wayland;wayland-dlopen;wayland-csd-adwaita;x11"),
    ("graphics_backend", "wgpu-29.0.4-vulkan-only"),
    ("graphics_backend_features", "std;parking_lot;vulkan;wgsl"),
    ("windowing_system", "x11"),
    ("device_features", "empty"),
    ("required_limits", "wgpu-29.0.4-Limits::downlevel_defaults().using_resolution(adapter.limits())"),
    ("runtime_backend_selection", "Backends::VULKAN"),
    ("joiner", "pollster-0.4.0"),
    ("adapter_order", "discrete;integrated;virtual;vendor-id;device-id;name;driver-info"),
    ("cpu_adapter", "deny"),
    ("other_adapter", "deny"),
    ("surface_format", "Bgra8UnormSrgb"),
    ("target_format", "Rgba8UnormSrgb"),
    ("present_mode", "Fifo"),
    ("composite_alpha", "Opaque"),
    ("shader_input", "logical-straight-rgba"),
    ("shader_output", "premultiplied-rgb-and-alpha"),
    ("blend", "src-One;dst-OneMinusSrcAlpha;op-Add"),
    ("filled_rect_antialiasing", "none"),
    ("appearance_surface_pipeline", "rounded-fill-inward-border"),
    ("appearance_outline_pipeline", "outside-ring-full-fringe"),
    ("appearance_antialiasing", "analytic-signed-distance-pixel-center"),
    ("appearance_primary_pointer", "mouse"),
    ("appearance_qualified_scales", "1.0;1.25;1.5;2.0"),
    ("text_antialiasing", "qualified-grayscale-coverage"),
    ("coordinate_rounding", "min-floor;max-ceil;half-open"),
    ("baseline_rgba", "0;0;0;0"),
    ("baseline_authority", "same-surface-binding-profile-runtime-receipt"),
    ("unsupported_mode", "typed-denial-before-effects-no-fallback"),
    ("initial_logical_size", "application-profile"),
    ("client_background", "opaque"),
    ("qualification_observations", "os-build;adapter-name;vendor-id;device-id;driver-info;scale-factors;required-modes;required-limits;pointer-event-position;move-dpi-order"),
    ("presented_source_observation", "retained-target-readback"),
    ("client_area_observation", "pulse-executable-world-x11rb-0.13.2-get-image"),
    ("client_window_observation", "winit-0.30.13-window-attributes"),
    ("native_pointer_position_observation", "winit-0.30.13-CursorMoved;event-ordered-client-origin;no-cursor-query"),
    ("reduced_motion_observation", "unobserved"),
    ("client_input_observation", "x11rb-0.13.2-xtest-fake-input"),
    ("client_visibility_transition_observation", "x11rb-0.13.2-override-redirect-cover;full-occlusion"),
];

const INTEGER_FIELDS: &[(&str, i64)] = &[
    ("sample_count", 1),
    ("appearance_version", 1),
    ("appearance_anti_alias_fringe_physical_pixels", 1),
    ("windows", 1),
    ("surfaces", 1),
    ("retained_commands", 4_096),
    ("surface_commands", 2_048),
    ("outline_commands", 1_024),
    ("backdrop_commands", 512),
    ("overlay_order_commands", 4_096),
    ("pointer_affordance_commands", 64),
    ("rectangle_commands", 2_048),
    ("text_commands", 2_048),
    ("damage_regions", 4_096),
    ("order_edits", 4_096),
    ("text_bytes", 1_048_576),
    ("readiness_owners", 8),
    ("resource_registry_entries", 32),
    ("causes_per_owner", 64),
    ("ready_owner_slots", 8),
    ("presentation_slots", 2),
    ("readback_slots", 4),
    ("readback_bytes", 16_777_216),
    ("gpu_wait_deadline_ms", 5_000),
    ("wheel_line_logical_subpixels", 40_000),
];

const BOOL_FIELDS: &[(&str, bool)] = &[("required_surface_compatibility", true)];
