use super::QualifiedProfileRecord;

/// The closed record of `profiles/worth-ui-windows-dx12-v2.toml`.
pub(super) const RECORD: QualifiedProfileRecord = QualifiedProfileRecord {
    manifest_sha256: "ab85b98751a3da4df2d48314faa62dc3561f1a0ed0d6402431e5a31b80a869f8",
    strings: STRING_FIELDS,
    integers: INTEGER_FIELDS,
    booleans: BOOL_FIELDS,
};

const STRING_FIELDS: &[(&str, &str)] = &[
    ("identity", "worth-ui-windows-dx12-v2"),
    ("profile_stage", "current"),
    ("live_emission", "enabled"),
    ("platform", "windows-11-x86_64"),
    ("desktop", "composition-enabled"),
    ("event_backend", "winit-0.30.13"),
    ("event_backend_features", "rwh_06"),
    ("graphics_backend", "wgpu-29.0.4-dx12-only"),
    ("graphics_backend_features", "std;parking_lot;dx12;wgsl"),
    ("windowing_system", "win32"),
    ("device_features", "empty"),
    ("required_limits", "wgpu-29.0.4-Limits::downlevel_defaults().using_resolution(adapter.limits())"),
    ("runtime_backend_selection", "Backends::DX12"),
    ("dx12_presentation_system", "DxgiFromVisual"),
    ("joiner", "pollster-0.4.0"),
    ("adapter_order", "discrete;integrated;virtual;vendor-id;device-id;name;driver-info"),
    ("cpu_adapter", "deny"),
    ("other_adapter", "deny"),
    ("surface_format", "Bgra8UnormSrgb"),
    ("target_format", "Rgba8UnormSrgb"),
    ("present_mode", "Fifo"),
    ("composite_alpha", "PreMultiplied"),
    ("shader_input", "logical-straight-rgba"),
    ("shader_output", "premultiplied-rgb-and-alpha"),
    ("blend", "src-One;dst-OneMinusSrcAlpha;op-Add"),
    ("filled_rect_antialiasing", "none"),
    ("appearance_surface_pipeline", "rounded-fill-inward-border"),
    ("appearance_outline_pipeline", "outside-ring-full-fringe"),
    ("appearance_antialiasing", "analytic-signed-distance-pixel-center"),
    ("appearance_primary_pointer", "mouse"),
    ("appearance_qualified_scales", "1.0;1.25;1.5;2.0"),
    ("text_antialiasing", "qualified-grayscale-coverage"),
    ("coordinate_rounding", "min-floor;max-ceil;half-open"),
    ("baseline_rgba", "0;0;0;0"),
    ("baseline_authority", "same-surface-binding-profile-runtime-receipt"),
    ("unsupported_mode", "typed-denial-before-effects-no-fallback"),
    ("initial_logical_size", "application-profile"),
    ("client_background", "transparent"),
    ("qualification_observations", "os-build;adapter-name;vendor-id;device-id;driver-info;scale-factors;required-modes;required-limits;message-position;wrapped-coordinate;move-dpi-order"),
    ("presented_source_observation", "retained-target-readback"),
    ("client_area_observation", "pulse-executable-world-xcap-0.9.7-wgc"),
    ("client_window_observation", "winsafe-0.0.28-dwm-kernel-user"),
    ("native_pointer_position_observation", "winsafe-0.0.28-user:GetMessagePos;event-ordered-client-origin;low16-wrapping;no-cursor-query"),
    ("reduced_motion_observation", "windows-0.61.3-UI_ViewManagement:UISettings.AnimationsEnabled"),
    ("client_input_observation", "uiautomation-0.25.0-control-input"),
    ("client_visibility_transition_observation", "winsafe-0.0.28-user:ShowWindow;iconic-state"),
];

const INTEGER_FIELDS: &[(&str, i64)] = &[
    ("sample_count", 1),
    ("appearance_version", 2),
    ("appearance_anti_alias_fringe_physical_pixels", 1),
    ("windows", 1),
    ("surfaces", 1),
    ("retained_commands", 4_096),
    ("surface_commands", 2_048),
    ("outline_commands", 1_024),
    ("backdrop_commands", 512),
    ("overlay_order_commands", 4_096),
    ("pointer_affordance_commands", 64),
    ("rectangle_commands", 2_048),
    ("text_commands", 2_048),
    ("damage_regions", 4_096),
    ("order_edits", 4_096),
    ("text_bytes", 1_048_576),
    ("readiness_owners", 8),
    ("resource_registry_entries", 32),
    ("causes_per_owner", 64),
    ("ready_owner_slots", 8),
    ("presentation_slots", 2),
    ("readback_slots", 4),
    ("readback_bytes", 16_777_216),
    ("gpu_wait_deadline_ms", 5_000),
    ("wheel_line_logical_subpixels", 40_000),
];

const BOOL_FIELDS: &[(&str, bool)] = &[("required_surface_compatibility", true)];
