mod helpers;
mod key_registry;
mod patch_buffer;
mod runtime;
#[cfg(test)]
mod tests;

pub(crate) use runtime::admit_signal_observation_request;
pub(crate) use runtime::RuntimeObservationRegistry;
pub(crate) use runtime::SignalCanonicalCallerUnwind;
pub(crate) use runtime::TemporalRuntimeState;
pub use runtime::{branch_state_proof_report, canonical_digest};
#[allow(unused_imports)]
pub use runtime::{
    bridge_signal_branch_basis_trust_boundary, bridge_signal_merge_compatibility_trust_boundary,
    lowered_strategy_bundle_digest, merge_lineage_digest, merge_plan_proof_report,
    merge_result_proof_report, replay_artifact_proof_report, replay_parity_proof_report,
    runtime_proof_report, temporal_certification_builder, temporal_certification_bundle,
    temporal_certification_bundle_parity_report, temporal_certification_record,
    temporal_replay_parity_report, AdvisoryRecord, ArtifactMergeAction, ArtifactMergeComparable,
    AspectMergeDecisionOutcome, AspectMergePolicy, AspectMergePolicyBinding,
    AspectMergePolicyDescriptor, AspectMergePolicyId, AspectMergePolicyName,
    AspectMergePolicyRegistration, AspectMergePolicySelectionBasis, AspectMergePolicyVersion,
    BatchChangeSession, BoundaryBridgedSignalBranchBasisArtifact,
    BoundaryBridgedSignalMergeCompatibilityArtifact, BoundedJournalSegment,
    BranchConflictResolutionPlan, BranchMergeBase, BranchMergeConflictEvidence,
    BranchMergeConflictKind, BranchMergeConflictRecord, BranchMergeConflictSummary,
    BranchMergeCounters, BranchMergeDeletionFailureEvidence, BranchMergeDivergence,
    BranchMergeExecutionSummary, BranchMergeFailureEvidence, BranchMergeFailureKind,
    BranchMergeIdentityFailureEvidence, BranchMergeKind, BranchMergePlan,
    BranchMergeReconciliationPolicy, BranchMergeRequest, BranchMergeRequestDenial,
    BranchMergeRequestScope, BranchMergeRequestScopeFamily, BranchMergeResolutionRequirement,
    BranchMergeResult, BranchMergeScopedDenialFailureEvidence, BranchMergeScopedDenialKind,
    BranchMergeScopedDeniedLocus, BranchMergeScopedUnavailableFailureEvidence,
    BranchMergeScopedUnavailableOutcomeKind, BranchMergeScopedUnavailableReason,
    BranchMergeStrategy, BranchMutationJournalSlice, BranchMutationLedger,
    BranchStateDenseGridProofBasis, BranchStateProofBasis, BranchStateProofReport,
    BranchTargetedTransactionDenial, BranchTargetedTransactionExecutionOutcome,
    BranchTargetedTransactionRequest, CausalityCarryPolicy, CheckpointBoundary, CheckpointRecord,
    CommittedObservationEventSummary, ConflictIsolationGranularity,
    ConflictIsolationPolicyDescriptor, ConflictIsolationPolicyId, ConflictIsolationPolicyName,
    ConflictIsolationPolicyRegistration, ConflictIsolationPolicyVersion,
    ConflictIsolationSelectionBasis, ConflictMergePolicy, ConflictPolicyDescriptor,
    ConflictPolicyId, ConflictPolicyName, ConflictPolicyRegistration, ConflictPolicySelectionBasis,
    ConflictPolicyVersion, ConflictResolutionRecord, ConflictResolutionStrategy,
    ConservativeOverlapExpansion, DecisionDetail, DecisionLog, DecisionRecord, DecisionSummary,
    DefinedComputation, DefinedKeyedComputation, DeletionMergePolicy, DeletionPolicyDescriptor,
    DeletionPolicyId, DeletionPolicyName, DeletionPolicyRegistration, DeletionPolicySelectionBasis,
    DeletionPolicyVersion, DependencyFingerprint, DependencyIndexRebuildProof,
    DependencyRemapRecord, DuplicateAspectMergePolicyRegistration,
    DuplicateConflictIsolationPolicyRegistration, DuplicateConflictPolicyRegistration,
    DuplicateDeletionPolicyRegistration, DuplicateIdentityMatcherRegistration,
    DuplicateMergeBaseStrategyRegistration, DuplicateMergeStrategyRegistration,
    DuplicateSourceOnlyPolicyRegistration, EvaluationSummary,
    ExecutedBranchTargetedTransactionReceipt, ExistingTargetMergePolicy,
    FoundationalScopeLoweringDenial, FrozenAspectMergePolicyRegistry,
    FrozenConflictIsolationRegistry, FrozenConflictPolicyRegistry, FrozenDeletionPolicyRegistry,
    FrozenIdentityMatcherRegistry, FrozenMergeBaseStrategyRegistry, FrozenMergeStrategyRegistry,
    FrozenSourceOnlyPolicyRegistry, IdentityCorrespondenceBasis, IdentityCorrespondenceRecord,
    IdentityCorrespondenceStatus, IdentityMatchPolicy, IdentityMatcherDescriptor,
    IdentityMatcherId, IdentityMatcherName, IdentityMatcherRegistration,
    IdentityMatcherSelectionBasis, IdentityMatcherVersion, IntegrityMarkers, JournalSegment,
    LoweredAspectMergeDecisionPlan, LoweredAspectMergeDecisionRecord,
    LoweredBranchTargetedTransactionPlan, LoweredConflictIsolationPlan,
    LoweredConflictIsolationRecord, LoweredDeletionPolicyPlan, LoweredFoundationalMergeRequest,
    LoweredIdentityCorrespondencePlan, LoweredMergeBasePlan, LoweredMergePlan, MatchingObserverSet,
    MergeBaseSelectionBasis, MergeBaseSelectionPolicy, MergeBaseStrategyDescriptor,
    MergeBaseStrategyId, MergeBaseStrategyName, MergeBaseStrategyRegistration,
    MergeBaseStrategyVersion, MergeBoundaryWitness, MergeBoundaryWitnessKind, MergeDecisionBasis,
    MergeNodeMap, MergePlanProofReport, MergeResultProofReport, MergeStrategyDescriptor,
    MergeStrategyId, MergeStrategyName, MergeStrategyRegistration, MergeStrategySelectionBasis,
    MergeStrategyVersion, MergeSupportRebuildProof, MergeTouchedNodeSet, MergedArtifactRecord,
    NodeMergeInputState, NodeMergePlan, NodeReconciliationDecision, NodeReconciliationShape,
    NormalizedBranchMergeRequest, NormalizedBranchMergeRequestScope, ObservationBoundaryOutcome,
    ObservationBoundarySummary, ObservationDeliveryMode, ObservationHandle, ObservationHandleId,
    ObservationListener, ObservationNotice, ObservationPolicy, ObservationReadContext,
    ObservationRegistrySummary, ObservationTrigger, ObservedNodeSet, ObserverId,
    PlannedMergeCandidateSet, PlannedRuntimeMerge, PlannedSignalBranchRetirement,
    PlannedSignalBranchRetirementBatch, ProofMinimalOverlapBasis, Recipe, ReconstructabilityProof,
    ReconstructabilityRecord, ReplayArtifactProofInput, ReplayArtifactProofReport,
    ReplayMismatchClass, ReplayParityProofReport, ReplaySuffixRebuildProof,
    RequiredDerivedRebuildSet, RetainedArtifactCarryPolicy, RuntimeArtifactCarryPolicy,
    RuntimeExecutionRequest, RuntimeHistory, RuntimeMaterializer, RuntimeMerge, RuntimeObserver,
    RuntimeProofReport, ScopedMergeProofPacket, SelectedMergeSemanticsBundle,
    SignalAspectPolicyInventoryEntry, SignalBranchBasis, SignalBranchBasisArtifact,
    SignalBranchBasisAuthority, SignalBranchBasisCompactExplanation, SignalBranchBasisDenial,
    SignalBranchBasisIdentity, SignalBranchBasisInspectionRow, SignalBranchBasisReady,
    SignalBranchBasisValidationOutcome, SignalBranchForkDenial, SignalBranchForkReceipt,
    SignalBranchForkRequest, SignalBranchForkRequestBasis, SignalBranchHeadPosture,
    SignalBranchRestorePosture, SignalBranchRetirementBatchDenial,
    SignalBranchRetirementBatchReceipt, SignalBranchRetirementDenial, SignalBranchRetirementReason,
    SignalBranchRetirementReceipt, SignalBranchTransactionHead, SignalCompatibilityInspectionRow,
    SignalDeliveryStrategyIdentity, SignalInvalidationStrategyIdentity,
    SignalMergeCompatibilityArtifact, SignalMergeCompatibilityAuthority,
    SignalMergeCompatibilityBasis, SignalMergeCompatibilityDenial,
    SignalMergeCompatibilityDenialKind, SignalMergeCompatibilityFactInventory,
    SignalMergeCompatibilityPostureKind, SignalMergeCompatibilityReadmissionAuthority,
    SignalMergeCompatibilityReady, SignalMergeCompatibilityWitness, SignalMergeStrategyIdentity,
    SignalMergeStrategyWitness, SignalMergeStrategyWitnessDenial,
    SignalMergeStrategyWitnessDenialKind, SignalMergeSupportInspectionAbsence,
    SignalMergeSupportInspectionAbsenceKind, SignalMergeSupportInspectionOutcome,
    SignalMergeSupportInspectionWitness, SignalMergeSupportReadinessPosture,
    SignalObservationAdmissionDenial, SignalObservationCompletion, SignalObservationRequest,
    SignalObservationSession, SignalObservationSurface, SignalRuntime, SignalRuntimeBuilder,
    SignalRuntimeConfig, SignalScopedMergeCanonicalBasisBundle,
    SignalScopedMergeCanonicalLocatorBundle, SignalScopedMergeDiagnosticRow,
    SignalScopedMergeInspectionRow, SignalScopedMergeLocatorBundle,
    SignalSelectedAspectRequestEntry, SignalStrategyInspectionRow, SignalTransaction,
    SourceNodeAdoptionPlanCore, SourceOnlyMergePolicy, SourceOnlyPolicyDescriptor,
    SourceOnlyPolicyId, SourceOnlyPolicyName, SourceOnlyPolicyRegistration,
    SourceOnlyPolicySelectionBasis, SourceOnlyPolicyVersion, StaleSignalBranchBasisArtifact,
    StructuralMergeCandidateRecord, StructuralMergeJournalSlice, TemporalCertificationBuilder,
    TemporalCertificationBundle, TemporalCertificationBundleMismatchClass,
    TemporalCertificationBundleParityReport, TemporalCertificationFailure,
    TemporalCertificationFamily, TemporalCertificationRecord, TemporalCertificationSummary,
    TemporalEligibilityFact, TemporalReconstructabilityArtifact, TemporalReplayMismatchClass,
    TemporalReplayParityReport, TemporalStateRebuildProof, TemporalTransactionEvidence,
    TransactionExecutionRequest, TransactionOutcome, TransactionReplayEntry, TransactionResult,
    TransactionTiming, ValidatedBranchTargetedTransactionRequest, BRANCH_STATE_PROOF_BASIS_VERSION,
    MERGE_PROOF_SCHEMA_VERSION, REQUIRED_TEMPORAL_CERTIFICATION_FAMILIES,
    SIGNAL_BRANCH_BASIS_SCHEMA_VERSION, SIGNAL_MERGE_COMPATIBILITY_SCHEMA_VERSION,
    TEMPORAL_CERTIFICATION_BUNDLE_PARITY_SCHEMA_VERSION,
    TEMPORAL_CERTIFICATION_BUNDLE_SCHEMA_VERSION, TEMPORAL_REPLAY_PARITY_SCHEMA_VERSION,
};
pub(crate) use runtime::{
    BranchState, SignalOwnerMetadataCloseBatch, SignalOwnerMetadataState, SignalOwnerPartition,
    SignalOwnerRetirementCleanup, SignalOwnerSnapshotReservationDenial, SnapshotBranchState,
    SnapshotStatePacket,
};
pub(crate) use runtime::{
    SignalObservationCaptureGate, SignalObservationDropCleanup, SignalObservationSessionState,
};
