[package]
name = "worth-query-topology-entry"
version.workspace = true
edition.workspace = true
publish.workspace = true

[dependencies]
worth-query-consumer-values.workspace = true
worth-query-decl.workspace = true
worth-query-host.workspace = true
worth-foundational = { path = "../../../../../../../crates/worth-foundational" }
