//! Primary Graph application contracts.

pub use crate::domain_computation::primary_graph::WorthQueryExecutionLeaseDenial;

pub use crate::domain_computation::{
    WorthQueryInvariantExecutionDenialKind, WorthQueryInvariantExecutionFailure,
    WorthQueryInvariantExecutionFailurePosture,
};

#[cfg(feature = "test-query-execution-observer")]
pub use crate::domain_computation::primary_graph::inexact_native_deliveries_on_this_thread_for_test;
#[cfg(feature = "test-query-execution-observer")]
pub use crate::domain_computation::primary_graph::query_read_kernel_entries_on_this_thread_for_test;
#[cfg(feature = "test-query-execution-observer")]
pub use crate::domain_computation::primary_graph::required_ready_custody_bytes_for_test;

pub use worth_relational::facade::{
    indexes::{DerivedIndexDiscardDenial, DerivedIndexDiscardOutcome, DerivedIndexDiscardRequest},
    lineage::{LineageEventKind, LineageEventRecord},
    publication::RecordStructuralChange,
};

pub use crate::domain_computation::application_aftermath::{
    compensate_recovery_handle, dispose_recovery_handle, expire_recovery_handle,
    inspect_recovery_handle, map_ordinary_commit_conflict, reconcile_recovery_handle,
    resolve_recovery_handle, safe_retry_recovery_handle, ExternalEffectCausalLink,
    ExternalEffectClassification, ExternalEffectCorrelationIdentity, ExternalEffectPosture,
    ExternalEffectPostureIdentity, ExternalEffectPostureKind, ExternalRailTransportFault,
    WorthQueryAdmittedIdempotencyRead, WorthQueryAftermathDerivationFailure,
    WorthQueryDispatchOutboxDurabilityPosture, WorthQueryDispatchOutboxRecord,
    WorthQueryExternalDispatchCausalRelation, WorthQueryExternalDispatchPosture,
    WorthQueryExternalDispatchPostureKind, WorthQueryExternalDispatchRequest,
    WorthQueryExternalEffectCausalLadder, WorthQueryExternalEffectDispatch,
    WorthQueryExternalEffectTransport, WorthQueryExternalTransportOutcome,
    WorthQueryInboundOccurrenceClaims, WorthQueryInboundOccurrenceVerifier,
    WorthQueryInboundVerificationDenial, WorthQueryOpaqueRecoveryWireIdentity,
    WorthQueryPerformedExternalRedispatch, WorthQueryRecoveryClaimStatus,
    WorthQueryRecoveryCompensateAdmission, WorthQueryRecoveryCurrentDecision,
    WorthQueryRecoveryDisclosureAdmission, WorthQueryRecoveryDisposalReceipt,
    WorthQueryRecoveryDurabilityPosture, WorthQueryRecoveryEffectAuthority,
    WorthQueryRecoveryExpiryDecision, WorthQueryRecoveryExpiryEvaluation, WorthQueryRecoveryHandle,
    WorthQueryRecoveryHandleBinding, WorthQueryRecoveryHandleDenial,
    WorthQueryRecoveryHandleDenialKind, WorthQueryRecoveryInspectAuthority,
    WorthQueryRecoveryInspectionView, WorthQueryRecoveryReconcileAdmission,
    WorthQueryRecoverySafeRetryAdmission, WorthQueryRecoverySafeRetryDenial,
};
pub use crate::domain_computation::primary_graph::output_lineage::{
    WorthQueryPriorOutputDenial, WorthQueryPriorOutputDenialKind,
};
pub use crate::domain_computation::primary_graph::{
    CandidateWriter, DecisionReader, HandlerExecutionDenial, HandlerInterruption, HandlerResult,
    MutationHandlerExecutionDenial, OperationHandler,
    WorthQueryAdmittedApplicationCapabilityAccess,
    WorthQueryAdmittedApplicationConditionalDefinition, WorthQueryAdmittedApplicationOperation,
    WorthQueryAdmittedApplicationQueryControls, WorthQueryAdmittedApplicationQueryPlan,
    WorthQueryAdmittedDisclosedApplicationResult, WorthQueryAdmittedInboundOccurrence,
    WorthQueryAdmittedOutputDemand, WorthQueryAdmittedProgramMigration,
    WorthQueryApplicationAttemptDenial, WorthQueryApplicationAttemptDenialKind,
    WorthQueryApplicationAuthorizationExplanationCause,
    WorthQueryApplicationAuthorizationWorkEvidence, WorthQueryApplicationBasisObservation,
    WorthQueryApplicationBasisObserver, WorthQueryApplicationBasisReleaseOutcome,
    WorthQueryApplicationBasisSelectionIdentity, WorthQueryApplicationBatchReadDenial,
    WorthQueryApplicationBatchResult, WorthQueryApplicationCommitAuthorityBinding,
    WorthQueryApplicationCommitDeferred, WorthQueryApplicationCommitDeferredKind,
    WorthQueryApplicationCommitDenial, WorthQueryApplicationCommitDenialKind,
    WorthQueryApplicationCommitDenialStage, WorthQueryApplicationCommitOutcome,
    WorthQueryApplicationCommitOutcomeIdentity, WorthQueryApplicationCommitPublicationSource,
    WorthQueryApplicationCommitReceipt, WorthQueryApplicationCommitRecoveryKind,
    WorthQueryApplicationCommitTerminalEvidence, WorthQueryApplicationCommitTerminalKind,
    WorthQueryApplicationCommittedChanges,
    WorthQueryApplicationConditionalDefinitionAdmissionDenial,
    WorthQueryApplicationContinuationDenial, WorthQueryApplicationContinuationDenialKind,
    WorthQueryApplicationContinuationPageResult, WorthQueryApplicationDependentOutputConnection,
    WorthQueryApplicationDisclosed, WorthQueryApplicationDisclosureDecisionFact,
    WorthQueryApplicationDisclosureOutcome, WorthQueryApplicationDisclosureOutcomeIdentity,
    WorthQueryApplicationDisclosureReceipt, WorthQueryApplicationDisclosureReceiptPosture,
    WorthQueryApplicationDiscoveredOutputConnection, WorthQueryApplicationEffectEntity,
    WorthQueryApplicationEffectProgram, WorthQueryApplicationEffectProgramBuilder,
    WorthQueryApplicationEntityIdentity, WorthQueryApplicationEntityKey,
    WorthQueryApplicationEntityKeyDenial, WorthQueryApplicationEntitySeed,
    WorthQueryApplicationIdempotencyBinding, WorthQueryApplicationIdempotencyResolution,
    WorthQueryApplicationIdempotencyResolutionDenial,
    WorthQueryApplicationIdempotencyResolutionDenialKind,
    WorthQueryApplicationInvariantProjectionAuthority,
    WorthQueryApplicationInvariantProjectionReader,
    WorthQueryApplicationInvariantProjectionSnapshot, WorthQueryApplicationLiveCauseDenialKind,
    WorthQueryApplicationLiveCloseOutcome, WorthQueryApplicationLiveControlDenial,
    WorthQueryApplicationLiveControls, WorthQueryApplicationLiveDeliveryCloseReceipt,
    WorthQueryApplicationLiveLease, WorthQueryApplicationLiveOpenDenial,
    WorthQueryApplicationLiveOpenDenialKind, WorthQueryApplicationLiveOutcome,
    WorthQueryApplicationLiveOverflow, WorthQueryApplicationLiveUpdate,
    WorthQueryApplicationOmission, WorthQueryApplicationOneShotDenial,
    WorthQueryApplicationOneShotDenialKind, WorthQueryApplicationOneShotResult,
    WorthQueryApplicationOperationInvariantProjectionReader,
    WorthQueryApplicationOperationInvariantProjectionSnapshot,
    WorthQueryApplicationOutputDemandDisclosure, WorthQueryApplicationOutputDemandSource,
    WorthQueryApplicationOutputEntity, WorthQueryApplicationOutputFamilyEntry,
    WorthQueryApplicationOutputPosture, WorthQueryApplicationOutputProjectionDenial,
    WorthQueryApplicationPrincipalIdentity, WorthQueryApplicationPrincipalKey,
    WorthQueryApplicationPrincipalKeyDenial, WorthQueryApplicationProductBranchCloseDenial,
    WorthQueryApplicationProductBranches, WorthQueryApplicationProjection,
    WorthQueryApplicationProjectionDenial, WorthQueryApplicationProjectionDenialKind,
    WorthQueryApplicationProjectionRow, WorthQueryApplicationProjectionRows,
    WorthQueryApplicationQueryAccessContext, WorthQueryApplicationQueryAccessReceipt,
    WorthQueryApplicationQueryAdmissionDenial, WorthQueryApplicationQueryAdmissionDenialKind,
    WorthQueryApplicationQueryBasisPosture, WorthQueryApplicationQueryBatchAdmission,
    WorthQueryApplicationQueryBatchLimits, WorthQueryApplicationQueryBatchMemory,
    WorthQueryApplicationQueryBatchReadPlan, WorthQueryApplicationQueryBatchResourceDenial,
    WorthQueryApplicationQueryBatchWork, WorthQueryApplicationQueryConsistency,
    WorthQueryApplicationQueryContinuation, WorthQueryApplicationQueryFreshness,
    WorthQueryApplicationQueryOmissionPosture, WorthQueryApplicationQueryResumeControls,
    WorthQueryApplicationQueryWorkEvidence, WorthQueryApplicationReadAttempt,
    WorthQueryApplicationReadObservation, WorthQueryApplicationRelationSeed,
    WorthQueryApplicationRequiredOutputConnection, WorthQueryApplicationRequiredOutputSource,
    WorthQueryApplicationResultBufferEvidence, WorthQueryApplicationResultBufferObservation,
    WorthQueryApplicationResultBufferObserver, WorthQueryApplicationRetainedCommitOutcome,
    WorthQueryApplicationSettlementDeferred, WorthQueryApplicationSettlementNextAction,
    WorthQueryApplicationSettlementRecoveryError, WorthQueryApplicationStaleAttempt,
    WorthQueryApplicationTypedOutputCorrespondence, WorthQueryApplicationUncommitted,
    WorthQueryApplicationUnresolvedCommitEvidence, WorthQueryApprovedElevation,
    WorthQueryAuthenticatedInboundOccurrence, WorthQueryAuthenticatedPrincipal,
    WorthQueryBoundSourceExpectation, WorthQueryBranchAdoptionActivationDenial,
    WorthQueryBranchAdoptionPreparationDenial, WorthQueryBranchAdoptionPublicationOutcome,
    WorthQueryBranchAdoptionRecovery, WorthQueryBranchAdoptionRecoveryDenial,
    WorthQueryBranchAdoptionRecoveryFailure, WorthQueryBranchAdoptionRecoveryOutcome,
    WorthQueryBranchAdoptionRecoveryReleaseFailure, WorthQueryBranchSetAdoptionAdvanceDenial,
    WorthQueryBranchSetAdoptionCancellation, WorthQueryBranchSetAdoptionCloseDenial,
    WorthQueryBranchSetAdoptionPreparationDenial, WorthQueryBranchSetAdoptionProgress,
    WorthQueryBranchSetAdoptionRecovery, WorthQueryBranchSetAdoptionRecoveryFailure,
    WorthQueryBranchSetAdoptionRecoveryOutcome, WorthQueryBranchSetAdoptionRecoveryReleaseFailure,
    WorthQueryBranchSetAdoptionResumeDenial, WorthQueryBranchSetAdoptionResumeFailure,
    WorthQueryBridgeGranularDeliveryCounters, WorthQueryCapabilityRevocationProgram,
    WorthQueryClosedBranchSetAdoption, WorthQueryCommittedProductPublication,
    WorthQueryCompleteApplicationReadSet, WorthQueryCompletedGeneratedOutputReconstruction,
    WorthQueryCompletedInvariantProjection, WorthQueryCompletedMutationCandidate,
    WorthQueryCompletedOperationInvariantProjection,
    WorthQueryConditionalApplicationRuntimeInstallation, WorthQueryConditionalClockHandle,
    WorthQueryConditionalClockObservationDenial, WorthQueryConditionalClockObservationDenialKind,
    WorthQueryConditionalClockObservationFailure, WorthQueryConditionalClockObservationFailureKind,
    WorthQueryConditionalClockObservationOutcome, WorthQueryConditionalClockObservationPort,
    WorthQueryConditionalClockObservationReceipt, WorthQueryConditionalDefinitionPublicationDenial,
    WorthQueryConditionalDefinitionPublicationOutcome, WorthQueryConditionalExecutionCause,
    WorthQueryConditionalExecutionProvenance, WorthQueryConditionalExecutionTerminal,
    WorthQueryConditionalRuntimeInspection, WorthQueryConditionalRuntimeInstallationDenial,
    WorthQueryConditionalRuntimeInstallationDenialKind, WorthQueryConditionalRuntimeLifecycleProbe,
    WorthQueryConditionalRuntimeReinstallationReceipt, WorthQueryConditionalSignalDecision,
    WorthQueryCorrelatedInboundOccurrence, WorthQueryCurrentOutputDenial,
    WorthQueryCurrentOutputDenialKind, WorthQueryCurrentOutputSelection,
    WorthQueryCustomInvariantDenial, WorthQueryDelegationActivationProgram,
    WorthQueryElevationApprovalAuthorizationDenial, WorthQueryElevationApprovalOutcome,
    WorthQueryElevationApprovalProgram, WorthQueryElevationCloseAuthorizationDenial,
    WorthQueryElevationCloseOutcome, WorthQueryElevationCloseProgram,
    WorthQueryElevationClosureKind, WorthQueryElevationRequestOutcome,
    WorthQueryElevationRequestProgram, WorthQueryEntityResolutionDenial,
    WorthQueryEntityResolutionDenialKind, WorthQueryExternalDispatchAttemptDenial,
    WorthQueryExternalDispatchPreparationDenial, WorthQueryExternalRedispatchDenial,
    WorthQueryExternalTransportInstallationDenial, WorthQueryGeneratedEntity,
    WorthQueryGeneratedOutputInvariantAdmissionDenial,
    WorthQueryGeneratedOutputPublicationNoEffect,
    WorthQueryGeneratedOutputPublicationNoEffectCause, WorthQueryGeneratedOutputReconstruction,
    WorthQueryGeneratedOutputReconstructionDenial, WorthQueryGeneratedOutputReconstructionFailure,
    WorthQueryGeneratedOutputRestorationFailure, WorthQueryGeneratedOutputRestorationFailureCause,
    WorthQueryGeneratedOutputRestorationReceipt, WorthQueryGeneratedOutputRestorationRecovery,
    WorthQueryGeneratedOutputRestorationRecoveryFailure,
    WorthQueryGeneratedOutputRestorationRecoveryStage, WorthQueryGeneratedOutputSuspensionDenial,
    WorthQueryGeneratedOutputSuspensionFailure, WorthQueryGeneratedOutputSuspensionRecovery,
    WorthQueryGeneratedOutputSuspensionRecoveryFailure,
    WorthQueryGeneratedOutputSuspensionRecoveryStage,
    WorthQueryGovernedTemporalOperationAuthorization, WorthQueryGovernedTemporalQueryAuthorization,
    WorthQueryGranularInvalidationCoverage, WorthQueryGranularInvalidationDeliveryBatch,
    WorthQueryGranularInvalidationInstallation, WorthQueryGranularInvalidationObservation,
    WorthQueryGranularSourceReadBasis, WorthQueryGranularTransportMergeDenial,
    WorthQueryHistoricalApplicationCommit, WorthQueryInboundAdmissionDenial,
    WorthQueryInboundAuthenticatedPermanentDenial, WorthQueryInboundCleanupReport,
    WorthQueryInboundCostObservation, WorthQueryInboundIndexRepairDenial,
    WorthQueryInboundMaintenanceReport, WorthQueryInboundPendingReason,
    WorthQueryInboundPermanentDenialKind, WorthQueryInboundReceipt,
    WorthQueryInboundReceiptPosture, WorthQueryInboundSourceControlDenial,
    WorthQueryInboundSourcePosture, WorthQueryInboundTerminalObservation,
    WorthQueryInboundVerifierHandle, WorthQueryInboundVerifierInstallationDenial,
    WorthQueryInspectedOperationInvariantProjection, WorthQueryInvariantAggregate,
    WorthQueryInvariantAggregateDenial, WorthQueryInvariantAggregateDenialKind,
    WorthQueryInvariantDecisionPlanDenial, WorthQueryInvariantDecisionPlanDenialKind,
    WorthQueryInvariantEntityIdentity, WorthQueryInvariantMutationTarget,
    WorthQueryInvariantProjectionDenial, WorthQueryInvariantProjectionDenialKind,
    WorthQueryInvariantProjectionTraversalDenial, WorthQueryInvariantProjectionTraversalDenialKind,
    WorthQueryInvariantProjectionWork, WorthQueryInvariantRelation,
    WorthQueryManagedApplicationRecoveryDenial, WorthQueryManagedApplicationRecoveryOutcome,
    WorthQueryManagedApplicationRecoveryPerformed,
    WorthQueryManagedDerivedCollectionBatchRefreshDenial, WorthQueryManagedDerivedMemberToken,
    WorthQueryManagedDerivedStorageQuote, WorthQueryManagedDerivedValue,
    WorthQueryManagedDerivedView, WorthQueryManagedDerivedViewDenial,
    WorthQueryManagedDerivedViewKey, WorthQueryManagedDerivedViewReconciliation,
    WorthQueryManagedDerivedViewSnapshot, WorthQueryMandatoryReview,
    WorthQueryMandatoryReviewAuthorizationDenial, WorthQueryMandatoryReviewOutcome,
    WorthQueryMandatoryReviewProgram, WorthQueryMutationHandlerExecutionReport,
    WorthQueryMutationHandlerProjectionWork, WorthQueryMutationHandlerWork,
    WorthQueryMutationPreconditionComparisonEvidence, WorthQueryObservedApplicationRelation,
    WorthQueryObservedResultSet, WorthQueryObservedSource, WorthQueryOperationAuthorizationDenial,
    WorthQueryOperationAuthorizationDenialIdentity, WorthQueryOperationAuthorizationDenialKind,
    WorthQueryOperationProjectionDenial, WorthQueryOperationProjectionDenialKind,
    WorthQueryOperationScopeBinding, WorthQueryOperationScopeEntityBinding,
    WorthQueryOrderedProgramAdoptionCoverage, WorthQueryOrdinaryApplicationRead,
    WorthQueryOrdinaryReadBatch, WorthQueryOrdinaryReadMetadata, WorthQueryOrdinaryReadProjection,
    WorthQueryOrdinaryReadVersion, WorthQueryOutputDemandAdvance, WorthQueryOutputDemandDenial,
    WorthQueryOutputDemandDenialKind, WorthQueryOutputDemandNotifications,
    WorthQueryOutputDemandRecoveryPosture, WorthQueryOutputDemandSettlement,
    WorthQueryOutputReadinessDeliveryEvidence, WorthQueryOutputSettlementPosture,
    WorthQueryPendingSourceExpectation, WorthQueryPerformedBranchAdoption,
    WorthQueryPerformedConditionalDefinitionPublication, WorthQueryPreparedBranchAdoption,
    WorthQueryPreparedBranchSetAdoption, WorthQueryPreparedEntitySelection,
    WorthQueryPreparedProgramMigration, WorthQueryPreparedRequiredOutputSource,
    WorthQueryPrimaryGraph, WorthQueryPrimaryGraphApplicationReadinessSnapshot,
    WorthQueryPrimaryGraphApplicationRuntime, WorthQueryPrimaryGraphBootstrap,
    WorthQueryPrimaryGraphInstallationDenial, WorthQueryPrimaryGraphInstallationDenialKind,
    WorthQueryPrimaryGraphPublication, WorthQueryPrimaryMutationWorkEvidence,
    WorthQueryPrincipalResolutionDenial, WorthQueryPrincipalResolutionDenialKind,
    WorthQueryPrincipalResolutionMode, WorthQueryPriorOutputFamilyMember,
    WorthQueryProductBranchAdmissionDenial, WorthQueryProductBranchLease,
    WorthQueryProductBranchReadIdentity, WorthQueryProductObservationLease,
    WorthQueryProductQueryControls, WorthQueryProductStaleApplication,
    WorthQueryProductUnpublishedApplication, WorthQueryProductUnpublishedRecovery,
    WorthQueryProgramAdoptionCoverage, WorthQueryProgramAdoptionCoverageDenial,
    WorthQueryProgramCustodyDisposition, WorthQueryProgramCustodyDispositionInventory,
    WorthQueryProgramCustodyDispositionKind, WorthQueryProgramMigrationDescription,
    WorthQueryProgramMigrationPreparationDenial, WorthQueryProjectedApplicationMutation,
    WorthQueryPublicTemporalOperationAuthorization, WorthQueryPublicTemporalQueryAuthorization,
    WorthQueryReconstructedOutputEntity, WorthQueryRequestedElevation,
    WorthQueryRequiredOutputConnectionDenial, WorthQueryRequiredOutputSourcePreparationFailure,
    WorthQueryRestoredGeneratedOutput, WorthQueryRetainedBatchQueryAdmissionDenial,
    WorthQueryRetainedGeneratedOutputEntity, WorthQueryReviewedElevation,
    WorthQueryRuntimeTimeSource, WorthQueryRuntimeTimeSourceDenial,
    WorthQuerySelectedApplicationProducer, WorthQuerySelectedProductOperation,
    WorthQuerySelectedProgramInspection, WorthQuerySelectedProgramInspectionDenial,
    WorthQuerySourceExpectationDenial, WorthQuerySourceExpectationDenialKind,
    WorthQueryStoppedBranchSetAdoption, WorthQuerySuspendedGeneratedOutput,
    WorthQueryTemporalInvocationFailure, WorthQueryTemporalInvocationFailureKind,
    WorthQueryTemporalOperationAuthorization, WorthQueryTemporalOperationExecution,
    WorthQueryTemporalOperationInvoker, WorthQueryTemporalPrincipalAdmission,
    WorthQueryTemporalPrincipalFailure, WorthQueryTemporalPrincipalFailureKind,
    WorthQueryTemporalPrincipalSource, WorthQueryTemporalQueryAuthorization,
    WorthQueryTemporalQueryAuthorizationDenial, WorthQueryTemporalReconstructionAccess,
    WorthQueryTouchedRecordIdentity, WorthQueryUnpublishedBranchAdoption,
    WorthQueryUnpublishedGeneratedOutputRestoration,
};
pub use crate::domain_computation::primary_graph::{
    WorthQueryCommittedDispatchOutboxObservation, WorthQueryCommittedDispatchOutboxReadDenial,
    WorthQueryCommittedDispatchOutboxReadWork,
};
pub use crate::domain_computation::primary_graph::{
    WorthQueryWorkflowAdoptionInventory, WorthQueryWorkflowCompatibility,
    WorthQueryWorkflowDefinitionDisposition, WorthQueryWorkflowDefinitionOccurrence,
    WorthQueryWorkflowDispositionDenial, WorthQueryWorkflowDispositions,
    WorthQueryWorkflowIncompatibility, WorthQueryWorkflowInstanceCustody,
    WorthQueryWorkflowInstanceDisposition, WorthQueryWorkflowInstanceOccurrence,
};
pub use crate::domain_computation::runtime_time::WorthQueryRuntimeTimeSample;
pub use crate::domain_computation::{
    WorthQueryProductUnpublishedRecoveryFailure, WorthQueryProductUnpublishedRecoveryReleaseDenial,
    WorthQueryProductUnpublishedRecoveryReleaseFailure,
};
pub use worth_runtime_bridge::facade::RelationalBridgeRecordIdentityParts;
pub use worth_runtime_world::facade::{
    ProductUnpublishedNextAction, ProductUnpublishedRecoveryHandle, RecoveryContinuationContract,
    RuntimeWorldRecoveryCursor, RuntimeWorldRecoveryDenial, RuntimeWorldRecoveryPage,
    RuntimeWorldServiceDenial, RuntimeWorldSettledRelationalAdoptionDenial,
};
pub use worth_signal::facade::runtime::SignalConditionalEvaluationBudget;

pub use crate::domain_computation::primary_graph::WorthQueryApplicationSourceAdjacencyEndpoints;
