use crate::performance::data::RuntimeComplexityCounters;

macro_rules! complexity_operations {
    ($($field:ident),+ $(,)?) => {
        pub(crate) fn complexity_delta(
            before: RuntimeComplexityCounters,
            after: RuntimeComplexityCounters,
        ) -> RuntimeComplexityCounters {
            let mut delta = RuntimeComplexityCounters {
                $($field: after.$field.saturating_sub(before.$field),)+
                commit_topology_flags: after.commit_topology_flags,
            };
            copy_commit_gauges(&mut delta, &after);
            delta
        }

        pub(crate) fn complexity_delta_without_commit_gauges(
            before: RuntimeComplexityCounters,
            after: RuntimeComplexityCounters,
        ) -> RuntimeComplexityCounters {
            let mut delta = complexity_delta(before, after);
            clear_commit_gauges(&mut delta);
            delta
        }

        pub(crate) fn combine_complexity_deltas(
            left: RuntimeComplexityCounters,
            right: RuntimeComplexityCounters,
        ) -> RuntimeComplexityCounters {
            let mut combined = RuntimeComplexityCounters {
                $($field: left.$field.saturating_add(right.$field),)+
                commit_topology_flags: right.commit_topology_flags,
            };
            copy_commit_gauges(&mut combined, &right);
            combined
        }
    };
}

fn copy_commit_gauges(target: &mut RuntimeComplexityCounters, source: &RuntimeComplexityCounters) {
    target.commit_topology_flags = source.commit_topology_flags;
    target.partitions_touched_by_commit = source.partitions_touched_by_commit;
    target.entity_slots_touched_by_commit = source.entity_slots_touched_by_commit;
    target.relation_slots_touched_by_commit = source.relation_slots_touched_by_commit;
    target.bulk_entity_slots_reserved = source.bulk_entity_slots_reserved;
    target.bulk_relation_slots_reserved = source.bulk_relation_slots_reserved;
}

fn clear_commit_gauges(counters: &mut RuntimeComplexityCounters) {
    counters.commit_topology_flags = 0;
    counters.partitions_touched_by_commit = 0;
    counters.entity_slots_touched_by_commit = 0;
    counters.relation_slots_touched_by_commit = 0;
    counters.bulk_entity_slots_reserved = 0;
    counters.bulk_relation_slots_reserved = 0;
}

complexity_operations!(
    full_state_clones,
    reconstructive_state_clones,
    reconstructive_partitions_materialized,
    partition_editions_acquired,
    adjacency_kind_slices_leased,
    adjacency_relation_ids_copied,
    ordinary_partitions_copied_on_write,
    ordinary_partition_slots_copied_on_write,
    partitions_cloned,
    entity_slots_cloned,
    relation_slots_cloned,
    aosoa_entity_chunks_staged,
    aosoa_entity_chunk_slots_materialized,
    aosoa_entity_chunks_published,
    aosoa_entity_slot_soa_merges,
    aosoa_prepare_soa_merge_count,
    aosoa_publish_soa_merge_count,
    partitions_touched_by_commit,
    entity_slots_touched_by_commit,
    relation_slots_touched_by_commit,
    bulk_entity_slots_reserved,
    bulk_relation_slots_reserved,
    relation_identity_candidates_scanned,
    visibility_entity_slot_scans,
    visibility_relation_slot_scans,
    visible_authoritative_entity_records_materialized,
    visible_authoritative_relation_records_materialized,
    query_packet_count,
    query_packet_item_count,
    query_packet_peak_width_total,
    query_scope_unit_count,
    query_parallel_legal_count,
    query_parallel_profitable_count,
    query_serial_strategy_count,
    query_staged_parallel_strategy_count,
    query_fragment_scratch_reuse_count,
    query_index_attempt_count,
    query_index_path_count,
    query_index_rejection_count,
    query_index_parity_verification_count,
    query_index_scratch_reuse_count,
    query_authoritative_entity_records_emitted,
    query_authoritative_relation_records_emitted,
    bulk_mutation_batch_count,
    bulk_mutation_entity_target_count,
    bulk_mutation_relation_target_count,
    bulk_mutation_cross_partition_relation_count,
    bulk_mutation_naming_normalization_count,
    bulk_mutation_lineage_transition_count,
    bulk_mutation_provenance_record_count,
    visibility_cache_hits,
    visibility_exact_state_materializations,
    visibility_cache_miss_reconstructions,
    visibility_cache_recent_evictions,
    visibility_cache_branch_head_promotions,
    visibility_cache_replay_promotions,
    visibility_cache_snapshot_promotions,
    invariant_entity_slot_scans,
    invariant_relation_slot_scans,
    invariant_authoritative_entity_records_materialized,
    invariant_authoritative_relation_records_materialized,
    custom_invariant_preparation_count,
    custom_invariant_execution_count,
    custom_invariant_panic_count,
    custom_invariant_traversal_frontier_count,
    custom_invariant_traversal_step_count,
    custom_invariant_candidate_entity_reads,
    custom_invariant_candidate_relation_reads,
    custom_invariant_candidate_adjacency_gathers,
    custom_invariant_candidate_adjacency_count_reads,
    custom_invariant_candidate_adjacency_relation_ids,
    custom_invariant_candidate_reuse_hits,
    custom_invariant_candidate_entity_aspect_reads,
    custom_invariant_candidate_relation_aspect_reads,
    relation_integrity_contracts_evaluated,
    relation_endpoint_kind_checks,
    relation_cardinality_checks,
    relation_uniqueness_checks,
    relation_uniqueness_candidates_scanned,
    relation_symmetry_checks,
    relation_endpoint_deletion_checks,
    preparation_packet_count,
    preparation_packet_item_count,
    preparation_packet_peak_width_total,
    preparation_scope_unit_count,
    preparation_parallel_legal_count,
    preparation_parallel_profitable_count,
    preparation_serial_strategy_count,
    preparation_staged_parallel_strategy_count,
    preparation_reducer_conflict_count,
    post_commit_consumer_packet_count,
    post_commit_consumer_item_count,
    post_commit_consumer_peak_width_total,
    post_commit_scope_unit_count,
    post_commit_serial_strategy_count,
    post_commit_parallel_strategy_count,
    snapshot_pin_adjustments,
    snapshot_pin_full_rebuilds,
    retention_entity_slots_scanned,
    retention_relation_slots_scanned,
    inspection_structural_identity_lookups,
    inspection_structural_identity_query_scans,
    inspection_graph_summary_requests,
    inspection_kind_summary_requests,
    inspection_connectivity_summary_requests,
    inspection_neighbor_requests,
    inspection_historical_view_opens,
    inspection_commit_reads,
    inspection_connectivity_entity_scans,
    inspection_connectivity_relation_scans,
    inspection_connectivity_frontier_expansions,
    inspection_connectivity_components_evaluated,
    inspection_budget_refusals,
    inspection_retention_entity_slot_scans,
    inspection_retention_relation_slot_scans,
    relation_cardinality_minimum_certification_contracts_evaluated,
    relation_cardinality_minimum_certification_entity_slot_scans,
    relation_cardinality_minimum_certification_relation_slot_scans,
    lineage_finalization_event_batch_width,
    lineage_finalization_decision_log_width,
    lineage_historical_resolution_requests,
    lineage_historical_resolution_event_visits,
    lineage_historical_resolution_traversed_events,
    lineage_historical_resolution_index_probes,
    lineage_historical_resolution_reachable_commit_node_visits,
    lineage_historical_resolution_reachable_commit_parent_edge_visits,
    lineage_historical_resolution_reachable_commit_catalog_probes,
    bridge_observation_commit_selections,
    bridge_observation_commit_ancestry_visits,
    lineage_branch_divergence_requests,
    lineage_branch_divergence_event_scans,
    lineage_graph_snapshot_requests,
    lineage_graph_snapshot_nodes_materialized,
    lineage_graph_snapshot_events_materialized,
    lineage_branch_divergence_node_scans,
    lineage_graph_snapshot_visibility_cache_hits,
    lineage_graph_snapshot_visibility_cache_miss_reconstructions,
    lineage_publication_event_width,
    lineage_publication_decision_width,
    schema_transition_atoms_inspected,
    schema_changed_subtrees_inspected,
    schema_unchanged_subtrees_reused_by_fingerprint,
    schema_bridge_descriptors_built,
    schema_normalized_descriptor_compositions,
    schema_transition_continue_unchanged_count,
    schema_transition_continue_transparent_bridge_count,
    schema_transition_continue_visible_bridge_count,
    schema_transition_continue_contract_upgrade_count,
    schema_transition_require_renegotiation_count,
    schema_transition_rejected_count,
    schema_historical_interpretation_sensitive_boundaries,
    schema_reconciliation_reject_lossy_narrowing_count,
    schema_reconciliation_preserve_information_count,
    schema_reconciliation_preserve_target_contract_count,
    schema_reconciliation_preserve_source_contract_count,
    schema_reconciliation_permit_lossy_narrowing_with_annotation_count,
    schema_reconciliation_require_explicit_projection_count,
    subscriber_resume_evaluations,
    subscriber_continue_unchanged_count,
    subscriber_continue_transparent_bridge_count,
    subscriber_continue_visible_bridge_count,
    subscriber_continue_contract_upgrade_count,
    subscriber_require_renegotiation_count,
    subscriber_rejected_count,
    replay_digest_parity_checks,
    replay_summary_parity_checks,
    replay_deep_artifact_parity_checks,
    replay_lineage_authority_lookup_requests,
    replay_lineage_log_index_hits,
    replay_lineage_checkpoint_index_hits,
    replay_lineage_durable_basis_selections,
    replay_lineage_retained_envelope_basis_selections,
    replay_lineage_authoritative_basis_rejections,
    replay_lineage_digest_event_width,
    replay_lineage_digest_decision_width,
    merge_history_ancestry_traversals,
    merge_history_ancestry_nodes_visited,
    merge_history_parent_comparisons,
    merge_history_replay_parent_checks,
    merge_history_replay_planning_nodes_visited,
    merge_history_durability_parent_checks,
    merge_history_durability_validation_nodes_visited,
    merge_planning_requests,
    merge_planning_schema_kinds_snapshotted,
    merge_planning_target_commits_scoped,
    merge_planning_source_commits_scoped,
    merge_planning_target_records_scoped,
    merge_planning_source_records_scoped,
    merge_identity_candidates_discovered,
    merge_identity_effective_declarations,
    merge_identity_target_records_scanned,
    merge_identity_target_records_indexed,
    merge_conflict_records_classified,
    merge_topology_relation_candidates_scoped,
    merge_topology_endpoint_incidences_scoped,
    merge_topology_region_conflicts_detected,
    merge_topology_region_records_escalated,
    merge_causal_records_annotated,
    merge_policy_records_resolved,
    merge_policy_value_source_state_hits,
    merge_policy_value_target_state_hits,
    merge_policy_value_base_state_hits,
    merge_policy_value_base_patch_authority_hits,
    merge_policy_value_missing_ancestor_basis,
    merge_policy_value_missing_visible_state,
    merge_policy_value_invalid_shape,
    merge_lowered_records_emitted,
    merge_decision_log_width,
    merge_planning_elapsed_nanos,
    merge_execution_verification_requests,
    merge_execution_branch_head_checks,
    merge_execution_merge_base_checks,
    merge_execution_schema_kinds_snapshotted,
    merge_execution_compiled_plan_digest_checks,
    merge_execution_attempts,
    merge_execution_requests,
    merge_execution_records_admitted,
    merge_execution_mutation_intents_emitted,
    descriptor_version_mismatches_encountered,
    live_entity_history_entries_trimmed,
    live_relation_history_entries_trimmed,
    forward_adjacency_updates,
    reverse_adjacency_updates,
);
