mod inspection;
mod mounted_frame;
mod mounted_projection;
mod mounted_target_coherence;
mod observation_report;
mod operational_adapter;
mod qualified_text;
mod runtime;
mod visual_snapshot;

pub use inspection::WorthUiInspectionHostContract;
pub use mounted_frame::{
    UiHostMeasurementSchemaVersion, UiHostObservationSchemaVersion,
    UiHostPresentationCompletionToken, UiHostPresentationCostInput, UiHostPresentationCostOverflow,
    UiHostPresentationCostReport, UiHostPresentationLineageIdentity,
    UiHostPresentationProgressClass, UiHostProtocolAgreement, UiHostProtocolContract,
    UiHostProtocolDenial, UiHostProtocolIdentity, UiHostProtocolNegotiation,
    UiHostProtocolSchemaFamily, UiHostProtocolVersion, UiHostSolicitedEffectSchemaVersion,
    UiHostSurfaceBaselineIdentity, UiHostSurfaceCancellationOutcome,
    UiHostSurfaceDeregistrationIndeterminate, UiHostSurfaceDeregistrationOutcome,
    UiHostSurfaceDeregistrationReceipt, UiHostSurfaceIdentity, UiHostSurfaceInFlightCompletion,
    UiHostSurfacePresentationDenial, UiHostSurfacePresentationMode,
    UiHostSurfacePresentationOutcome, UiHostSurfaceRegistrationDenial,
    UiHostSurfaceRegistrationIndeterminate, UiHostSurfaceRegistrationInput,
    UiHostSurfaceRegistrationOutcome, UiHostSurfaceRegistrationRequest, UiHostSurfaceStopReason,
    UiMountIncarnation, UiMountedCompletedEffects, UiMountedContentGeneration,
    UiMountedContractIdentityExhaustion, UiMountedEffectFamily, UiMountedFrameCanonicalCore,
    UiMountedFrameConsumptionInput, UiMountedFrameConsumptionView, UiMountedFrameIdentity,
    UiMountedFrameIntegrity, UiMountedFrameManifest, UiMountedFrameSchemaVersion,
    UiMountedInstanceIdentity, UiMountedLaneParticipation, UiMountedLogicalDamage,
    UiMountedNodeReceiptAffinity, UiMountedNodeReceiptIdentity, UiMountedNodeReceiptIssuer,
    UiMountedPaintCommand, UiMountedPaintCommandChange, UiMountedPaintCommandIdentity,
    UiMountedPaintOrderEdit, UiMountedPaintOrderIdentity, UiMountedPaintOrderIntegrity,
    UiMountedPresentationAffinity, UiMountedPresentationAttemptIdentity,
    UiMountedPresentationAuxiliaryState, UiMountedPresentationDelta,
    UiMountedPresentationDeltaInput, UiMountedPresentationInitial,
    UiMountedPresentationInitialInput, UiMountedPresentationNodeChange,
    UiMountedPresentationNodeHitTest, UiMountedPresentationNodePaint,
    UiMountedPresentationNodeState, UiMountedPresentationNodeStateInput,
    UiMountedPresentationOpacity, UiMountedPresentationProductionCost,
    UiMountedPresentationProductionCostInput, UiMountedPresentationReconstruction,
    UiMountedPresentationReconstructionDenial, UiMountedPresentationReconstructionInput,
    UiMountedPresentationSample, UiMountedPresentationSampleChange,
    UiMountedPresentationSampleConstructionDenial, UiMountedPresentationSampleInput,
    UiMountedPresentationSchemaVersion, UiMountedPresentationTransform,
    UiMountedPresentationUnchanged, UiMountedPresentationUnchangedInput,
    UiMountedPresentationWorkView, UiMountedSurfaceBindingRequirement,
    UiMountedSurfacePresentationCompletion, UiMountedSurfacePresentationSupersession,
    UiMountedTextRasterCallback, UiMountedTextRasterWork, UiPresentationDeadline,
    UiRequiredLaneContribution, UiRequiredLaneContributionStatus, UiSemanticSurfaceIdentity,
    UiSurfaceBindingGeneration,
};
pub use mounted_projection::{
    compose_source_over, UiAppearanceAllocationBounds, UiAppearanceBackdropExtent,
    UiAppearanceClip, UiAppearanceDamageAttribution, UiAppearanceDamageRegion,
    UiAppearanceEmptyRegion, UiAppearanceGeometryOverflow, UiAppearanceLogicalLength,
    UiAppearanceNegativeLength, UiAppearanceNormalizedLogicalRadii, UiAppearanceOutlineGeometry,
    UiAppearanceOutlineGeometryDenial, UiAppearanceVisualBounds,
    UiHeadlessMountedParticipationRecord, UiHeadlessMountedResourceHandle,
    UiHostAppearanceMechanicFamily, UiHostAppearanceProfileContract, UiHostAppearanceProfileDenial,
    UiHostPrimaryPointerKind, UiMountedAccessibilityProjection, UiMountedAllocationBasis,
    UiMountedAllocationProjection, UiMountedAppearanceColor, UiMountedAppearanceFrame,
    UiMountedAppearanceFrameDenial, UiMountedAppearanceMechanic, UiMountedAppearanceMechanicChange,
    UiMountedAppearanceMechanicIdentity, UiMountedAppearanceOpacity,
    UiMountedAppearancePredecessorManifest, UiMountedAppearanceWork,
    UiMountedAppearanceWorkPosture, UiMountedBackdropAppearanceAttribution,
    UiMountedBackdropCompletionDenial, UiMountedBackdropCompletionInput, UiMountedBackdropIdentity,
    UiMountedBackdropMechanic, UiMountedBackdropScope, UiMountedCanonicalBox,
    UiMountedCanonicalBoxInput, UiMountedClientCoordinateBasis, UiMountedClientPhysicalRect,
    UiMountedClipProjection, UiMountedClipReference, UiMountedClipRow, UiMountedClipTable,
    UiMountedCollectionRowCorrelation, UiMountedCoordinateSpace, UiMountedDiagnosticProjection,
    UiMountedDiagnosticReference, UiMountedDrawableReference, UiMountedFilledRectCompletionDenial,
    UiMountedFilledRectCompletionInput, UiMountedFilledRectMechanic, UiMountedFilledRectReference,
    UiMountedFilledRectTable, UiMountedFilledRectTableDenial, UiMountedGeometryDenial,
    UiMountedGeometryPosture, UiMountedHitTestCompletionDenial, UiMountedHitTestCompletionInput,
    UiMountedHitTestMechanic, UiMountedHitTestOrder, UiMountedHitTestProjection,
    UiMountedHitTestReference, UiMountedHitTestTable, UiMountedIdentityOverlayMechanic,
    UiMountedIdentityOverlayMechanicInput, UiMountedLayerProjection, UiMountedLayerReference,
    UiMountedLayerRow, UiMountedLayerTable, UiMountedMechanicalRole, UiMountedMotionProjection,
    UiMountedNodeAppearanceAttribution, UiMountedNodeProjectionView,
    UiMountedNodeProjectionViewInput, UiMountedOmissionReason,
    UiMountedOutlineAppearanceCompletionDenial, UiMountedOutlineAppearanceCompletionInput,
    UiMountedOutlineAppearanceMechanic, UiMountedOverlayOrderMechanic,
    UiMountedOverlayOrderMechanicDenial, UiMountedPaintBatchReference, UiMountedPaintBatchRow,
    UiMountedPaintBatchTable, UiMountedPaintPrimitiveKind, UiMountedPaintProjection,
    UiMountedParticipation, UiMountedParticipationFact, UiMountedParticipationInput,
    UiMountedParticipationStatus, UiMountedPointerAffordanceMechanic,
    UiMountedPortalInputShielding, UiMountedPortalOverlayCompletionDenial,
    UiMountedPortalOverlayCompletionInput, UiMountedPortalOverlayLifecyclePosture,
    UiMountedPortalOverlayMechanic, UiMountedPortalOverlayReference,
    UiMountedPortalOverlaySchemaVersion, UiMountedPortalOverlayTable,
    UiMountedPortalPresentationAffinity, UiMountedPortalSurfaceAppearanceCompletionDenial,
    UiMountedPortalSurfaceAppearanceMechanic, UiMountedPreviewProjection,
    UiMountedProjectionAudience, UiMountedProjectionView, UiMountedProjectionViewInput,
    UiMountedQualifiedTextResolver, UiMountedRealtimeBatchReference, UiMountedRealtimeBatchRow,
    UiMountedRealtimeBatchTable, UiMountedResourceEntry, UiMountedResourceKind,
    UiMountedResourceReference, UiMountedResourceTable, UiMountedRgba8,
    UiMountedSemanticTextCompletionDenial, UiMountedSemanticTextCompletionInput,
    UiMountedSemanticTextMechanic, UiMountedSemanticTextReference, UiMountedSemanticTextTable,
    UiMountedSemanticTextTableDenial, UiMountedSpatialBatchReference, UiMountedSpatialBatchRow,
    UiMountedSpatialBatchTable, UiMountedStaticPaintSchemaVersion,
    UiMountedSurfaceAppearanceCompletionDenial, UiMountedSurfaceAppearanceCompletionInput,
    UiMountedSurfaceAppearanceMechanic, UiMountedSurfacePaint, UiMountedTableProjectionStatus,
    UiMountedTextForegroundAppearanceCompletionDenial,
    UiMountedTextForegroundAppearanceCompletionInput, UiMountedTextForegroundAppearanceMechanic,
    UiMountedTextForegroundSpan, UiMountedTextPaintSpanIdentity, UiMountedTextSchemaVersion,
    UiMountedTransformProjection, UiOverlayParticipantIdentity, UiOverlayPlacementReceipt,
    UiPointerAffordanceFamily, UiSemanticTextBaselinePosture, UiSemanticTextProfile,
    UiSemanticTextSlot, UiSemanticTextWrapPosture, WorthUiHeadlessMountedProjectionRecord,
    WorthUiHeadlessMountedResourceCache, WorthUiMountedResourceCacheDenial, SRGB_GAMMA_DENOMINATOR,
    SRGB_GAMMA_NUMERATOR, SRGB_LINEAR_SCALE_DENOMINATOR, SRGB_LINEAR_SCALE_NUMERATOR,
    SRGB_LINEAR_THRESHOLD_DENOMINATOR, SRGB_LINEAR_THRESHOLD_NUMERATOR, SRGB_OFFSET_DENOMINATOR,
    SRGB_OFFSET_NUMERATOR, SRGB_SCALE_DENOMINATOR, SRGB_SCALE_NUMERATOR,
    UI_APPEARANCE_LOGICAL_SUBPIXELS_PER_POINT,
};
pub use observation_report::{
    UiHostApplicationGeneration, UiHostImeCompositionPhase, UiHostImePreedit,
    UiHostImePreeditConstructionDenial, UiHostImePreeditSelection, UiHostImeRangeConversionReceipt,
    UiHostInputDraftSessionIdentity, UiHostInputRecipientAffinityReceipt,
    UiHostInputRecipientBindingInput, UiHostInputRecipientBindingReceipt,
    UiHostInputRecipientFamily, UiHostInputRecipientGeneration, UiHostKey, UiHostKeyTransition,
    UiHostKeyboardModifiers, UiHostObservationBatch, UiHostObservationBatchConstructionDenial,
    UiHostObservationBatchInput, UiHostObservationCanonicalCore,
    UiHostObservationCanonicalCoreInput, UiHostObservationCoalescingIdentity,
    UiHostObservationDrain, UiHostObservationDrainDenial, UiHostObservationFamily,
    UiHostObservationIntegrity, UiHostObservationLoss, UiHostObservationMountedBasis,
    UiHostObservationPayload, UiHostObservationPointerDeviceKindDenial,
    UiHostObservationPresentationBasis, UiHostObservationReport, UiHostObservationRetention,
    UiHostObservationRetentionDenial, UiHostObservationSequence, UiHostObservationSequenceRange,
    UiHostObservationSessionRegistrationDenial, UiHostObservationTimeBasis, UiHostPointerButton,
    UiHostPointerButtonTransition, UiHostPointerCaptureEpoch, UiHostPointerDeviceKind,
    UiHostPointerIdentity, UiHostPressedPointerButtons, UiHostScrollDeltaPhase,
    UiHostScrollDeltaPrecision, UiHostScrollDeltaSource, UiHostScrollDeltaTargetAffinity,
    UiHostSurfaceCoordinateSpace, UiHostSurfaceCoordinateUnit, UiHostSurfacePosition,
    UiHostSurfacePositionBasis, UiHostUnicodeScalarRange, UiHostUtf8ByteRange,
    UI_HOST_OBSERVATION_ACTIVE_SESSION_LIMIT, UI_HOST_OBSERVATION_BATCH_BYTE_LIMIT,
    UI_HOST_OBSERVATION_BATCH_REPORT_LIMIT, UI_HOST_OBSERVATION_DRAIN_BATCH_LIMIT,
    UI_HOST_OBSERVATION_DRAIN_BYTE_LIMIT, UI_HOST_OBSERVATION_DRAIN_REPORT_LIMIT,
    UI_HOST_SURFACE_POSITION_SUBPIXELS_PER_UNIT,
};
pub use operational_adapter::{
    UiHostSessionReleaseIndeterminate, UiHostSessionReleaseOutcome, UiHostSessionReleaseReceipt,
    WorthUiHostMechanicsAdapter,
};
pub use qualified_text::{
    UiAlphaRasterBatchView, UiAlphaRasterRecordView, UiColorRasterBatchView,
    UiColorRasterRecordView, UiFontCollectionGeneration, UiFontCollectionLineageIdentity,
    UiFontSlant, UiGlyphRasterAttribution, UiGlyphRasterBatchIdentity, UiGlyphRasterBatchSink,
    UiGlyphRasterBatchSubmissionDenial, UiGlyphRasterBearing, UiGlyphRasterCallbackDenial,
    UiGlyphRasterContentDigest, UiGlyphRasterDemandBatchView, UiGlyphRasterDemandBatchViewInput,
    UiGlyphRasterDemandIdentity, UiGlyphRasterDemandRecord, UiGlyphRasterEffectsIndeterminate,
    UiGlyphRasterExtent, UiGlyphRasterFractionalOrigin, UiGlyphRasterKey, UiGlyphRasterKeyInput,
    UiGlyphRasterLane, UiGlyphRasterMissRasterizer, UiGlyphRasterMissSelectionView,
    UiGlyphRasterPalette, UiGlyphRasterPinRequest, UiGlyphRasterPinTransitionView,
    UiGlyphRasterRecordViewInput, UiGlyphRasterSize, UiGlyphRasterSource,
    UiGlyphRasterTransactionDenial, UiGlyphRasterTransactionOutcome,
    UiGlyphRasterTransactionPending, UiGlyphRasterTransactionReceipt, UiGlyphRasterViewDenial,
    UiGlyphRunView, UiGlyphRunViewInput, UiGlyphVariationCoordinates,
    UiMountedTextPinReleaseRequest, UiPositionedTextGlyphInput, UiPositionedTextGlyphRecord,
    UiQualifiedFontFaceIdentity, UiQualifiedFontFamilyIdentity, UiQualifiedFontPackIdentity,
    UiQualifiedTextCaretRecord, UiQualifiedTextCostInput, UiQualifiedTextCostRecord,
    UiQualifiedTextCoverageRecord, UiQualifiedTextFeatureRecord, UiQualifiedTextGlyphInput,
    UiQualifiedTextGlyphRecord, UiQualifiedTextGraphemeRecord, UiQualifiedTextLayoutIdentity,
    UiQualifiedTextLayoutRequestIdentity, UiQualifiedTextLayoutView,
    UiQualifiedTextLayoutViewInput, UiQualifiedTextLayoutWidthBasis, UiQualifiedTextLineInput,
    UiQualifiedTextLineRecord, UiQualifiedTextRunInput, UiQualifiedTextRunRecord,
    UiQualifiedTextSelectionRect, UiQualifiedTextStyleInput, UiQualifiedTextStyleRecord,
    UiQualifiedTextVariationRecord, UiQualifiedTextVisualRunInput, UiQualifiedTextVisualRunRecord,
    UiQualifiedTextWordBoundaryRecord, UiTextCaretAffinity, UiTextCaretPosition,
    UiTextCoverageDisposition, UiTextDirection, UiTextFontUnitRect, UiTextHitResult,
    UiTextOriginalRange, UiTextPoint, UiTextProfileGeneration, UiTextRect, UiTextScaleGeneration,
    UiTextVisualEdge,
};
pub use runtime::{
    UiDpiScaleFactorObservation, UiDpiScaleFactorRequest, UiFontMeasurementKey,
    UiFontMetricsObservation, UiFontMetricsRequest, UiForbiddenHostAuthorityAsk,
    UiHostFocusPlacementAcknowledgement, UiHostFocusPlacementDisposition,
    UiHostFocusPlacementObservation, UiHostFocusPlacementObservationDenial,
    UiHostFocusPlacementObservationInput, UiHostFocusPlacementRejection,
    UiHostFocusPlacementRequest, UiHostFocusPlacementRequestDenial,
    UiHostFocusPlacementRequestIdentity, UiHostFocusPlacementRequestInput,
    UiHostFocusPlacementTarget, UiHostMeasurementAssumptionProfile, UiHostMeasurementDeadline,
    UiHostMeasurementEnvironmentReport, UiHostMeasurementNormalizationContext,
    UiHostMeasurementObservation, UiHostMeasurementObservationContractDenial,
    UiHostMeasurementObservationValue, UiHostMeasurementRequest, UiHostMeasurementRequestIntent,
    UiHostPhysicalPixelGeometry, UiHostPhysicalPixelGeometryInput, UiHostServiceGeometryDenial,
    UiHostSolicitedEffectCancellationOutcome, UiHostSolicitedEffectOutcome,
    UiHostSurfaceLogicalGeometry, UiMeasurementCapabilityGrant, UiMeasurementCapabilityPosture,
    UiMeasurementCoordinateSpace, UiMeasurementEvidenceCategory, UiMeasurementEvidenceFamily,
    UiMeasurementRequestDenial, UiMeasurementRequestFamily, UiMeasurementRequestIdentity,
    UiMeasurementRoundingPosture, UiMeasurementUnitPosture,
    UiNativeControlIntrinsicSizeObservation, UiNativeControlIntrinsicSizeRequest,
    UiNativeControlKind, UiPortalAnchorRectObservation, UiPortalAnchorRectRequest,
    UiPortalAnchorTargetIdentity, UiScrollContainerViewportObservation,
    UiScrollContainerViewportRequest, UiTextBaselineMetricsObservation,
    UiTextBaselineMetricsRequest, UiTextIntrinsicSizeObservation, UiTextIntrinsicSizeRequest,
    UiViewportExtentObservation, UiViewportExtentRequest, WorthUiHostCapability,
    WorthUiHostCapabilityObservationGeneration, WorthUiHostCapabilityPosture,
    WorthUiHostCapabilityReport, WorthUiHostContract, WorthUiHostKind,
    WorthUiMeasurementHostAdapter,
};
pub use visual_snapshot::{
    UiHostCaptureAffinity, UiHostCaptureArtifactBudget, UiHostCaptureCancellationOutcome,
    UiHostCaptureCapability, UiHostCaptureFrameAffinity, UiHostCaptureObservation,
    UiHostCaptureObservationOutcome, UiHostCaptureRequestIdentity, UiHostCaptureSurfaceAffinity,
    UiHostClientAreaObservation, UiHostCoordinateOrientation, UiHostCoordinatePosture,
    UiHostCoordinateRounding, UiHostCoordinateTransform, UiHostPixelArtifact,
    UiHostPixelColorSpace, UiHostPresentationEpoch, UiHostRealizedGeometry, UiHostRealizedOrdering,
    UiHostRealizedRegion, UiHostRealizedRegionParticipation, UiHostViewportTransformObservation,
    UiHostVisualCaptureRequest,
};
