//! Stable product-facing intent definition contracts.

pub use worth_ui_query_binding::WorthUiCollectionChangeConsequence;

pub use crate::capability::{
    FrozenIntentDefinitionCapabilities, IntentDefinitionDescriptor, UiApplicationEffectDestination,
    UiIntent, UiIntentAcceptedInteractions, UiIntentBoolean, UiIntentDefinition,
    UiIntentDefinitionDestination, UiIntentDefinitionRegistrationError,
    UiIntentExecutionDestination, UiIntentId, UiIntentPayload, UiIntentPayloadField,
    UiIntentPayloadFieldDescriptor, UiIntentPayloadFieldKind, UiIntentPayloadFieldSet,
    UiIntentPayloadProjection, UiIntentPayloadProjectionViolation, UiIntentPayloadSchemaViolation,
    UiIntentPayloadValueKind, UiIntentProductConsequenceFamilies, UiIntentProductConsequences,
    UiIntentProductOutcome, UiIntentRuntimeServiceDestination, UiIntentSchema, UiIntentSelection,
    UiIntentSelectionValue, UiIntentText, UiIntentTransitionDestination, UiIntentTransitionOutcome,
    UiIntentUnsigned64, UiRuntimeServiceDefinitionDestination, UiSemanticInteractionFamily,
    UiTransitionDefinitionDestination, UI_INTENT_PAYLOAD_FIELD_LIMIT,
    UI_INTENT_PAYLOAD_TEXT_BYTE_LIMIT,
};
pub use crate::declaration::{
    UiIntentApplicationFact, UiIntentApplicationFactIdentityError,
    UiIntentApplicationFactRegistrationError, UiIntentCatalogMetrics,
    UiIntentCatalogPreparationDenial, UiIntentConcurrencyScope, UiIntentConfirmationContract,
    UiIntentConfirmationContractIdentityError, UiIntentConfirmationRouteBinding,
    UiIntentConsequenceContract, UiIntentDeclaration, UiIntentDeclarationConcurrencyBound,
    UiIntentDeclarationConcurrencyMissing, UiIntentDeclarationConfirmationBound,
    UiIntentDeclarationConfirmationMissing, UiIntentDeclarationConsequencesBound,
    UiIntentDeclarationConsequencesMissing, UiIntentDeclarationConstructionError,
    UiIntentDeclarationIdentity, UiIntentDeclarationOperabilityBound,
    UiIntentDeclarationOperabilityMissing, UiIntentInteractionPayloadSourceKind,
    UiIntentMutabilitySource, UiIntentOperabilityContract,
    UiIntentOperabilityContractIdentityError, UiIntentOperabilityDependencyAxis,
    UiIntentPayloadSource, UiIntentPolicySource, UiIntentReadinessSource, UiIntentRouteBinding,
};
pub use crate::facade::entry::{
    UiIntentConsequencePublicationCompletion, UiIntentConsequencePublicationOutcome,
    UiIntentConsequencePublicationReceipt, UiIntentConsequencePublicationRecovery,
};
pub use crate::runtime::intent::{
    UiAdmittedIntent, UiConfirmedIntentCandidate, UiInoperableIntentCandidate,
    UiIntentAdmissionCancellationReason, UiIntentAdmissionCost, UiIntentAdmissionDecision,
    UiIntentAdmissionMetrics, UiIntentAdmissionSettlementPosture,
    UiIntentAdmissionSettlementReceipt, UiIntentAdmissionShutdownReport,
    UiIntentAdmissionSlotIdentity, UiIntentAdmissionStop, UiIntentAdmissionStopReason,
    UiIntentAffinityPosture, UiIntentApplicationFactRevision, UiIntentApplicationFactUpdateDenial,
    UiIntentApplicationFactUpdateReceipt, UiIntentAttemptLineage,
    UiIntentConfirmationCancellationReason, UiIntentConfirmationChallenge,
    UiIntentConfirmationContinuation, UiIntentConfirmationIssueOutcome,
    UiIntentConfirmationLookupCost, UiIntentConfirmationMetrics, UiIntentConfirmationObservation,
    UiIntentConfirmationPosture, UiIntentConfirmationSettlementReceipt,
    UiIntentConfirmationShutdownReport, UiIntentConfirmationSlotIdentity, UiIntentConfirmationStop,
    UiIntentConfirmationStopReason, UiIntentConfirmationTimeBasisKind, UiIntentDraftInputRevision,
    UiIntentInoperableCause, UiIntentInoperableCauseIter, UiIntentInputBasisReceipt,
    UiIntentInputOwnerRevision, UiIntentMutabilityPosture, UiIntentOccupancyPosture,
    UiIntentOperabilityCost, UiIntentOperabilityDecision, UiIntentOperabilityOutcome,
    UiIntentOperabilityProof, UiIntentPayloadProjectionCost, UiIntentPayloadStop,
    UiIntentPolicyPosture, UiIntentQueryInputRevision, UiIntentReadinessPosture,
    UiIntentRouteResolution, UiIntentRouteResolutionCost, UiIntentRouteResolutionStop,
    UiIntentSupportPosture, UiPendingIntentConfirmation, UiPreparedIntentPayload,
    UiResolvedConfirmationIntentRoute, UiResolvedProductIntentRoute, UI_INTENT_ADMISSION_CAPACITY,
    UI_INTENT_CONFIRMATION_TTL_MILLIS, UI_PENDING_INTENT_CONFIRMATION_LIMIT,
};
pub use crate::runtime::intent_execution::{
    UiIntentConsequenceCompletionReceipt, UiIntentConsequenceHandle, UiIntentConsequenceRecovery,
    UiIntentConsequenceStop, UiIntentConsequenceStopReason, UiIntentExecutionAdvanceOutcome,
    UiIntentExecutionAdvanceReport, UiIntentExecutionAdvanceStop, UiIntentExecutionAttempt,
    UiIntentExecutionAttemptIdentity, UiIntentExecutionBindingPreparationDenial,
    UiIntentExecutionCancellationContext, UiIntentExecutionCancellationReason,
    UiIntentExecutionClockReading, UiIntentExecutionCurrentnessStop, UiIntentExecutionDeadline,
    UiIntentExecutionDeadlineBasis, UiIntentExecutionDeadlineOverflow,
    UiIntentExecutionDispatchOutcome, UiIntentExecutionDispatchReceipt,
    UiIntentExecutionDispatchStop, UiIntentExecutionDispatchStopReason,
    UiIntentExecutionIdempotencyIdentity, UiIntentExecutionPollContext, UiIntentExecutionProvider,
    UiIntentExecutionRecovery, UiIntentExecutionRequest, UiIntentExecutionReservationDenial,
    UiIntentExecutionShutdownReport, UiIntentExecutionTransition,
    UiIntentExecutionTransitionPosture, UiIntentPartialEffect, UiIntentPortalPlacementStopReason,
    UiIntentProviderPoll, UiIntentProviderRecoveryPoll, UiIntentProviderSettlement,
    UiIntentProviderStart, UiIntentProviderStop, UiIntentProviderVersion, UiIntentRecoveryHandle,
    UiIntentRecoveryProgressOutcome, UiIntentRecoveryProgressPosture,
    UiIntentRecoveryProgressReceipt, UiIntentRecoveryProgressStop,
    UiRuntimeServiceFamilyStopReason, UiRuntimeServiceProposalStop,
    UiRuntimeServiceProposalStopReason, UI_INTENT_MAXIMUM_APPLICATION_ATTEMPTS,
    UI_INTENT_MAXIMUM_DESTINATION_ATTEMPTS, UI_INTENT_MAXIMUM_INTENT_ATTEMPTS,
    UI_INTENT_MAXIMUM_PROVIDER_ATTEMPTS, UI_INTENT_MAXIMUM_RETAINED_PAYLOAD_BYTES,
};
pub use crate::runtime::interaction::UiIntentRouteSource;
pub use crate::runtime::session::UiIntentResourceCensus;
