//! Mounted identity and surface-binding observations.

pub use crate::inspection::mounted_frame::{
    UiMountedDiagnosticInspection, UiMountedDiagnosticInspectionOmission,
    UiMountedInspectedDiagnostics, UiMountedInspectedFrame, UiMountedInspectionOmission,
    UiMountedInspectionReceipt, UiMountedInspectionRelation, UiMountedInspectionRequest,
    UiMountedInspectionTarget, UiMountedRetentionClassReport, UiMountedRetentionEvictionPosture,
    UiMountedRetentionQueueBudget, UiMountedRetentionReport, UiMountedVisualTargetDenial,
};
pub use crate::mounting::{
    UiHitTestSpatialWork, UiHostPresentationReconciliation, UiHostSurfaceBaselineIdentity,
    UiHostSurfaceIdentity, UiHostSurfacePresentationMode, UiMountCostReport, UiMountIncarnation,
    UiMountNamedCounters, UiMountWorkClass, UiMountedAppearanceSelectionCostReport,
    UiMountedFrameDelta, UiMountedFrameExecutionPosture, UiMountedFrameIdentity,
    UiMountedFrameIdentityView, UiMountedFrameOutcome, UiMountedFramePreparationDenial,
    UiMountedFramePublicationReceipt, UiMountedFrameReceipt, UiMountedFrameRequest,
    UiMountedFrameRetentionBudget, UiMountedFrameRetentionBudgetInput,
    UiMountedFrameRetentionDenial, UiMountedFrameRetentionRejection, UiMountedFrameReuse,
    UiMountedFrameReuseComparator, UiMountedFrameReuseContract, UiMountedFrameReuseDependency,
    UiMountedFrameReuseMintingStage, UiMountedFrameReuseWitness, UiMountedGraphNodeHandle,
    UiMountedGraphWorldIdentity, UiMountedIdentityBasis, UiMountedIdentityDenial,
    UiMountedIdentityView, UiMountedIndeterminateFrame, UiMountedInstanceIdentity,
    UiMountedInstanceIdentityView, UiMountedLayoutBasis, UiMountedLayoutCompletionReceipt,
    UiMountedLayoutRevision, UiMountedMosaicRegionGeometry, UiMountedNodeReceipt,
    UiMountedNodeReceiptIdentity, UiMountedOccurrenceGeometry, UiMountedOccurrenceGeometryDenial,
    UiMountedOccurrencePlacement, UiMountedPointerAffordanceWork, UiMountedPresentationAdmission,
    UiMountedPresentationAdmissionDenial, UiMountedPresentationAdmissionRejection,
    UiMountedPresentationAttempt, UiMountedPresentationCompletionDenial,
    UiMountedPresentationInFlight, UiMountedPresentationOutcome, UiMountedPresentationReceipt,
    UiMountedPresentationShutdownAttempt, UiMountedPresentationShutdownDisposition,
    UiMountedPresentationShutdownReport, UiMountedPresentationWitness, UiMountedPresentedFrame,
    UiMountedProjectionAudience, UiMountedProjectionDenial, UiMountedProjectionFrame,
    UiMountedPublicationLeaseDenial, UiMountedRejectedFrame, UiMountedRetentionClass,
    UiMountedRetentionClassBudget, UiMountedRetentionLease, UiMountedSpatialWork,
    UiMountedSupersededFrame, UiMountedSurfaceGeometryBatch, UiMountedSurfacePresentationReceipt,
    UiMountedSurfacePresentationRejection, UiMountedSurfaceReceipt,
    UiMountedSurfaceReconciliationBinding, UiPreparedMountedFrame,
    UiPresentationIndeterminateReport, UiPresentationMotionSamplingCost,
    UiProjectedMountedFrameCandidate, UiSemanticSurfaceIdentity, UiSurfaceBindingCoordinatePosture,
    UiSurfaceBindingGeneration, UiSurfaceBindingIdentityView, UiSurfaceBindingProfile,
};
pub use worth_ui_host_contract::{
    UiHeadlessMountedResourceHandle, UiHostPresentationCompletionToken,
    UiHostPresentationCostInput, UiHostPresentationCostOverflow, UiHostPresentationCostReport,
    UiHostSurfaceCancellationOutcome, UiHostSurfaceInFlightCompletion,
    UiHostSurfacePresentationDenial, UiHostSurfacePresentationOutcome,
    UiMountedAccessibilityProjection, UiMountedAllocationBasis, UiMountedAllocationProjection,
    UiMountedCanonicalBox, UiMountedCanonicalBoxInput, UiMountedClipProjection,
    UiMountedClipReference, UiMountedClipRow, UiMountedClipTable, UiMountedCompletedEffects,
    UiMountedCoordinateSpace, UiMountedDiagnosticProjection, UiMountedDiagnosticReference,
    UiMountedEffectFamily, UiMountedFrameCanonicalCore, UiMountedFrameIntegrity,
    UiMountedFrameManifest, UiMountedGeometryDenial, UiMountedGeometryPosture,
    UiMountedHitTestCompletionDenial, UiMountedHitTestMechanic, UiMountedHitTestOrder,
    UiMountedHitTestProjection, UiMountedHitTestReference, UiMountedHitTestTable,
    UiMountedLaneParticipation, UiMountedLayerProjection, UiMountedLayerReference,
    UiMountedLayerRow, UiMountedLayerTable, UiMountedMotionProjection, UiMountedNodeProjectionView,
    UiMountedOmissionReason, UiMountedPaintBatchReference, UiMountedPaintBatchRow,
    UiMountedPaintBatchTable, UiMountedPaintPrimitiveKind, UiMountedPaintProjection,
    UiMountedParticipation, UiMountedParticipationFact, UiMountedParticipationStatus,
    UiMountedPresentationAttemptIdentity, UiMountedPreviewProjection, UiMountedProjectionView,
    UiMountedRealtimeBatchReference, UiMountedRealtimeBatchRow, UiMountedRealtimeBatchTable,
    UiMountedResourceEntry, UiMountedResourceKind, UiMountedResourceReference,
    UiMountedResourceTable, UiMountedRgba8, UiMountedSpatialBatchReference,
    UiMountedSpatialBatchRow, UiMountedSpatialBatchTable, UiMountedSurfaceBindingRequirement,
    UiMountedSurfacePresentationCompletion, UiMountedTableProjectionStatus,
    UiMountedTransformProjection, UiPresentationDeadline, UiRequiredLaneContribution,
    UiRequiredLaneContributionStatus, WorthUiHeadlessMountedResourceCache,
    WorthUiMountedResourceCacheDenial,
};
