mod diagnostics_views;
mod invalidation;

pub use crate::data::aspect::{
    apply_installed_scoped_changes, Aspect, AspectMask, AspectVersion,
    InstalledSignalAspectCapability, InstalledSignalAspectLoweringAuthority,
    InstalledSignalAspectSetCapability, InstalledSignalGraphCapability,
    InstalledSignalNodeCapability, InstalledSignalScopedChange, InstalledSignalScopedChangeSet,
    InstalledSignalScopedChangeView, SignalAspectCapabilityDenial, SignalAspectLoweringOwner,
    SignalAspectLoweringOwnershipDenial, SignalInstalledScopedChangeDenial,
    SignalInstalledScopedChangeOutcome, MAX_ASPECTS,
};
pub use crate::data::async_node::{
    async_node_compile_time_boundary_proof, async_node_milestone_d_certification_run,
    async_node_milestone_d_performance_closeout, async_node_milestone_d_scenario_matrix,
    AsyncCapableNode, AsyncKeyedNodeCapabilityBinding,
    AsyncKeyedNodeCapabilityEquivalenceDenialClass, AsyncKeyedNodeCapabilityEquivalenceReport,
    AsyncKeyedNodeHistoricalParityDenialClass, AsyncKeyedNodeHistoricalParityReport,
    AsyncNodeAdmissionClass, AsyncNodeAdmissionClassification,
    AsyncNodeCapabilityAliasLoweringProof, AsyncNodeCapabilityDeclaration,
    AsyncNodeCapabilityEquivalenceDenialClass, AsyncNodeCapabilityEquivalenceReport,
    AsyncNodeCompileTimeBoundaryProof, AsyncNodeConditionBlockClass,
    AsyncNodeDownstreamDependenceFact, AsyncNodeGateStateReport,
    AsyncNodeHierarchyCancellationReport, AsyncNodeHierarchyHistoricalParityDenialClass,
    AsyncNodeHierarchyHistoricalParityReport, AsyncNodeHierarchyReplaySummary,
    AsyncNodeHistoricalParityDenialClass, AsyncNodeHistoricalParityReport,
    AsyncNodeMilestoneDCertificationRun, AsyncNodeMilestoneDCertificationRunSummary,
    AsyncNodeMilestoneDPerformanceClaimId, AsyncNodeMilestoneDPerformanceCloseout,
    AsyncNodeMilestoneDPerformanceCloseoutRow, AsyncNodeMilestoneDPerformanceCloseoutSummary,
    AsyncNodeMilestoneDScenarioEvidenceKind, AsyncNodeMilestoneDScenarioId,
    AsyncNodeMilestoneDScenarioInputs, AsyncNodeMilestoneDScenarioMatrix,
    AsyncNodeMilestoneDScenarioMatrixSummary, AsyncNodeMilestoneDScenarioRow,
    AsyncNodePayloadContract, AsyncNodePayloadContractId, AsyncNodeRequestAdmissionReport,
    AsyncNodeRequestIntent, AsyncNodeRevalidationIntent, AsyncNodeRevalidationReport,
    DeniedAsyncKeyedNodeCapabilityEquivalence, DeniedAsyncKeyedNodeHistoricalParity,
    DeniedAsyncNodeCapabilityEquivalence, DeniedAsyncNodeHierarchyHistoricalParity,
    DeniedAsyncNodeHistoricalParity, FrozenAsyncNodeCapabilityDescriptor,
    LoweredAsyncNodeCapabilityBundle, ValidatedAsyncNodeCapabilityDeclaration,
    ASYNC_NODE_COMPILE_TIME_BOUNDARY_PROOF_SCHEMA_VERSION,
    ASYNC_NODE_MILESTONE_D_CERTIFICATION_RUN_SCHEMA_VERSION,
    ASYNC_NODE_MILESTONE_D_PERFORMANCE_CLOSEOUT_SCHEMA_VERSION,
    ASYNC_NODE_MILESTONE_D_SCENARIO_MATRIX_SCHEMA_VERSION,
    REQUIRED_ASYNC_NODE_COMPILE_TIME_FIXTURES, REQUIRED_ASYNC_NODE_MILESTONE_D_PERFORMANCE_CLAIMS,
    REQUIRED_ASYNC_NODE_MILESTONE_D_SCENARIOS,
};
pub use crate::data::authorization::{
    InstalledSignalAuthorizationPolicy, SignalAuthorizationClauseContract,
    SignalAuthorizationClauseObservation, SignalAuthorizationDecision,
    SignalAuthorizationDecisionEvidence, SignalAuthorizationDenial,
    SignalAuthorizationDependencyCardinality, SignalAuthorizationEvaluationCounters,
    SignalAuthorizationObservation, SignalAuthorizationPolicyDefinition,
    SignalAuthorizationPolicyIdentity, SignalAuthorizationRequirementContract,
    SignalAuthorizationRequirementObservation, SignalAuthorizationRuleContract,
    SignalAuthorizationRuleDecisionEvidence, SignalAuthorizationRuleEffect,
    SignalAuthorizationRuleObservation,
};
pub use crate::data::comparator::{
    ComparatorPolicyResolver, InstalledSignalComparatorIdentity, VersionComparatorPolicy,
    VersionComparatorResolver,
};
pub use crate::data::conditional_execution::{
    resolve_signal_delta_threshold, InstalledSignalComparatorUse, InstalledSignalConditionDecision,
    InstalledSignalConditionResolver, InstalledSignalConditionalContract,
    SignalConditionalArtifactReuse, SignalConditionalArtifactReuseClass,
    SignalConditionalArtifactReusePolicy, SignalConditionalComparatorClass,
    SignalConditionalComparatorPosition, SignalConditionalComparisonWork,
    SignalConditionalCondition, SignalConditionalConditionClass,
    SignalConditionalContractDefinition, SignalConditionalContractDenial,
    SignalConditionalDecisionClass, SignalConditionalDecisionCounters,
    SignalConditionalDecisionEvidence, SignalConditionalDecisionIdentityKind,
    SignalConditionalDecisionProjectionIdentity, SignalConditionalExecutionAffinity,
    SignalConditionalExecutionAffinityComparisonMismatch,
    SignalConditionalExecutionAffinityMismatch, SignalConditionalExecutionFailure,
    SignalConditionalExecutionRequest, SignalConditionalSemanticComparisonMismatch,
    SignalConditionalSemanticContinuity, SignalConditionalSemanticMismatch,
    SignalConditionalVersionComparator, SignalDeltaThresholdContract, SignalThresholdBoundary,
    SignalThresholdComparisonDomain, SignalThresholdValueFamily,
};
pub use crate::data::core_profile::CORE_STORAGE_PROFILE_ID;
pub use crate::data::dependency::DependencyEdge;
pub use crate::data::error::SignalError;
pub use crate::data::graph::{NodeBuilder, SignalGraph, SignalGraphLifecycleProbe};
pub use crate::data::handle::NodeId;
pub use crate::data::host_computed::{
    AdmittedHostComputedReadSet, CommittedHostComputedArtifact, DeniedHostComputedEvaluation,
    DeniedHostComputedReadSet, HostComputedApiFamily, HostComputedDenialClass,
    HostComputedDependencyPatch, HostComputedDescriptor, HostComputedDescriptorId,
    HostComputedDiagnosticsSummary, HostComputedEvaluationOutcome, HostComputedEvaluationRequest,
    HostComputedEvaluationResponse, HostComputedEvaluator, HostComputedFailure,
    HostComputedFailureClass, HostComputedOutcomeClass, HostComputedPreparedResponse,
    PreparedHostComputedEvaluation, StagedHostComputedArtifact,
};
pub use crate::data::node::{EvaluationCondition, InstalledSignalConditionIdentity, NodeState};
pub use crate::data::output::{
    CanonicalChangedRegions, ChangedRegion, NodeEvaluationResult, OutputChange, OutputIdentity,
    PartitionMatchMode, PartitionSubscription, PartitionToken,
};
pub use crate::data::output_equivalence::OutputEquivalencePolicy;
pub use crate::data::resource::{
    resource_certification_builder, resource_certification_bundle,
    resource_certification_bundle_parity_report, resource_milestone_b_certification_run,
    resource_milestone_b_hostile_scenario_evidence, resource_milestone_b_performance_closeout,
    resource_milestone_b_scenario_matrix, resource_milestone_c_certification_run,
    resource_milestone_c_policy_certification_builder,
    resource_milestone_c_policy_certification_bundle,
    resource_milestone_c_policy_performance_closeout, resource_milestone_c_policy_scenario_matrix,
    ActiveResourceRevalidationProof, AdmittedResourceCompletion, AdmittedResourceRequest,
    AdmittedResourceRetry, AdmittedResourceRevalidation, AsyncDenialId, CancelledResourceRequest,
    CommittedResourceCompletionArtifact, CompletionDenialClass, DeniedResourceCancellation,
    DeniedResourceCompletion, DeniedResourcePolicyRestoreCompatibility, DeniedResourceRejection,
    DeniedResourceRetry, DeniedResourceRevalidation, DeniedResourceTimeout,
    DeniedResourceTimeoutHeartbeatExtension, DependencyChangeResourceRevalidationProof,
    ExtendedResourceTimeoutHeartbeat, FrozenResourcePolicyDescriptor,
    FrozenResourcePolicyDescriptorSet, FrozenResourcePolicyRegistry,
    FulfilledLifecycleResourceRevalidationProof, InFlightResourceRequest,
    LoweredResourcePolicyBundle, ObservedResourceNodeState,
    ObserverDemandResourceRevalidationProof, RawCompletionEnvelope, RejectedResourceRequest,
    ResourceAttemptId, ResourceBranchEpoch, ResourceBranchRestoreReport,
    ResourceCancellationDecisionClass, ResourceCancellationDecisionPlan,
    ResourceCancellationDenialClass, ResourceCancellationGraceWindow, ResourceCancellationOrdinal,
    ResourceCancellationPolicyDeclaration, ResourceCancellationReason, ResourceCancellationReport,
    ResourceCertificationBuilder, ResourceCertificationBundle,
    ResourceCertificationBundleMismatchClass, ResourceCertificationBundleParityReport,
    ResourceCertificationFailure, ResourceCertificationFamily, ResourceCertificationRecord,
    ResourceCertificationSummary, ResourceCompletionAdmissionReport,
    ResourceCompletionBatchAdmissionReport, ResourceCompletionCommitReport,
    ResourceCompletionDenialStagingReport, ResourceCompletionOrdinal,
    ResourceCompletionRollbackReport, ResourceCompletionRollbackSubject,
    ResourceCompletionStagingReport, ResourceCostContractId, ResourceCostPosture,
    ResourceDensityStrategy, ResourceDependentCancellationPropagation,
    ResourceDiagnosticsDecisionClass, ResourceDiagnosticsDecisionPlan,
    ResourceDiagnosticsExpansionBudget, ResourceDiagnosticsExpansionDenial,
    ResourceDiagnosticsExpansionDenialClass, ResourceDiagnosticsPolicyDeclaration,
    ResourceDiagnosticsSummary, ResourceGeneration, ResourceHostCancellationAdvisory,
    ResourceInFlightStatus, ResourceInitialLifecycleClass, ResourceIntentEquivalenceCoalescing,
    ResourceLifecycleClass, ResourceLifecycleOrdinal, ResourceLifecyclePolicyDeclaration,
    ResourceLifecycleRetentionCompactionReport, ResourceLifecycleTransition,
    ResourceLifecycleTransitionKind, ResourceManagedQueueBinding, ResourceManagedQueueCounters,
    ResourceManagedQueueDenial, ResourceManagedQueueDenialClass, ResourceManagedQueueMutationKind,
    ResourceManagedQueueMutationReport, ResourceMilestoneBCertificationRun,
    ResourceMilestoneBCertificationRunSummary, ResourceMilestoneBHostileScenarioEvidence,
    ResourceMilestoneBHostileScenarioEvidenceRow, ResourceMilestoneBPerformanceClaimId,
    ResourceMilestoneBPerformanceCloseout, ResourceMilestoneBPerformanceCloseoutRow,
    ResourceMilestoneBPerformanceCloseoutSummary, ResourceMilestoneBScenarioEvidenceKind,
    ResourceMilestoneBScenarioId, ResourceMilestoneBScenarioMatrix,
    ResourceMilestoneBScenarioMatrixSummary, ResourceMilestoneBScenarioRow,
    ResourceMilestoneCCertificationRun, ResourceMilestoneCCertificationRunSummary,
    ResourceMilestoneCPolicyCertificationBuilder, ResourceMilestoneCPolicyCertificationBundle,
    ResourceMilestoneCPolicyCertificationFamily, ResourceMilestoneCPolicyCertificationRecord,
    ResourceMilestoneCPolicyCertificationSummary, ResourceMilestoneCPolicyPerformanceClaimId,
    ResourceMilestoneCPolicyPerformanceCloseout, ResourceMilestoneCPolicyPerformanceCloseoutRow,
    ResourceMilestoneCPolicyPerformanceCloseoutSummary,
    ResourceMilestoneCPolicyScenarioEvidenceKind, ResourceMilestoneCPolicyScenarioId,
    ResourceMilestoneCPolicyScenarioMatrix, ResourceMilestoneCPolicyScenarioMatrixSummary,
    ResourceMilestoneCPolicyScenarioRow, ResourceNodeDeclaration, ResourceNodeId,
    ResourceObservationBatchReport, ResourceObservationDecisionClass,
    ResourceObservationDecisionPlan, ResourceObservationEvent,
    ResourceObservationPolicyDeclaration, ResourceOldHostWorkCancellationAdvisory,
    ResourceOutputContinuity, ResourceOutputContinuityDecisionClass,
    ResourceOutputContinuityDecisionPlan, ResourceOutputContinuityPolicyDeclaration,
    ResourceOverlappingGenerationAdmission, ResourcePayloadContract, ResourcePayloadContractDigest,
    ResourcePayloadContractId, ResourcePolicyCompatibilityClass,
    ResourcePolicyCompatibilityFamilyReport, ResourcePolicyCompatibilityPosture,
    ResourcePolicyCompatibilityReport, ResourcePolicyDescriptor, ResourcePolicyDescriptorId,
    ResourcePolicyDigest, ResourcePolicyKind, ResourcePolicyName, ResourcePolicyRegistration,
    ResourcePolicyRegistryError, ResourcePolicyRegistryFreezeReport, ResourcePolicyResolutionError,
    ResourcePolicyRestoreCompatibilityDenialClass, ResourcePolicyRestoreCompatibilityProof,
    ResourcePolicySelectionBasis, ResourcePolicyVersion, ResourceQueuePressureClass,
    ResourceQueuePressureObservation, ResourceRejectionDenialClass, ResourceRejectionOrdinal,
    ResourceRejectionReason, ResourceRejectionReport, ResourceReplayReconstructionReport,
    ResourceRequestHandle, ResourceRequestId, ResourceRequestIntent, ResourceRequestIntentDigest,
    ResourceResolvedPolicy, ResourceResolvedPolicyBundle,
    ResourceRetainedDeniedCompletionAvailability,
    ResourceRetainedDeniedCompletionAvailabilityClass, ResourceRetainedHistoryAvailability,
    ResourceRetainedHistoryAvailabilityClass, ResourceRetainedRetryLineageAvailability,
    ResourceRetainedRetryLineageAvailabilityClass, ResourceRetentionCompactionBudget,
    ResourceRetentionDecisionClass, ResourceRetentionDecisionPlan,
    ResourceRetentionPolicyDeclaration, ResourceRetryAdmissionReport, ResourceRetryBudgetScope,
    ResourceRetryDecisionClass, ResourceRetryDecisionPlan, ResourceRetryDenialClass,
    ResourceRetryOrdinal, ResourceRetryPolicyDeclaration, ResourceRetryReason,
    ResourceRetryScheduleReport, ResourceRevalidationCoalescing, ResourceRevalidationDecisionClass,
    ResourceRevalidationDecisionPlan, ResourceRevalidationDenialClass,
    ResourceRevalidationEvidence, ResourceRevalidationFreshnessClass,
    ResourceRevalidationFreshnessDecision, ResourceRevalidationIntent,
    ResourceRevalidationPolicyDeclaration, ResourceRevalidationReport,
    ResourceRuntimeSummaryReadReport, ResourceSafePointObservationCounters,
    ResourceSafePointObservationDenial, ResourceSafePointObservationDenialClass,
    ResourceSafePointObservationOrdinal, ResourceSafePointObservationReport,
    ResourceStaleAfterDecisionClass, ResourceStaleAfterDecisionPlan,
    ResourceStaleAfterPolicyDeclaration, ResourceSupersessionDecisionClass,
    ResourceSupersessionDecisionPlan, ResourceSupersessionOldHostWorkPosture,
    ResourceSupersessionOrdinal, ResourceSupersessionOverlapDisposition,
    ResourceSupersessionPolicyDeclaration, ResourceSupersessionRecord,
    ResourceTimeoutDeadlineAuthority, ResourceTimeoutDecisionClass, ResourceTimeoutDecisionPlan,
    ResourceTimeoutDenialClass, ResourceTimeoutHeartbeatExtensionDenialClass,
    ResourceTimeoutHeartbeatExtensionReport, ResourceTimeoutOrdinal, ResourceTimeoutOutcomeClass,
    ResourceTimeoutPolicyDeclaration, ResourceTimeoutReport, RetainedResourceRetryLineage,
    RolledBackResourceCompletionArtifact, ScheduledResourceRetry,
    StagedDeniedResourceCompletionEffect, StagedResourceCompletionEffect,
    TerminalStateResourceRevalidationProof, TimedOutResourceRequest, ValidatedCompletionEnvelope,
    ValidatedResourcePolicyDeclaration, ValidatedResourcePolicyReference,
    REQUIRED_RESOURCE_CERTIFICATION_FAMILIES, REQUIRED_RESOURCE_MILESTONE_B_HOSTILE_SCENARIOS,
    REQUIRED_RESOURCE_MILESTONE_B_PERFORMANCE_CLAIMS, REQUIRED_RESOURCE_MILESTONE_B_SCENARIOS,
    REQUIRED_RESOURCE_MILESTONE_C_POLICY_CERTIFICATION_FAMILIES,
    REQUIRED_RESOURCE_MILESTONE_C_POLICY_PERFORMANCE_CLAIMS,
    REQUIRED_RESOURCE_MILESTONE_C_POLICY_SCENARIOS,
    RESOURCE_CERTIFICATION_BUNDLE_PARITY_SCHEMA_VERSION,
    RESOURCE_CERTIFICATION_BUNDLE_SCHEMA_VERSION, RESOURCE_DIAGNOSTICS_SUMMARY_SCHEMA_VERSION,
    RESOURCE_MILESTONE_B_CERTIFICATION_RUN_SCHEMA_VERSION,
    RESOURCE_MILESTONE_B_HOSTILE_SCENARIO_EVIDENCE_SCHEMA_VERSION,
    RESOURCE_MILESTONE_B_PERFORMANCE_CLOSEOUT_SCHEMA_VERSION,
    RESOURCE_MILESTONE_B_SCENARIO_MATRIX_SCHEMA_VERSION,
    RESOURCE_MILESTONE_C_CERTIFICATION_RUN_SCHEMA_VERSION,
    RESOURCE_MILESTONE_C_POLICY_CERTIFICATION_BUNDLE_SCHEMA_VERSION,
    RESOURCE_MILESTONE_C_POLICY_PERFORMANCE_CLOSEOUT_SCHEMA_VERSION,
    RESOURCE_MILESTONE_C_POLICY_SCENARIO_MATRIX_SCHEMA_VERSION,
};
pub use crate::data::temporal::{
    AfterCondition, AtOrAfterCondition, BoundedTemporalReadyPromotionSummary, ClockAdvanceOrdinal,
    ClockAdvanceRequest, ClockAuthority, ClockCheckpointId, ClockDomain, ClockTick,
    DebounceCondition, DeferredTemporalEligibility, IntervalAnchor, IntervalCondition,
    IntervalPeriod, IntervalWakeRegeneration, LoweredTemporalEligibility, MissedTickPolicy,
    PreviousValueRevision, ReadyTemporalEligibility, RuntimeClockBasis, StaleAfterCondition,
    TemporalClockAdvanceSummary, TemporalCondition, TemporalDuration, TemporalEligibilityAuthority,
    TemporalExecutionSummary, TemporalFrontierSnapshot, TemporalPreviousValueAccess,
    TemporalPreviousValueReference, TemporalReadyPromotionSummary, TemporalWakeAdmissionSummary,
    TemporalWakeOwner, TemporalWakeReschedule, TemporalWakeRetirementBatch, TemporalWakeReuse,
    ThrottleCondition, ValidatedClockAdvance,
};
pub use crate::data::trace::TraceSummary;
pub use crate::logic::evaluation::ConditionEvaluationContext;
pub use crate::logic::invalidation::mark_dirty_batch;
pub use diagnostics_views::refresh_retained_diagnostics_views;
pub use invalidation::{
    mark_changed, mark_changed_with_regions, mark_dirty, mark_dirty_with_regions,
};
