use super::{surface, text, DashboardElement, DashboardGraphic};

pub(super) fn elements() -> Vec<DashboardElement> {
    vec![
        surface(
            "active_card",
            [266, 152, 253, 98],
            "raised_surface",
            12,
            true,
            2,
        ),
        text(
            "active_label",
            "Active services",
            [291, 171, 211, 21],
            12,
            false,
            "primary_text",
        ),
        text(
            "active_value",
            "24",
            [291, 197, 115, 40],
            28,
            true,
            "primary_text",
        ),
        text(
            "active_trend",
            "↑ 2%",
            [356, 208, 80, 26],
            14,
            false,
            "positive",
        ),
        surface(
            "active_icon_back",
            [451, 171, 44, 44],
            "mint_pale",
            32,
            false,
            3,
        ),
        surface("active_icon", [464, 184, 18, 18], "positive", 12, false, 4)
            .graphic(DashboardGraphic::Server),
        surface(
            "query_card",
            [535, 152, 248, 98],
            "raised_surface",
            12,
            true,
            2,
        ),
        text(
            "query_label",
            "Request volume",
            [560, 171, 206, 21],
            12,
            false,
            "primary_text",
        ),
        text(
            "request_volume",
            "1.2M",
            [560, 197, 115, 40],
            28,
            true,
            "primary_text",
        ),
        text(
            "query_trend",
            "↑ 12%",
            [651, 208, 80, 26],
            14,
            false,
            "positive",
        ),
        surface(
            "query_icon_back",
            [715, 171, 44, 44],
            "lavender_pale",
            32,
            false,
            3,
        ),
        surface(
            "query_icon",
            [728, 184, 18, 18],
            "principal_accent",
            12,
            false,
            4,
        )
        .graphic(DashboardGraphic::Bars),
        surface(
            "error_card",
            [799, 152, 237, 98],
            "raised_surface",
            12,
            true,
            2,
        ),
        text(
            "error_label",
            "Error rate",
            [824, 171, 195, 21],
            12,
            false,
            "primary_text",
        ),
        text(
            "error_value",
            "0.28%",
            [824, 197, 115, 40],
            28,
            true,
            "primary_text",
        ),
        text(
            "error_trend",
            "↓ 35%",
            [925, 208, 80, 26],
            14,
            false,
            "positive",
        ),
        surface(
            "error_icon_back",
            [968, 171, 44, 44],
            "coral_pale",
            32,
            false,
            3,
        ),
        surface("error_icon", [981, 184, 18, 18], "negative", 12, false, 4)
            .graphic(DashboardGraphic::Warning),
        surface(
            "latency_card",
            [1052, 152, 237, 98],
            "raised_surface",
            12,
            true,
            2,
        ),
        text(
            "latency_label",
            "P95 latency",
            [1077, 171, 195, 21],
            12,
            false,
            "primary_text",
        ),
        text(
            "latency_value",
            "186 ms",
            [1077, 197, 115, 40],
            28,
            true,
            "primary_text",
        ),
        text(
            "latency_trend",
            "↓ 8%",
            [1168, 208, 80, 26],
            14,
            false,
            "caution",
        ),
        surface(
            "latency_icon_back",
            [1221, 171, 44, 44],
            "amber_pale",
            32,
            false,
            3,
        ),
        surface("latency_icon", [1234, 184, 18, 18], "caution", 12, false, 4)
            .graphic(DashboardGraphic::Clock),
    ]
}
