export interface WebPerformanceSummary {
  activeHandleCount: number;
  activeCallbackCount: number;
  activeComputeCallbackCount: number;
  activeComputeCollectorCount: number;
  matchedWatcherBreadth: number;
  deliveredObservationCount: number;
  rollbackSuppressedDeliveryCount: number;
  serialExecutorUsageCount: number;
  executionReport: WebExecutionReportSummary | null;
  outputSerializationCount: number;
  outputSerializationBreadth: number;
  jsCallbackInvocationCount: number;
  jsCallbackFailureCount: number;
  observationCallbackRegistrationCount: number;
  observationCallbackDisposalCount: number;
  observationCallbackGenerationMismatchDenialCount: number;
  observationCallbackAllocationCount: number;
  observationCallbackReuseCount: number;
  computeCallbackRegistrationCount: number;
  computeCallbackDisposalCount: number;
  computeCallbackInvocationCount: number;
  computeCallbackFailureCount: number;
  computeCallbackGenerationMismatchDenialCount: number;
  computeCallbackSelfReadDenialCount: number;
  computeCallbackDynamicCycleDenialCount: number;
  computeCallbackPromiseReturnDenialCount: number;
  computeCallbackInvalidReturnDenialCount: number;
  computeCallbackCollectorInstallationCount: number;
  computeCallbackCaptureCount: number;
  computeCallbackCapturedReadCount: number;
  computeCallbackReturnSerializationBreadth: number;
  computeCallbackAllocationCount: number;
  computeCallbackReuseCount: number;
  computeCallbackDependencyPatchCount: number;
  computeCallbackDependencyPatchAddedCount: number;
  computeCallbackDependencyPatchRemovedCount: number;
  computeCallbackDependencyPatchRetainedCount: number;
  computeCallbackRuntimeReadBreadth: number;
  computeCallbackConstantNoSignalReadClassificationCount: number;
  computeCallbackSignalTrackedClassificationCount: number;
  computeCallbackMissingUnavailabilityCount: number;
  compatibilityReadCount: number;
  compatibilityReadBreadth: number;
  hostCapabilityRegistrationCount?: number;
  hostCapabilityDisposalCount?: number;
  hostCapabilityReadCount?: number;
  hostCapabilityPollCount?: number;
  hostCapabilityNoOpPollCount?: number;
  hostCapabilityManualCommitCount?: number;
  hostCapabilityNoOpManualCommitCount?: number;
  hostCapabilityInvalidationCount?: number;
  hostCapabilityInvalidationBatchFlushCount?: number;
  hostCapabilityReevaluationCount?: number;
  hostCapabilityInvalidationTouchedNodeCount?: number;
  hostCapabilityNoOpInvalidationSuppressedCount?: number;
  hostCapabilityStaleInvalidationIgnoredCount?: number;
  hostCapabilityCompatibilityDenialCount?: number;
  hostCapabilityUnavailabilityArtifactCount?: number;
  hostCapabilityBroadFanoutDenialCount?: number;
}

export interface WebExecutionReportSummary {
  resolvedPosture: string;
  chargedWork: number;
  chargedSpan: number;
  activeWorkersHighWatermark: number;
  peakChargedMemoryBytes: number;
  peakQueueWidth: number;
  discardedInFlightWork: number;
  fallback: string | null;
}
