pub use crate::aspects::{
    admit_authoritative_record_aspect_state, aspects, classify_aspect_contract_evolution,
    export_portable_record_aspect_patch, export_portable_record_aspect_state,
    readmit_portable_record_aspect_patch, readmit_portable_record_aspect_state,
    validate_aspect_value, AbsenceLaw, AspectBinding, AspectContract, AspectContractFrontDoor,
    AspectContractIdentityStep, AspectContractRevision, AspectContractRevisionStep,
    AspectContractShapeStep, AspectEquivalenceBasis, AspectEvolutionClassified,
    AspectEvolutionClassifiedContractArtifact, AspectEvolutionClassifiedContracts,
    AspectEvolutionKind, AspectEvolutionPolicy, AspectEvolutionVerdict,
    AspectFrontDoorConstructionDenial, AspectIdentity, AspectKey, AspectMask, AspectMaskContract,
    AspectMaskContractFrontDoor, AspectPatchFrontDoor, AspectShape, AspectValidationFrontDoor,
    AspectValidationInputStep, AspectValuePosture, AspectVocabularyFrontDoor, AspectsFrontDoor,
    AuthoritativeAspectChangeKind, AuthoritativePatchApplicationDenial,
    AuthoritativePatchConstructionDenial, AuthoritativeRecordAspectPatch,
    AuthoritativeRecordAspectState, AuthoritativeRecordAspectStateAdmitted,
    AuthoritativeRecordAspectStateArtifact, AuthoritativeStateAdmissionDenial,
    AuthoritativeStateFrontDoor, CanonicalAspectStateMap, CanonicalFieldPath,
    ContractValidatedAspectArtifact, ContractValidatedAspectValue,
    ContractValidatedAspectValueView, ContractValidationDenial, ContractValidationInput,
    DiagnosticMask, DiagnosticMaskFrontDoor, FieldDeclaration, FieldKey, FieldLevelAspectPatch,
    FieldLevelPatchBuilder, FieldRequirement, MaskAdmissibilityDenial, MutationMask,
    MutationMaskFrontDoor, OpaqueAspectType, PortableAspectContract, PortableAspectContractBasis,
    PortableAspectContractDenial, PortableAspectContractLookup, PortableAspectExportDenial,
    PortableAspectFieldSet, PortableAspectPatchOperation, PortableAspectReadmissionDenial,
    PortablePatchReadmissionPurpose, PortableRecordAspectPatch, PortableRecordAspectState,
    PortableRecordAspectStateEntry, ProjectionMask, ProjectionMaskFrontDoor, ReferenceAspectType,
    StructAspectShape, StructAspectValue, StructAspectValueConstructionDenial, StructFieldBuilder,
    StructFieldsFrontDoor, StructValueBuilder, TruthPartitionRole, WholeAspectPatchBuilder,
};
pub use crate::boundary::{
    certify_milestone1_production_test_readiness, declared_foundational_boundary,
    milestone1_compatibility_debt_inventory, milestone1_migration_readiness_report,
    milestone1_proof_seed_inventory, milestone1_public_api_inventory,
    require_milestone1_production_test_readiness, FoundationalBoundaryArtifact,
    FoundationalBoundaryDeclaration, FoundationalBoundaryDeclared, Milestone1CompatibilityDebt,
    Milestone1MigrationReadinessReport, Milestone1ProductionReadinessAuthority,
    Milestone1ProductionReadinessCertified, Milestone1ProductionReadinessScope,
    Milestone1ProductionTestReady, Milestone1ProductionTestReadyArtifact, Milestone1ProofSeed,
    Milestone1PublicApiSurface,
};
pub use crate::boundary_artifacts::{
    admit_authoritative_current_boundary_surface, admit_current_basis_boundary_artifact,
    admit_current_basis_boundary_bundle, admit_planned_work_boundary_artifact,
    admit_same_family_boundary_artifact, boundary_artifact_category_definitions,
    boundary_artifact_category_of, boundary_artifact_surface_definition,
    boundary_receipt_category_of, boundary_receipt_definition, boundary_report_category_of,
    boundary_report_definition, boundary_role_definitions, boundary_summary_category_of,
    boundary_summary_definition, bridge_current_basis_boundary_artifact_trust_boundary,
    bridge_current_basis_boundary_bundle_trust_boundary,
    certify_foundational_boundary_artifact_milestone4_production_test_readiness,
    claim_derived_projection_boundary_surface, claim_planned_work_boundary_surface,
    claim_receipt_evidence_boundary_surface, claim_support_only_boundary_surface,
    derive_same_family_boundary_identity, evaluate_boundary_role_claim_legality,
    evaluate_boundary_surface_disposition_legality,
    evaluate_planned_work_reserved_authority_transition_legality,
    evaluate_same_family_reserved_authority_transition_legality,
    foundational_boundary_artifact_milestone4_readiness_report,
    foundational_boundary_authority_admission, foundational_boundary_canonical_basis_entries,
    foundational_boundary_current_basis_authority, foundational_boundary_current_basis_proof_lane,
    foundational_boundary_current_basis_readmission_authority,
    materialize_authoritative_boundary_surface, materialize_descriptive_boundary_surface,
    plan_artifact_boundary_bundle, plan_authoritative_boundary_materialization,
    plan_descriptive_boundary_materialization,
    prepare_materialized_boundary_artifact_for_canonical_basis,
    prepare_materialized_boundary_bundle_for_canonical_basis,
    prepare_same_family_boundary_artifact_for_canonical_basis,
    readmit_current_basis_boundary_artifact_after_boundary,
    readmit_current_basis_boundary_bundle_after_boundary,
    require_foundational_boundary_artifact_milestone4_production_test_readiness, ArtifactCategory,
    AuthoritativeCurrentRole, BoundaryBridgedCurrentBasisBoundaryArtifact,
    BoundaryBridgedCurrentBasisBoundaryBundle, CurrentBasisBoundaryArtifact,
    CurrentBasisBoundaryArtifactPhase, CurrentBasisBoundaryBundle, DerivedProjectionRole,
    FoundationalAuthoritativeBoundaryClaim, FoundationalBoundaryArtifactCategory,
    FoundationalBoundaryArtifactCertifiedSurface,
    FoundationalBoundaryArtifactCertifiedSurfaceEvidence,
    FoundationalBoundaryArtifactCompileFailBoundary,
    FoundationalBoundaryArtifactMilestone4PhaseGate, FoundationalBoundaryArtifactPhaseGateEvidence,
    FoundationalBoundaryArtifactProductionReadinessAuthority,
    FoundationalBoundaryArtifactProductionReadinessCertified,
    FoundationalBoundaryArtifactProductionReadinessReport,
    FoundationalBoundaryArtifactProductionReadinessScope,
    FoundationalBoundaryArtifactProductionTestReady,
    FoundationalBoundaryArtifactProductionTestReadyArtifact,
    FoundationalBoundaryArtifactResidualDebt, FoundationalBoundaryArtifactRole,
    FoundationalBoundaryArtifactRuntimeAssumption,
    FoundationalBoundaryArtifactRuntimeNonAssumption, FoundationalBoundaryArtifactSurface,
    FoundationalBoundaryArtifactSyntheticRuntimePressure,
    FoundationalBoundaryArtifactWORTHProofApi,
    FoundationalBoundaryArtifactWORTHProofForbiddenSurface,
    FoundationalBoundaryArtifactWORTHProofSurface, FoundationalBoundaryAttachmentPoint,
    FoundationalBoundaryAuthorityAdmission, FoundationalBoundaryAuthorityAdmissionBasis,
    FoundationalBoundaryAuthorityAdmitted, FoundationalBoundaryAvailability,
    FoundationalBoundaryBundleMaterializationCost, FoundationalBoundaryBundleMaterializationDenial,
    FoundationalBoundaryBundlePlanningDenial, FoundationalBoundaryCategoryConstructionDenial,
    FoundationalBoundaryCategoryDefinition, FoundationalBoundaryCategoryMarker,
    FoundationalBoundaryCategorySurface, FoundationalBoundaryCurrentBasisAuthority,
    FoundationalBoundaryCurrentBasisCertified, FoundationalBoundaryCurrentBasisProofLane,
    FoundationalBoundaryCurrentBasisReadmissionAuthority, FoundationalBoundaryDecisionCause,
    FoundationalBoundaryDecisionSubject, FoundationalBoundaryDeliveryClass,
    FoundationalBoundaryMaterializationAttachment, FoundationalBoundaryMaterializationBundle,
    FoundationalBoundaryMaterializationBundlePlan, FoundationalBoundaryMaterializationCost,
    FoundationalBoundaryMaterializationDecisionRow, FoundationalBoundaryMaterializationDenial,
    FoundationalBoundaryMaterializationInput, FoundationalBoundaryMaterializationPlan,
    FoundationalBoundaryMaterializationSeam, FoundationalBoundaryMaterializationSource,
    FoundationalBoundaryPlanningDenial, FoundationalBoundaryReceiptSurface,
    FoundationalBoundaryReportSurface, FoundationalBoundaryRoleClaim,
    FoundationalBoundaryRoleClaimDenial, FoundationalBoundaryRoleDefinition,
    FoundationalBoundaryRoleMarker, FoundationalBoundarySummarySurface,
    FoundationalBoundarySurfaceDisposition, FoundationalBoundarySurfaceDispositionDenial,
    FoundationalBoundarySurfaceDispositionLegality, FoundationalDerivedProjectionBoundaryClaim,
    FoundationalMaterializedBoundaryArtifact, FoundationalPlannedWorkBoundaryArtifact,
    FoundationalPlannedWorkBoundaryArtifactDenial, FoundationalPlannedWorkBoundaryClaim,
    FoundationalReceiptEvidenceBoundaryClaim, FoundationalReservedAuthorityTransitionDenial,
    FoundationalReservedAuthorityTransitionKind, FoundationalSameFamilyBoundaryArtifact,
    FoundationalSameFamilyBoundaryArtifactDenial, FoundationalSameFamilyBoundaryFamily,
    FoundationalSameFamilyBoundaryFamilyDenial, FoundationalSameFamilyBoundaryIdentity,
    FoundationalSupportOnlyBoundaryClaim, PlannedWorkRole, ReceiptCategory, ReceiptEvidenceRole,
    ReportCategory, SummaryCategory, SupportOnlyRole,
};
pub use crate::boundary_evidence::{
    admit_current_basis_boundary_evidence_attachment_bundle, attachment, boundary_evidence,
    bridge_current_basis_boundary_evidence_attachment_bundle_trust_boundary,
    certify_foundational_boundary_evidence_milestone7_production_test_readiness,
    derive_boundary_evidence_attachment_bundle_digest,
    evaluate_boundary_evidence_primitive_legality,
    foundational_boundary_evidence_attachment_readmission_authority,
    foundational_boundary_evidence_attachment_target_kind_definitions,
    foundational_boundary_evidence_branch_divergence_posture_definitions,
    foundational_boundary_evidence_category_definitions,
    foundational_boundary_evidence_closeout_disposition_definitions,
    foundational_boundary_evidence_continuity_attachment_scope_definitions,
    foundational_boundary_evidence_descriptive_role_definitions,
    foundational_boundary_evidence_execution_posture_definitions,
    foundational_boundary_evidence_freshness_posture_definitions,
    foundational_boundary_evidence_lineage_outcome_kind_definitions,
    foundational_boundary_evidence_lineage_partiality_posture_definitions,
    foundational_boundary_evidence_locality_definitions,
    foundational_boundary_evidence_materialization_profile_definitions,
    foundational_boundary_evidence_milestone7_readiness_report,
    foundational_boundary_evidence_promotion_posture_definitions,
    foundational_boundary_evidence_provenance_layer_definitions,
    foundational_boundary_evidence_receipt_kind_definitions,
    foundational_boundary_evidence_source_basis_kind_definitions,
    foundational_boundary_evidence_support_basis_disclosure_definitions,
    foundational_boundary_evidence_support_recovery_posture_definitions,
    foundational_boundary_evidence_support_residual_debt_kind_definitions,
    foundational_boundary_evidence_support_truth_kind_definitions, lineage,
    prepare_boundary_evidence_attachment_bundle_for_canonical_basis, provenance,
    readmit_current_basis_boundary_evidence_attachment_bundle_after_boundary,
    readmit_support_basis_boundary_evidence_attachment_bundle_after_boundary, receipt,
    require_foundational_boundary_evidence_milestone7_production_test_readiness, support,
    BoundaryBridgedCurrentBasisBoundaryEvidenceAttachmentBundle,
    BoundaryBridgedSupportBasisBoundaryEvidenceAttachmentBundle, BoundaryEvidenceFrontDoor,
    CurrentBasisBoundaryEvidenceAttachmentBundle, FoundationalBoundaryEvidenceAttachmentBundle,
    FoundationalBoundaryEvidenceAttachmentDigestDerivationDenial,
    FoundationalBoundaryEvidenceAttachmentFrontDoor,
    FoundationalBoundaryEvidenceAttachmentReadmissionAuthority,
    FoundationalBoundaryEvidenceAttachmentTarget, FoundationalBoundaryEvidenceAttachmentTargetKind,
    FoundationalBoundaryEvidenceAttestedLineageArtifact, FoundationalBoundaryEvidenceAuthorityPath,
    FoundationalBoundaryEvidenceBranchDivergencePosture,
    FoundationalBoundaryEvidenceBranchLocalLineageArtifact,
    FoundationalBoundaryEvidenceCanonicalDigestBasis, FoundationalBoundaryEvidenceCategory,
    FoundationalBoundaryEvidenceCertifiedSurface,
    FoundationalBoundaryEvidenceCertifiedSurfaceEvidence,
    FoundationalBoundaryEvidenceCloseoutDisposition, FoundationalBoundaryEvidenceComparisonBasis,
    FoundationalBoundaryEvidenceCompileFailBoundary,
    FoundationalBoundaryEvidenceCompletedReceiptArtifact,
    FoundationalBoundaryEvidenceContinuityAttachmentScope,
    FoundationalBoundaryEvidenceDescriptiveRole, FoundationalBoundaryEvidenceDiagnosticAttachment,
    FoundationalBoundaryEvidenceExecutedReceiptArtifact,
    FoundationalBoundaryEvidenceExecutionPosture, FoundationalBoundaryEvidenceFreshnessPosture,
    FoundationalBoundaryEvidenceGoldenArtifact, FoundationalBoundaryEvidenceHarnessExpansionPoint,
    FoundationalBoundaryEvidenceLineageConstructionDenial,
    FoundationalBoundaryEvidenceLineageFrontDoor, FoundationalBoundaryEvidenceLineageOutcomeKind,
    FoundationalBoundaryEvidenceLineagePartialityPosture,
    FoundationalBoundaryEvidenceLineageSubject, FoundationalBoundaryEvidenceLineageSubjectSet,
    FoundationalBoundaryEvidenceLocality, FoundationalBoundaryEvidenceLocatorContinuityAttachment,
    FoundationalBoundaryEvidenceMaterializationProfile,
    FoundationalBoundaryEvidenceMilestone7PhaseGate,
    FoundationalBoundaryEvidenceObjectContinuityAttachment,
    FoundationalBoundaryEvidencePartialLineageArtifact,
    FoundationalBoundaryEvidencePhaseGateEvidence,
    FoundationalBoundaryEvidencePlanningReceiptArtifact,
    FoundationalBoundaryEvidencePrimitiveDefinition,
    FoundationalBoundaryEvidencePrimitiveLegalityDenial,
    FoundationalBoundaryEvidenceProductionReadinessAuthority,
    FoundationalBoundaryEvidenceProductionReadinessCertified,
    FoundationalBoundaryEvidenceProductionReadinessReport,
    FoundationalBoundaryEvidenceProductionReadinessScope,
    FoundationalBoundaryEvidenceProductionTestReady,
    FoundationalBoundaryEvidenceProductionTestReadyArtifact,
    FoundationalBoundaryEvidenceProfileBasis, FoundationalBoundaryEvidencePromotedLineageArtifact,
    FoundationalBoundaryEvidencePromotionPosture, FoundationalBoundaryEvidencePropertySeed,
    FoundationalBoundaryEvidencePropertySeedEvidence,
    FoundationalBoundaryEvidenceProvenanceArtifact,
    FoundationalBoundaryEvidenceProvenanceConstructionDenial,
    FoundationalBoundaryEvidenceProvenanceFrontDoor,
    FoundationalBoundaryEvidenceProvenanceLayerKind,
    FoundationalBoundaryEvidencePublishedSupportArtifact,
    FoundationalBoundaryEvidenceReceiptBoundary, FoundationalBoundaryEvidenceReceiptFrontDoor,
    FoundationalBoundaryEvidenceReceiptKind,
    FoundationalBoundaryEvidenceReconstructedEquivalenceArtifact,
    FoundationalBoundaryEvidenceReplayDerivedLineageArtifact,
    FoundationalBoundaryEvidenceResidualDebt, FoundationalBoundaryEvidenceRestoredLineageArtifact,
    FoundationalBoundaryEvidenceRuntimeAssumption,
    FoundationalBoundaryEvidenceRuntimeNonAssumption, FoundationalBoundaryEvidenceSourceBasis,
    FoundationalBoundaryEvidenceSourceBasisKind, FoundationalBoundaryEvidenceStrategyBasis,
    FoundationalBoundaryEvidenceSupportAttachment,
    FoundationalBoundaryEvidenceSupportBasisDisclosure,
    FoundationalBoundaryEvidenceSupportCloseoutArtifact,
    FoundationalBoundaryEvidenceSupportConstructionDenial,
    FoundationalBoundaryEvidenceSupportContextAttachment,
    FoundationalBoundaryEvidenceSupportFrontDoor,
    FoundationalBoundaryEvidenceSupportReadmissionAuthority,
    FoundationalBoundaryEvidenceSupportReadmissionDenial,
    FoundationalBoundaryEvidenceSupportRecoveryPosture,
    FoundationalBoundaryEvidenceSupportResidualDebtKind,
    FoundationalBoundaryEvidenceSupportResidualDebtSet,
    FoundationalBoundaryEvidenceSupportTruthKind,
    FoundationalBoundaryEvidenceSyntheticRuntimePressure,
    FoundationalBoundaryEvidenceTransientLifecycleSupportArtifact,
    FoundationalMaterializedBoundaryEvidenceAttachmentBundle,
    SupportBasisBoundaryEvidenceAttachmentBundle,
};
pub use crate::boundary_protocol::{
    BoundaryProtocolCompatibilityWindow, BoundaryProtocolCompatibilityWindowDenial,
    BoundaryProtocolIdentity, BoundaryProtocolIdentityDenial, BoundaryProtocolUnsupportedVersion,
    BoundaryProtocolUnsupportedVersionPosture, BoundaryProtocolVersion,
    BoundaryProtocolVersionDenial,
};
pub use crate::canonicalization::{
    admit_canonical_bundle_digest_derivation, admit_canonical_bundle_digest_derivation_with_budget,
    admit_canonical_export_digest_derivation, admit_canonical_export_digest_derivation_with_budget,
    admit_canonical_sequence_digest_derivation,
    admit_canonical_sequence_digest_derivation_with_budget,
    aspect_contract_digest_preparation_basis, aspect_mask_digest_preparation_basis,
    aspect_patch_digest_preparation_basis, aspect_state_digest_preparation_basis,
    bridge_canonical_export_trust_boundary, canonical_basis_sequence_material,
    canonical_basis_value_for_aspect_value, canonical_milestone2_production_readiness_report,
    canonicalization, certify_canonical_milestone2_production_readiness, compare_canonical_basis,
    compare_canonical_exports, derive_canonical_digest,
    diagnostic_mask_locator_canonical_basis_entries, identity_canonical_basis_entries,
    locator_canonical_basis_entries, mutation_mask_locator_canonical_basis_entries,
    prepare_aspect_contract_for_canonical_basis, prepare_aspect_contract_for_digest,
    prepare_aspect_mask_for_canonical_basis, prepare_aspect_mask_for_digest,
    prepare_aspect_patch_for_canonical_basis, prepare_aspect_patch_for_digest,
    prepare_aspect_state_for_canonical_basis, prepare_aspect_state_for_digest,
    prepare_aspect_value_identity_basis, prepare_canonical_basis_bundle,
    prepare_canonical_basis_sequence, prepare_canonical_comparison,
    prepare_canonical_export_bundle, prepare_identity_for_canonical_basis,
    prepare_locator_for_canonical_basis, prepare_struct_aspect_value_identity_basis,
    projection_mask_locator_canonical_basis_entries, readmit_canonical_export_after_boundary,
    require_canonical_production_test_readiness, BoundaryBridgedCanonicalExportArtifact,
    CanonicalAspectValueIdentityBasis, CanonicalBasisBundle, CanonicalBasisConstructionDenial,
    CanonicalBasisDomain, CanonicalBasisEntry, CanonicalBasisEntryId, CanonicalBasisEntryKind,
    CanonicalBasisFrontDoor, CanonicalBasisLocus, CanonicalBasisReadinessProofs,
    CanonicalBasisReady, CanonicalBasisReadyArtifact, CanonicalBasisSequence, CanonicalBasisValue,
    CanonicalBasisVersionStep, CanonicalBundleReadinessProofs, CanonicalBundleReady,
    CanonicalBundleReadyArtifact, CanonicalCertifiedSurface, CanonicalCertifiedSurfaceEvidence,
    CanonicalComparisonBasisStep, CanonicalComparisonFrontDoor, CanonicalComparisonInput,
    CanonicalComparisonOutcome, CanonicalComparisonReadinessProofs, CanonicalComparisonReady,
    CanonicalComparisonReadyArtifact, CanonicalComparisonRightStep, CanonicalCompileFailBoundary,
    CanonicalCostCounterEvidence, CanonicalDerivedDigest, CanonicalDigestAlgorithmId,
    CanonicalDigestAlgorithmMetadata, CanonicalDigestAlgorithmSlot, CanonicalDigestAspectShapeKind,
    CanonicalDigestBasisBundle, CanonicalDigestBasisSequence, CanonicalDigestDerivationDenial,
    CanonicalDigestDerivationInput, CanonicalDigestDerivationReadinessProofs,
    CanonicalDigestDerivationReady, CanonicalDigestDerivationReadyArtifact,
    CanonicalDigestFrontDoor, CanonicalDigestInputDomain, CanonicalDigestInputEvidence,
    CanonicalDigestInputId, CanonicalDigestInputShape, CanonicalDigestInputShapeBound,
    CanonicalDigestMaskMode, CanonicalDigestMetadata, CanonicalDigestOutputShape,
    CanonicalDigestPreparationEntry, CanonicalDigestValue, CanonicalDigestWorkBudget,
    CanonicalDigestWorkEvidence, CanonicalDomainBundleDigestAlgorithmSlot,
    CanonicalDomainBundleDigestInput, CanonicalDomainCoherence, CanonicalEquivalenceBasis,
    CanonicalEquivalenceBasisDeclared, CanonicalEquivalentBasis, CanonicalExportBasisBundle,
    CanonicalExportBasisSequence, CanonicalExportBasisStep, CanonicalExportBundle,
    CanonicalExportBundleDigestAlgorithmSlot, CanonicalExportBundleDigestInput,
    CanonicalExportComparisonOutcome, CanonicalExportDebt, CanonicalExportFrontDoor,
    CanonicalExportHarnessSeed, CanonicalExportManifest, CanonicalExportManifestBound,
    CanonicalExportManifestMismatch, CanonicalExportManifestMismatchKind,
    CanonicalExportManifestRow, CanonicalExportNameStep, CanonicalExportReadinessProofs,
    CanonicalExportReadmissionAuthority, CanonicalExportReady, CanonicalExportReadyArtifact,
    CanonicalExportShapeStep, CanonicalFixtureManifestEvidence, CanonicalFloatWidth,
    CanonicalGoldenArtifactEvidence, CanonicalHarnessExpansionPoint, CanonicalIdentityInput,
    CanonicalIntegerWidth, CanonicalLocatorInput, CanonicalMilestone2PhaseGate,
    CanonicalMismatchBasis, CanonicalMismatchKind, CanonicalMismatchLociBound,
    CanonicalPhaseGateEvidence, CanonicalProducerShape, CanonicalProductionReadinessAuthority,
    CanonicalProductionReadinessCertified, CanonicalProductionReadinessReport,
    CanonicalProductionReadinessScope, CanonicalProductionTestReady,
    CanonicalProductionTestReadyArtifact, CanonicalPropertySeed, CanonicalPropertySeedEvidence,
    CanonicalReadinessFrontDoor, CanonicalResidualDebt, CanonicalRuleVersionBound,
    CanonicalRuntimeAssumption, CanonicalRuntimeNonAssumption,
    CanonicalSingleSequenceDigestAlgorithmSlot, CanonicalSingleSequenceDigestInput,
    CanonicalSyntheticRuntimePressure, CanonicalizationCost, CanonicalizationCostObserved,
    CanonicalizationFrontDoor, CanonicalizationRuleVersion, DigestPreparationMaskMode,
    DigestPreparationReady, DigestPreparationReadyAspectContract,
    DigestPreparationReadyAspectContractArtifact, DigestPreparationReadyAspectMask,
    DigestPreparationReadyAspectMaskArtifact, DigestPreparationReadyAspectPatch,
    DigestPreparationReadyAspectPatchArtifact, DigestPreparationReadyAspectState,
    DigestPreparationReadyAspectStateArtifact, Milestone2DigestReadinessNote,
};
pub use crate::compatibility::{
    compatibility, lower_json_aspect_value, lower_json_record_aspect_state, CompatibilityFrontDoor,
    JsonCompatibilityAspectInput, JsonCompatibilityFrontDoor, JsonCompatibilityLoweringDeferred,
    JsonCompatibilityLoweringDenial, JsonCompatibilityLoweringFailure,
    JsonCompatibilityLoweringOutcome, JsonCompatibilityLoweringStale,
    JsonCompatibilityRebindRequired,
};
pub use crate::diagnostics::{
    bridge_certified_diagnostic_bundle_trust_boundary, certify_current_basis_diagnostic_bundle,
    certify_diagnostic_bundle_with_source_basis,
    certify_foundational_diagnostic_milestone6_production_test_readiness,
    compare_diagnostic_explanation_bundles, compare_diagnostic_support_reports,
    diagnostic_artifact_kind_definitions, diagnostic_comparison_bundle_definition,
    diagnostic_explanation_bundle_definition, diagnostic_failure_bundle_definition,
    diagnostic_report_definition, diagnostic_summary_definition,
    diagnostic_support_report_definition, evaluate_diagnostic_materialization_legality,
    foundational_comparison_bundle_artifact_kind,
    foundational_diagnostic_boundary_artifact_subject,
    foundational_diagnostic_branch_candidate_subject,
    foundational_diagnostic_branch_discard_subject,
    foundational_diagnostic_canonical_basis_entries,
    foundational_diagnostic_certified_attachment_authority,
    foundational_diagnostic_certified_readmission_authority, foundational_diagnostic_code,
    foundational_diagnostic_commit_receipt_subject,
    foundational_diagnostic_committed_authority_subject,
    foundational_diagnostic_locator_boundary_artifact, foundational_diagnostic_locator_mismatch,
    foundational_diagnostic_locator_source, foundational_diagnostic_locator_transition,
    foundational_diagnostic_merge_verdict_subject,
    foundational_diagnostic_milestone6_readiness_report, foundational_diagnostic_scope,
    foundational_explanation_bundle_artifact_kind, foundational_failure_bundle_artifact_kind,
    foundational_report_artifact_kind, foundational_summary_artifact_kind,
    foundational_support_report_artifact_kind, materialize_diagnostic_explanation_bundle,
    materialize_diagnostic_support_report, plan_diagnostic_explanation_bundle,
    plan_diagnostic_support_report, prepare_diagnostic_explanation_bundle_for_canonical_basis,
    prepare_diagnostic_support_report_for_canonical_basis,
    readmit_certified_diagnostic_bundle_after_boundary,
    require_foundational_diagnostic_milestone6_production_test_readiness,
    sort_foundational_diagnostic_rows, BoundaryBridgedCertifiedDiagnosticBundle,
    FoundationalCertifiedDiagnosticBundle, FoundationalCertifiedDiagnosticPayload,
    FoundationalCertifiedDiagnosticProvenanceHook, FoundationalCertifiedDiagnosticSource,
    FoundationalCertifiedDiagnosticSourceKind, FoundationalComparisonBundleArtifactKind,
    FoundationalDiagnosticAbsenceCause, FoundationalDiagnosticAdoptionShapedFollowthrough,
    FoundationalDiagnosticArtifactKind, FoundationalDiagnosticArtifactKindDefinition,
    FoundationalDiagnosticArtifactKindMarker, FoundationalDiagnosticAssemblyDebt,
    FoundationalDiagnosticAssemblyDebtClass, FoundationalDiagnosticAvailability,
    FoundationalDiagnosticBreachClass, FoundationalDiagnosticCanonicalGoldenArtifact,
    FoundationalDiagnosticCanonicalGoldenArtifactEvidence, FoundationalDiagnosticCertified,
    FoundationalDiagnosticCertifiedAttachmentAuthority,
    FoundationalDiagnosticCertifiedAttachmentDenial, FoundationalDiagnosticCertifiedCoverageClass,
    FoundationalDiagnosticCertifiedCoverageDenial, FoundationalDiagnosticCertifiedPhase,
    FoundationalDiagnosticCertifiedReadmissionAuthority, FoundationalDiagnosticCertifiedSurface,
    FoundationalDiagnosticCertifiedSurfaceEvidence, FoundationalDiagnosticCodeId,
    FoundationalDiagnosticComparisonBundle, FoundationalDiagnosticComparisonDenial,
    FoundationalDiagnosticComparisonRow, FoundationalDiagnosticCompileFailBoundary,
    FoundationalDiagnosticCompileFailEvidence, FoundationalDiagnosticCounterSnapshot,
    FoundationalDiagnosticCoverageFamilyStatus, FoundationalDiagnosticCoverageMatrix,
    FoundationalDiagnosticDecisionRow, FoundationalDiagnosticDeliveryClass,
    FoundationalDiagnosticDenialClass, FoundationalDiagnosticEvidencePosture,
    FoundationalDiagnosticExplanationBundle, FoundationalDiagnosticExplanationInput,
    FoundationalDiagnosticFailureRow, FoundationalDiagnosticGapClass,
    FoundationalDiagnosticGapClosurePosture, FoundationalDiagnosticGapTarget,
    FoundationalDiagnosticHarnessExpansionEvidence, FoundationalDiagnosticHarnessExpansionPoint,
    FoundationalDiagnosticLocalityClaim, FoundationalDiagnosticLocator,
    FoundationalDiagnosticMaterializationDenial,
    FoundationalDiagnosticMaterializationLegalityDenial, FoundationalDiagnosticMaterializationPlan,
    FoundationalDiagnosticMilestone6PhaseGate, FoundationalDiagnosticNamedGap,
    FoundationalDiagnosticOutcomeKind, FoundationalDiagnosticPartiality,
    FoundationalDiagnosticPhaseGateEvidence, FoundationalDiagnosticPrimitiveConstructionDenial,
    FoundationalDiagnosticProductionReadinessAuthority,
    FoundationalDiagnosticProductionReadinessCertified,
    FoundationalDiagnosticProductionReadinessReport,
    FoundationalDiagnosticProductionReadinessScope, FoundationalDiagnosticProductionTestReady,
    FoundationalDiagnosticProductionTestReadyArtifact, FoundationalDiagnosticPropertySeed,
    FoundationalDiagnosticPropertySeedEvidence, FoundationalDiagnosticProvenanceReadyRow,
    FoundationalDiagnosticResidualDebt, FoundationalDiagnosticRow, FoundationalDiagnosticRowFamily,
    FoundationalDiagnosticRuntimeAdoptionFailurePressure, FoundationalDiagnosticRuntimeAssumption,
    FoundationalDiagnosticRuntimeNonAssumption, FoundationalDiagnosticScopeId,
    FoundationalDiagnosticSemanticLabelSet, FoundationalDiagnosticSeverity,
    FoundationalDiagnosticSubject, FoundationalDiagnosticSupportClaimStrength,
    FoundationalDiagnosticSupportEvidencePosture, FoundationalDiagnosticSupportInput,
    FoundationalDiagnosticSupportReport, FoundationalDiagnosticSupportRow,
    FoundationalDiagnosticSurfaceAvailability, FoundationalDiagnosticSyntheticPressureEvidence,
    FoundationalDiagnosticSyntheticRuntimePressure, FoundationalDiagnosticWORTHProofApi,
    FoundationalDiagnosticWORTHProofApiEvidence, FoundationalDiagnosticWORTHProofForbiddenSurface,
    FoundationalDiagnosticWORTHProofSurface, FoundationalDiagnosticWidenedFalloutPosture,
    FoundationalExplanationBundleArtifactKind, FoundationalFailureBundleArtifactKind,
    FoundationalReportArtifactKind, FoundationalSummaryArtifactKind,
    FoundationalSupportReportArtifactKind,
};
pub use crate::identities::{
    admit_foundational_authority_identity, admit_foundational_external_identity_token,
    admitted_foundational_identity_value, derive_foundational_digest_identity_evidence,
    project_foundational_identity, readmit_foundational_authority_identity,
    readmit_revalidated_foundational_authority_identity, revalidated_foundational_identity_value,
    BoundaryArtifactId, BoundaryEpoch, BoundaryHandle, CanonicalDigestId, EquivalenceBasisId,
    FoundationalAdmittedIdentityValue, FoundationalAuthorityIdentity,
    FoundationalBoundaryBridgedIdentity, FoundationalDigestIdentityEvidence,
    FoundationalExternalIdentityToken, FoundationalIdentityBasis,
    FoundationalIdentityDigestDerivationEvidence, FoundationalIdentityKind,
    FoundationalIdentityProjectionEvidence, FoundationalProjectionIdentity,
    FoundationalRevalidatedIdentityValue,
};
pub use crate::locators::{
    AspectContractLocator, AspectFieldLocator, AspectLocator, AspectMaskLocator,
    AspectValueLocator, BoundaryArtifactField, BoundaryArtifactLocator, BoundaryMismatchLocator,
    BoundarySourceLocator, FoundationalBranchCandidateLocator, FoundationalCommitParentageLocator,
    FoundationalCommittedDeltaLocator, FoundationalMergeConflictLocator,
    FoundationalMergeScopeLocator, FoundationalSelectedAspectScopeLocator,
    FoundationalSelectedNodeScopeLocator, FoundationalTransitionLocator, LocatorAuthority,
};
pub use crate::performance::{
    attach_counter_backed_performance_receipt, attach_performance_bundle,
    attach_policy_admission_receipt, bridge_certified_performance_bundle_trust_boundary,
    certify_foundational_performance_milestone8_production_test_readiness,
    certify_hot_path_counter_backed_performance_receipt,
    certify_support_expansion_performance_report, compare_performance_bundles,
    counter_backed_performance_receipt, evaluate_performance_primitive_legality,
    foundational_performance_access_pattern_definitions,
    foundational_performance_allocation_definitions,
    foundational_performance_attachment_target_kind_definitions,
    foundational_performance_boundary_definitions,
    foundational_performance_breadth_locality_definitions,
    foundational_performance_budget_definitions,
    foundational_performance_certified_attachment_authority,
    foundational_performance_certified_readmission_authority,
    foundational_performance_evidence_strength_definitions,
    foundational_performance_execution_temperature_definitions,
    foundational_performance_fallback_debt_definitions,
    foundational_performance_freshness_retention_definitions,
    foundational_performance_layout_intent_definitions,
    foundational_performance_milestone8_readiness_report,
    foundational_performance_work_class_definitions, performance, performance_bundle,
    plan_performance_report, policy_admission_receipt,
    prepare_counter_backed_performance_receipt_for_canonical_basis,
    prepare_materialized_performance_report_for_canonical_basis,
    readmit_certified_performance_bundle_after_boundary,
    require_foundational_performance_milestone8_production_test_readiness,
    BoundaryBridgedCertifiedPerformanceBundle, FoundationalAttachedCounterBackedPerformanceReceipt,
    FoundationalAttachedPerformanceBundle, FoundationalAttachedPolicyAdmissionReceipt,
    FoundationalAuthoritativePerformanceClaim, FoundationalAuthoritativePerformanceClaimBuilder,
    FoundationalCertifiedPerformanceAttachmentDenial, FoundationalCertifiedPerformanceBundle,
    FoundationalCertifiedPerformanceClass, FoundationalCertifiedPerformancePayload,
    FoundationalCertifiedPerformanceSource, FoundationalCertifiedPerformanceSourceDigest,
    FoundationalCertifiedPerformanceSourceKind, FoundationalCounterBackedPerformanceReceipt,
    FoundationalCounterBackedPerformanceReceiptBuilder,
    FoundationalCounterBackedPerformanceReceiptConstructionDenial,
    FoundationalLayoutAnnotatedClaim, FoundationalLayoutAnnotatedClaimConstructionDenial,
    FoundationalLayoutIntentClaim, FoundationalMaterializedPerformanceReport,
    FoundationalPerformanceAccessPatternDefinition, FoundationalPerformanceAccessPatternPosture,
    FoundationalPerformanceAllocationDefinition, FoundationalPerformanceAllocationPosture,
    FoundationalPerformanceAttachmentConstructionDenial, FoundationalPerformanceAttachmentDenial,
    FoundationalPerformanceAttachmentTargetKind, FoundationalPerformanceBoundary,
    FoundationalPerformanceBoundaryDefinition, FoundationalPerformanceBreadthLocalityDefinition,
    FoundationalPerformanceBreadthLocalityPosture, FoundationalPerformanceBudgetDecision,
    FoundationalPerformanceBudgetDefinition, FoundationalPerformanceBudgetKind,
    FoundationalPerformanceBundle, FoundationalPerformanceBundleBuilder,
    FoundationalPerformanceBundleConstructionDenial, FoundationalPerformanceCertified,
    FoundationalPerformanceCertifiedAttachmentAuthority, FoundationalPerformanceCertifiedPhase,
    FoundationalPerformanceCertifiedReadmissionAuthority, FoundationalPerformanceCertifiedSurface,
    FoundationalPerformanceCertifiedSurfaceEvidence,
    FoundationalPerformanceClaimAuthoringFrontDoor, FoundationalPerformanceClaimConstructionDenial,
    FoundationalPerformanceClaimSurface, FoundationalPerformanceComparison,
    FoundationalPerformanceCompileFailBoundary, FoundationalPerformanceContractName,
    FoundationalPerformanceCounterName, FoundationalPerformanceCounterRow,
    FoundationalPerformanceCounterSpec, FoundationalPerformanceEvidenceStrength,
    FoundationalPerformanceEvidenceStrengthDefinition, FoundationalPerformanceExecutionTemperature,
    FoundationalPerformanceExecutionTemperatureDefinition,
    FoundationalPerformanceFallbackDebtDefinition, FoundationalPerformanceFallbackDebtPosture,
    FoundationalPerformanceFreshnessRetentionDefinition,
    FoundationalPerformanceFreshnessRetentionPosture, FoundationalPerformanceFrontDoor,
    FoundationalPerformanceHarnessExpansionPoint, FoundationalPerformanceLayoutIntent,
    FoundationalPerformanceLayoutIntentDefinition, FoundationalPerformanceMilestone8PhaseGate,
    FoundationalPerformanceMismatch, FoundationalPerformanceObservationContext,
    FoundationalPerformancePhaseGateEvidence, FoundationalPerformancePrimitiveDefinition,
    FoundationalPerformancePrimitiveLegalityDenial,
    FoundationalPerformanceProductionReadinessAuthority,
    FoundationalPerformanceProductionReadinessCertified,
    FoundationalPerformanceProductionReadinessReport,
    FoundationalPerformanceProductionReadinessScope, FoundationalPerformanceProductionTestReady,
    FoundationalPerformanceProductionTestReadyArtifact,
    FoundationalPerformancePublicSurfaceDocumentationCoverage,
    FoundationalPerformanceReportMaterializationBoundary, FoundationalPerformanceReportPlan,
    FoundationalPerformanceReportRequest, FoundationalPerformanceReportSection,
    FoundationalPerformanceReportSectionDecision,
    FoundationalPerformanceReportSectionDecisionCause, FoundationalPerformanceResidualDebt,
    FoundationalPerformanceRuntimeAdoptionPressure,
    FoundationalPerformanceRuntimeAdoptionPressureEvidence,
    FoundationalPerformanceRuntimeAssumption, FoundationalPerformanceRuntimeNonAssumption,
    FoundationalPerformanceSupportingEvidenceCode, FoundationalPerformanceSupportingEvidenceRow,
    FoundationalPerformanceSyntheticRuntimePressure, FoundationalPerformanceWORTHProofApi,
    FoundationalPerformanceWORTHProofForbiddenSurface, FoundationalPerformanceWORTHProofSurface,
    FoundationalPerformanceWorkClass, FoundationalPerformanceWorkClassDefinition,
    FoundationalPolicyAdmissionPerformanceClaim,
    FoundationalPolicyAdmissionPerformanceClaimBuilder, FoundationalPolicyAdmissionReceipt,
    FoundationalPolicyAdmissionReceiptBuilder,
    FoundationalPolicyAdmissionReceiptConstructionDenial,
    FoundationalReplayMaterializationPerformanceClaim,
    FoundationalReplayMaterializationPerformanceClaimBuilder,
    FoundationalSupportDerivedPerformanceClaim, FoundationalSupportDerivedPerformanceClaimBuilder,
};
pub use crate::profiles::{
    admit_requested_foundational_profile, admit_requested_foundational_profile_with_resolutions,
    attach_boundary_profiled_artifact, attach_proof_bearing_profiled_artifact,
    attach_support_profiled_artifact, boundary_artifact_surface_inventory,
    bridge_evidence_backed_proof_bearing_artifact_trust_boundary,
    bridge_production_certified_proof_bearing_artifact_trust_boundary,
    certify_evidence_backed_proof_bearing_artifact,
    certify_foundational_profile_milestone3_production_test_readiness,
    certify_production_certified_proof_bearing_artifact,
    classify_foundational_profile_compatibility, compare_foundational_profile_identities,
    compare_foundational_profiles, derive_foundational_profile_identity,
    foundational_profile_applicability, foundational_profile_canonical_basis_entries,
    foundational_profile_certification_authority, foundational_profile_certification_proof_lane,
    foundational_profile_certification_readmission_authority,
    foundational_profile_milestone10_readiness_report,
    foundational_profile_milestone3_readiness_report, foundational_profile_progression_authority,
    materialize_admitted_foundational_profile,
    materialize_admitted_foundational_profile_with_resolutions,
    plan_foundational_profile_materialization,
    plan_foundational_profile_materialization_with_elision,
    plan_selected_foundational_profile_materialization,
    plan_selected_foundational_profile_materialization_with_disposition,
    prepare_admitted_foundational_profile_for_canonical_basis, profiles,
    proof_bearing_artifact_surface_inventory,
    readmit_evidence_backed_proof_bearing_artifact_after_boundary,
    readmit_production_certified_proof_bearing_artifact_after_boundary,
    request_foundational_profile_set,
    require_foundational_profile_milestone3_production_test_readiness,
    support_artifact_surface_inventory, AdmissionReadinessProfile,
    AdmittedFoundationalProfileArtifact, AdmittedFoundationalProfilePhase,
    AdmittedFoundationalProfileSet, BoundaryArtifactTarget,
    BoundaryBridgedEvidenceBackedCertifiedProofBearingArtifact,
    BoundaryBridgedProductionCertifiedProofBearingArtifact, BoundaryProfiledArtifact,
    CertificationPostureProfile, CompatibilityPostureProfile, DiagnosticRichnessProfile,
    EvidenceBackedCertifiedProofBearingArtifact, ExecutionObjectiveProfile,
    FoundationalDescriptiveElisionProfile, FoundationalDescriptiveSurface,
    FoundationalMaterializationCost, FoundationalMaterializationPlanningDenial,
    FoundationalObservationActivationScope, FoundationalObservationDisposition,
    FoundationalProfileApplicability, FoundationalProfileAttachmentDenial,
    FoundationalProfileAttachmentFrontDoor, FoundationalProfileAttachmentOutcome,
    FoundationalProfileAttachmentTargetKind, FoundationalProfileAttachmentTargetMarker,
    FoundationalProfileCertificationAuthority, FoundationalProfileCertificationDenial,
    FoundationalProfileCertificationFrontDoor, FoundationalProfileCertificationOutcome,
    FoundationalProfileCertificationProofLane,
    FoundationalProfileCertificationReadmissionAuthority, FoundationalProfileCertifiedSurface,
    FoundationalProfileCertifiedSurfaceEvidence, FoundationalProfileCompatibilityClass,
    FoundationalProfileCompileFailBoundary, FoundationalProfileCompositionDenial,
    FoundationalProfileDecisionKind, FoundationalProfileDifferenceReport,
    FoundationalProfileFamily, FoundationalProfileFrontDoorConstructionDenial,
    FoundationalProfileFrontDoorFamily, FoundationalProfileIdentity,
    FoundationalProfileIdentityDenial, FoundationalProfileMaterializationFrontDoor,
    FoundationalProfileMaterializationPlan, FoundationalProfileMilestone10PhaseGate,
    FoundationalProfileMilestone10ReadinessReport, FoundationalProfileMilestone3PhaseGate,
    FoundationalProfileNarrowingKind, FoundationalProfileNarrowingRecord,
    FoundationalProfilePhaseGateEvidence, FoundationalProfileProductionReadinessAuthority,
    FoundationalProfileProductionReadinessCertified, FoundationalProfileProductionReadinessReport,
    FoundationalProfileProductionReadinessScope, FoundationalProfileProductionTestReady,
    FoundationalProfileProductionTestReadyArtifact, FoundationalProfileProgressionAuthority,
    FoundationalProfileProgressionDeferred, FoundationalProfileProgressionDenial,
    FoundationalProfileProgressionFailure, FoundationalProfileProgressionFrontDoor,
    FoundationalProfileProgressionOutcome, FoundationalProfileProgressionRebindRequired,
    FoundationalProfileProgressionStale, FoundationalProfileResidualDebt,
    FoundationalProfileResolutionFamily, FoundationalProfileResolutionLedger,
    FoundationalProfileResolutionLedgerDenial, FoundationalProfileResolutionRecord,
    FoundationalProfileResolutionRelation, FoundationalProfileRuntimeAssumption,
    FoundationalProfileRuntimeNonAssumption, FoundationalProfileSet,
    FoundationalProfileSetFrontDoor, FoundationalProfileSetInput,
    FoundationalProfileSyntheticRuntimePressure, FoundationalProfileWORTHProofApi,
    FoundationalProfileWORTHProofForbiddenSurface, FoundationalProfileWORTHProofSurface,
    FoundationalProfiledArtifact, FoundationalSurfaceAbsenceCause,
    FoundationalSurfaceAvailabilityDecision, FoundationalTargetSurfaceInventory,
    MaterializedBoundaryArtifactStep, MaterializedFoundationalProfileArtifact,
    MaterializedFoundationalProfilePhase, MaterializedFoundationalProfileSet,
    MaterializedProofBearingArtifactStep, MaterializedSupportArtifactStep,
    ObservationActivationProfile, ProductionCertifiedProofBearingArtifact, ProfilesFrontDoor,
    ProofBearingArtifactTarget, ProofBearingProfiledArtifact, RequestedFoundationalProfileArtifact,
    RequestedFoundationalProfilePhase, RequestedFoundationalProfileSet, RetentionDeliveryProfile,
    SupportArtifactTarget, SupportPostureProfile, SupportProfiledArtifact,
};
pub use crate::transitions::{
    admit_current_basis_commit_receipt, admit_current_basis_committed_authority,
    attach_boundary_profiled_branch_candidate, attach_boundary_profiled_staged_branch,
    attach_proof_bearing_profiled_commit_receipt,
    attach_proof_bearing_profiled_committed_authority, attach_support_profiled_merge_verdict,
    bridge_current_basis_commit_receipt_trust_boundary,
    bridge_current_basis_committed_authority_trust_boundary,
    certify_foundational_transition_milestone5_production_test_readiness,
    certify_foundational_transition_milestone9_scoped_merge_production_test_readiness,
    foundational_branch_candidate, foundational_branch_local_state_definitions,
    foundational_commit_receipt_issuance, foundational_committed_authority_admission,
    foundational_merge, foundational_transition_canonical_basis_entries,
    foundational_transition_current_basis_authority,
    foundational_transition_current_basis_readmission_authority,
    foundational_transition_milestone5_readiness_report,
    foundational_transition_milestone9_scoped_merge_readiness_report,
    prepare_admitted_merge_scope_for_canonical_basis, prepare_branch_candidate_for_canonical_basis,
    prepare_commit_receipt_for_canonical_basis, prepare_committed_authority_for_canonical_basis,
    prepare_merge_scope_for_canonical_basis, prepare_merge_verdict_for_canonical_basis,
    prepare_scoped_merge_denial_for_canonical_basis, prepare_scoped_merge_diagnostic_explanation,
    prepare_scoped_merge_unavailable_for_canonical_basis,
    prepare_staged_branch_for_canonical_basis, readmit_current_basis_commit_receipt_after_boundary,
    readmit_current_basis_committed_authority_after_boundary,
    require_foundational_transition_milestone5_production_test_readiness,
    require_foundational_transition_milestone9_scoped_merge_production_test_readiness,
    BoundaryBridgedCurrentBasisCommitReceiptArtifact,
    BoundaryBridgedCurrentBasisCommittedAuthorityArtifact, CurrentBasisCommitReceiptArtifact,
    CurrentBasisCommittedAuthorityArtifact, CurrentBasisTransitionPhase,
    FoundationalAdmittedMergeScopeEvidence, FoundationalAuthorityTransitionClass,
    FoundationalAuthorityTransitionDenial, FoundationalAuthorityTransitionOutcomeKind,
    FoundationalBranchBasisDrift, FoundationalBranchBasisDriftKind,
    FoundationalBranchCandidateArtifact, FoundationalBranchCandidateBuilder,
    FoundationalBranchCandidateComparisonBasis, FoundationalBranchCandidateForkBasis,
    FoundationalBranchCandidateForkObservationBasis, FoundationalBranchCandidateId,
    FoundationalBranchCandidateObservationBasis, FoundationalBranchCloseoutCause,
    FoundationalBranchComparisonBasis, FoundationalBranchDiscardReceipt,
    FoundationalBranchForkBasis, FoundationalBranchId, FoundationalBranchIdConstructionDenial,
    FoundationalBranchLocalConstructionDenial, FoundationalBranchLocalStateDefinition,
    FoundationalBranchLocalStateKind, FoundationalBranchReferenceGeneration,
    FoundationalBranchReferenceGenerationAdvanceDenial, FoundationalBranchReferenceMismatch,
    FoundationalBranchReferenceMismatchAxis, FoundationalBranchReferenceMovement,
    FoundationalBranchReferenceMovementKind, FoundationalBranchReferenceObservation,
    FoundationalBranchTarget, FoundationalBranchTargetBasis, FoundationalBranchTargetEncoding,
    FoundationalBranchTargetEncodingConstructionDenial, FoundationalCommitDeltaSummary,
    FoundationalCommitId, FoundationalCommitParentBasis, FoundationalCommitParentage,
    FoundationalCommitReceiptArtifact, FoundationalCommitReceiptIdentity,
    FoundationalCommitReceiptIssuance, FoundationalCommitReceiptIssuanceBasis,
    FoundationalCommitReceiptIssuanceDenial, FoundationalCommitReceiptPhase,
    FoundationalCommittedAuthorityAdmission, FoundationalCommittedAuthorityAdmissionBasis,
    FoundationalCommittedAuthorityArtifact, FoundationalCommittedAuthorityConstructionDenial,
    FoundationalCommittedAuthorityInput, FoundationalCommittedAuthorityPhase,
    FoundationalCommittedDeltaLocus, FoundationalDeniedScopeLocus,
    FoundationalMergeAdmissionDeferred, FoundationalMergeAdmissionDenial,
    FoundationalMergeAdmissionFailure, FoundationalMergeAdmissionOutcome,
    FoundationalMergeAdmissionRebindRequired, FoundationalMergeAncestryBasis,
    FoundationalMergeBaseSelectionBasis, FoundationalMergeBasis, FoundationalMergeBuilder,
    FoundationalMergeCandidate, FoundationalMergeConflictLocus,
    FoundationalMergeConstructionDenial, FoundationalMergeIntent, FoundationalMergeScope,
    FoundationalMergeScopeFamily, FoundationalMergeStructuralSummary, FoundationalMergeVerdict,
    FoundationalMergeVerdictKind, FoundationalNoOpCause, FoundationalNonAuthoritativeResidueReport,
    FoundationalScopeAdmissionBasis, FoundationalScopeBreadthSummary,
    FoundationalScopedMergeDenialEvidence, FoundationalScopedMergeDenialKind,
    FoundationalScopedMergeDiagnosticInput, FoundationalScopedMergeUnavailableOutcomeCategory,
    FoundationalScopedMergeUnavailablePosture, FoundationalScopedMergeUnavailableReason,
    FoundationalSelectedAspectLocus, FoundationalSelectedAspectRequestEntry,
    FoundationalSelectedNodeLocus, FoundationalSelectedScopeLocus,
    FoundationalSelectedScopeNoOpCause, FoundationalSelectedScopeNoOpEvidence,
    FoundationalSkippedOutOfScopeEvidence, FoundationalStagedBranchArtifact,
    FoundationalStrategyBasis, FoundationalTransitionBasisFamily,
    FoundationalTransitionBasisIdentity, FoundationalTransitionBasisVersion,
    FoundationalTransitionBundle, FoundationalTransitionBundleBuilder,
    FoundationalTransitionBundleMaterializationCost, FoundationalTransitionCertifiedSurface,
    FoundationalTransitionCertifiedSurfaceEvidence, FoundationalTransitionCompileFailBoundary,
    FoundationalTransitionCompileFailEvidence, FoundationalTransitionCorrespondenceBasis,
    FoundationalTransitionCurrentBasisAuthority,
    FoundationalTransitionCurrentBasisReadmissionAuthority, FoundationalTransitionIssuanceCause,
    FoundationalTransitionMilestone5PhaseGate, FoundationalTransitionPhaseGateEvidence,
    FoundationalTransitionProductionReadinessAuthority,
    FoundationalTransitionProductionReadinessCertified,
    FoundationalTransitionProductionReadinessReport,
    FoundationalTransitionProductionReadinessScope, FoundationalTransitionProductionTestReady,
    FoundationalTransitionProductionTestReadyArtifact, FoundationalTransitionProvenanceRow,
    FoundationalTransitionRemapBasis, FoundationalTransitionResidualDebt,
    FoundationalTransitionRuntimeAssumption, FoundationalTransitionRuntimeNonAssumption,
    FoundationalTransitionStrategyContractBasis, FoundationalTransitionStrategyDescriptorDigest,
    FoundationalTransitionStrategyFamily, FoundationalTransitionStrategyId,
    FoundationalTransitionStrategyIdentity, FoundationalTransitionStrategyOwnershipClass,
    FoundationalTransitionStrategySemanticName, FoundationalTransitionStrategyVersion,
    FoundationalTransitionSyntheticPressureEvidence,
    FoundationalTransitionSyntheticRuntimePressure, FoundationalTransitionWORTHProofApi,
    FoundationalTransitionWORTHProofApiEvidence, FoundationalTransitionWORTHProofForbiddenSurface,
    FoundationalTransitionWORTHProofSurface,
};
pub use crate::values::{
    decode_canonical_text_hex, encode_canonical_text_hex, AspectValue, CanonicalBigInt,
    CanonicalDate, CanonicalDecimal, CanonicalF32, CanonicalF64, CanonicalRational,
    CanonicalString, CanonicalTime, CanonicalTimestamp, CanonicalTimestampTz, ContentRefId,
    EntityId, Generation, InternedString, LocalSlot, PartitionId, ScalarAspectType, Symbol,
};

pub use crate::responsibilities::{foundational_responsibilities, ResponsibilityArea};
