//! Mapping contracts for causes not generated by these public request probes.
//! Child policy admission precedes a valid request; accounting,
//! and malformed builder extrema are guarded at Relational's owning boundary.
use super::super::*;
use crate::domain_computation::primary_graph::application_attempt::{
    provider_compare_denial::preparation_outcome::application_outcome,
    WorthQueryApplicationCommitDenialKind as Kind, WorthQueryApplicationCommitOutcome as Outcome,
};
use crate::domain_computation::primary_graph::{
    WorthQueryManagedComputationResourceDenial as Resource, WorthQueryMemoryLimitLevel as Level,
};
use worth_relational::facade::{
    errors::{ErrorContext, ErrorOperation, RelationalSubsystem},
    transactions::{
        CommitExecutionDenial, CommitExecutionDenialKind, CommitLog,
        RelationalExecutionDenialCause as Cause, TransactionCommitError,
    },
};

fn assert_kind(cause: Cause, expected: Kind) {
    let stop = transaction_commit_stop(TransactionCommitError::Execution {
        denial: CommitExecutionDenial {
            kind: CommitExecutionDenialKind::Cause(cause),
            partition_identity: Some(7),
        },
        context: ErrorContext::new(RelationalSubsystem::Transaction, ErrorOperation::Commit),
        commit_log: CommitLog::new(),
    });
    let Outcome::Denied(denial) = application_outcome(stop) else {
        panic!("lost typed application denial")
    };
    assert_eq!(denial.kind(), expected);
}

macro_rules! resource_contract {
    ($name:ident, $cause:expr, $resource:expr) => {
        #[test]
        fn $name() {
            assert_kind(
                $cause,
                Kind::ExecutionResource {
                    denial: $resource,
                    partition_identity: Some(7),
                    policy_ancestor: None,
                },
            );
        }
    };
}
resource_contract!(
    worker_limit,
    Cause::WorkerLimitExceedsParent,
    Resource::WorkerLimit
);
resource_contract!(
    memory_limit,
    Cause::MemoryLimitExceedsParent,
    Resource::PolicyMemoryLimit
);
resource_contract!(
    work_limit,
    Cause::WorkLimitExceedsParent,
    Resource::WorkLimit
);
resource_contract!(
    charged_overflow,
    Cause::ChargedBytesOverflow,
    Resource::ChargedBytesOverflow
);
resource_contract!(
    equivalence,
    Cause::EquivalenceContractUnavailable,
    Resource::EquivalenceContractUnavailable
);
resource_contract!(
    counter_overflow,
    Cause::WorkCounterOverflow,
    Resource::WorkCounterOverflow
);
resource_contract!(
    map_memory_overflow,
    Cause::MemoryOverflow,
    Resource::CapacityOverflow
);
resource_contract!(
    declared_memory,
    Cause::DeclaredMemoryExhausted {
        requested: 31,
        admitted: 17
    },
    Resource::MemoryLimit {
        requested: 31,
        admitted: 17,
        level: Level::Declared
    }
);

#[test]
fn packet_panic() {
    assert_kind(
        Cause::WorkerFailed,
        Kind::ExecutionWorkerPanicked {
            partition_identity: Some(7),
        },
    );
}
#[test]
fn malformed_identity() {
    assert_kind(
        Cause::ExpectedIdentitiesNotCanonical,
        Kind::ExecutionIdentitiesNotCanonical {
            partition_identity: Some(7),
        },
    );
}
