//! Typed intent meaning exposed to product composition roots.

pub use worth_ui_runtime::facade::intent::{
    FrozenIntentDefinitionCapabilities, IntentDefinitionDescriptor, UiAdmittedIntent,
    UiApplicationEffectDestination, UiConfirmedIntentCandidate, UiInoperableIntentCandidate,
    UiIntent, UiIntentAcceptedInteractions, UiIntentAdmissionCancellationReason,
    UiIntentAdmissionCost, UiIntentAdmissionDecision, UiIntentAdmissionMetrics,
    UiIntentAdmissionSettlementPosture, UiIntentAdmissionSettlementReceipt,
    UiIntentAdmissionShutdownReport, UiIntentAdmissionSlotIdentity, UiIntentAdmissionStop,
    UiIntentAdmissionStopReason, UiIntentAffinityPosture, UiIntentApplicationFact,
    UiIntentApplicationFactIdentityError, UiIntentApplicationFactRegistrationError,
    UiIntentApplicationFactRevision, UiIntentApplicationFactUpdateDenial,
    UiIntentApplicationFactUpdateReceipt, UiIntentAttemptLineage, UiIntentBoolean,
    UiIntentCatalogMetrics, UiIntentCatalogPreparationDenial, UiIntentConcurrencyScope,
    UiIntentConfirmationCancellationReason, UiIntentConfirmationChallenge,
    UiIntentConfirmationContinuation, UiIntentConfirmationContract,
    UiIntentConfirmationContractIdentityError, UiIntentConfirmationIssueOutcome,
    UiIntentConfirmationLookupCost, UiIntentConfirmationMetrics, UiIntentConfirmationObservation,
    UiIntentConfirmationPosture, UiIntentConfirmationRouteBinding,
    UiIntentConfirmationSettlementReceipt, UiIntentConfirmationShutdownReport,
    UiIntentConfirmationSlotIdentity, UiIntentConfirmationStop, UiIntentConfirmationStopReason,
    UiIntentConfirmationTimeBasisKind, UiIntentConsequenceCompletionReceipt,
    UiIntentConsequenceContract, UiIntentConsequenceHandle,
    UiIntentConsequencePublicationCompletion, UiIntentConsequencePublicationOutcome,
    UiIntentConsequencePublicationReceipt, UiIntentConsequencePublicationRecovery,
    UiIntentConsequenceRecovery, UiIntentConsequenceStop, UiIntentConsequenceStopReason,
    UiIntentDeclaration, UiIntentDeclarationConcurrencyBound,
    UiIntentDeclarationConcurrencyMissing, UiIntentDeclarationConfirmationBound,
    UiIntentDeclarationConfirmationMissing, UiIntentDeclarationConsequencesBound,
    UiIntentDeclarationConsequencesMissing, UiIntentDeclarationConstructionError,
    UiIntentDeclarationIdentity, UiIntentDeclarationOperabilityBound,
    UiIntentDeclarationOperabilityMissing, UiIntentDefinition, UiIntentDefinitionDestination,
    UiIntentDefinitionRegistrationError, UiIntentDraftInputRevision,
    UiIntentExecutionAdvanceOutcome, UiIntentExecutionAdvanceReport, UiIntentExecutionAdvanceStop,
    UiIntentExecutionAttempt, UiIntentExecutionAttemptIdentity,
    UiIntentExecutionBindingPreparationDenial, UiIntentExecutionCancellationContext,
    UiIntentExecutionCancellationReason, UiIntentExecutionClockReading,
    UiIntentExecutionCurrentnessStop, UiIntentExecutionDeadline, UiIntentExecutionDeadlineBasis,
    UiIntentExecutionDeadlineOverflow, UiIntentExecutionDestination,
    UiIntentExecutionDispatchOutcome, UiIntentExecutionDispatchReceipt,
    UiIntentExecutionDispatchStop, UiIntentExecutionDispatchStopReason,
    UiIntentExecutionIdempotencyIdentity, UiIntentExecutionPollContext, UiIntentExecutionProvider,
    UiIntentExecutionRecovery, UiIntentExecutionRequest, UiIntentExecutionReservationDenial,
    UiIntentExecutionShutdownReport, UiIntentExecutionTransition,
    UiIntentExecutionTransitionPosture, UiIntentId, UiIntentInoperableCause,
    UiIntentInoperableCauseIter, UiIntentInputBasisReceipt, UiIntentInputOwnerRevision,
    UiIntentInteractionPayloadSourceKind, UiIntentMutabilityPosture, UiIntentMutabilitySource,
    UiIntentOccupancyPosture, UiIntentOperabilityContract,
    UiIntentOperabilityContractIdentityError, UiIntentOperabilityCost, UiIntentOperabilityDecision,
    UiIntentOperabilityDependencyAxis, UiIntentOperabilityOutcome, UiIntentOperabilityProof,
    UiIntentPartialEffect, UiIntentPayload, UiIntentPayloadField, UiIntentPayloadFieldDescriptor,
    UiIntentPayloadFieldKind, UiIntentPayloadFieldSet, UiIntentPayloadProjection,
    UiIntentPayloadProjectionCost, UiIntentPayloadProjectionViolation,
    UiIntentPayloadSchemaViolation, UiIntentPayloadSource, UiIntentPayloadStop,
    UiIntentPayloadValueKind, UiIntentPolicyPosture, UiIntentPolicySource,
    UiIntentProductConsequenceFamilies, UiIntentProductConsequences, UiIntentProductOutcome,
    UiIntentProviderPoll, UiIntentProviderRecoveryPoll, UiIntentProviderSettlement,
    UiIntentProviderStart, UiIntentProviderStop, UiIntentProviderVersion,
    UiIntentQueryInputRevision, UiIntentReadinessPosture, UiIntentReadinessSource,
    UiIntentRecoveryHandle, UiIntentRecoveryProgressOutcome, UiIntentRecoveryProgressPosture,
    UiIntentRecoveryProgressReceipt, UiIntentRecoveryProgressStop, UiIntentResourceCensus,
    UiIntentRouteBinding, UiIntentRouteResolution, UiIntentRouteResolutionStop,
    UiIntentRouteSource, UiIntentRuntimeServiceDestination, UiIntentSchema, UiIntentSelection,
    UiIntentSelectionValue, UiIntentSupportPosture, UiIntentText, UiIntentTransitionDestination,
    UiIntentTransitionOutcome, UiIntentUnsigned64, UiPendingIntentConfirmation,
    UiPreparedIntentPayload, UiResolvedConfirmationIntentRoute, UiResolvedProductIntentRoute,
    UiRuntimeServiceDefinitionDestination, UiSemanticInteractionFamily,
    UiTransitionDefinitionDestination, WorthUiCollectionChangeConsequence,
    UI_INTENT_ADMISSION_CAPACITY, UI_INTENT_CONFIRMATION_TTL_MILLIS,
    UI_INTENT_MAXIMUM_APPLICATION_ATTEMPTS, UI_INTENT_MAXIMUM_DESTINATION_ATTEMPTS,
    UI_INTENT_MAXIMUM_INTENT_ATTEMPTS, UI_INTENT_MAXIMUM_PROVIDER_ATTEMPTS,
    UI_INTENT_MAXIMUM_RETAINED_PAYLOAD_BYTES, UI_INTENT_PAYLOAD_FIELD_LIMIT,
    UI_INTENT_PAYLOAD_TEXT_BYTE_LIMIT, UI_PENDING_INTENT_CONFIRMATION_LIMIT,
};
